Content.Server/Anomaly/Effects/TechAnomalySystem.cs, Content.Shared/_White/Standing/LayingDownComponent.cs, README.md, Resources/Audio/Lobby/attributions.yml, Resources/Prototypes/Entities/Clothing/Head/helmets.yml, Resources/Prototypes/Entities/Markers/Spawners/Random/anomaly.yml, Resources/Prototypes/_Goobstation/tags copy.yml
Reverts funky-station/funky-station#15
=> Revert "Merge upstream 9/27/2024"

Resources/Locale/en-US/guidebook/guides.ftl, Resources/Prototypes/Entities/Objects/Misc/books.yml, Resources/Prototypes/Guidebook/rules.yml, Resources/Prototypes/Guidebook/security.yml, Resources/ServerInfo/Funkystation/Guidebook/Security/RulesOfConduct.xml
Adds Security Rules of Conduct, which gives players guidance on how to interact with the public as a security officer.
More guidance is needed for security on what and what can't be done, while also not enforcing it OOC. With these rules, they give Command and the Warden clear guidance on what should be allowed.
Nothing crazy.
**Changelog**
:cl:
- add: Added rules of conduct
=> Security Rules of Conduct

Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
Reverts funky-station/funky-station#10
=> Revert "Felinid size increase & they no longer fit into duffelbags."

Resources/Locale/en-US/traits/traits.ftl, Resources/Prototypes/Traits/speech.yml
Adds russian accent to traits menu
its a request, also russian cool
**Changelog**
:cl:
- add: Added russian accent to traits
=> Russian trait

Resources/ServerInfo/Guidebook/ServerRules/BanDurations.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13CharacterNames.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC14ICinOOC.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC6BanEvasion.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR14SecComStandard.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR15SpaceLaw.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR9MassSabotage.xml, Resources/ServerInfo/RP_Rules.txt
Reverts funky-station/funky-station#37
=> Revert "Core & Roleplay rule updates"

Resources/ServerInfo/Guidebook/ServerRules/BanDurations.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13CharacterNames.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC14ICinOOC.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC6BanEvasion.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR14SecComStandard.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR15SpaceLaw.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR4Metashield.xml, Resources/ServerInfo/Guidebook/ServerRules/RoleplayRules/RuleR9MassSabotage.xml, Resources/ServerInfo/RP_Rules.txt
=> dw about this

Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml, Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
Updated blueshield & NTR role time requirements (i forgot to before)
=> Roles update 2.0

Content.Server/_Goobstation/Heretic/EntitySystems/HereticSystem.cs, Content.Server/_Goobstation/Heretic/Ritual/CustomBehavior.Sacrifice.cs, Content.Shared/_Goobstation/Heretic/Components/SacrificedComponent.cs, Resources/Locale/en-US/_Funkystation/sacrificed.ftl, Resources/Prototypes/Body/Organs/Animal/animal.yml, Resources/Prototypes/Body/Prototypes/Animal/animal.yml, Resources/Prototypes/_Goobstation/Heretic/Objectives/heretic.yml
Sacrificing no longer GIBS people, instead it will teleport them away, give them a message about missing memory (so you can't tattle on a heretic). It also changes the sacrifice objective to sacrifice more people, and gives you double knowledge for sacrificing.
Round removing a ton of people just for a tiny bit of knowledge is kinda dogshit, and with the new targetting this makes it much more bearable to get points, and a lot of people will enjoy not being round removed.
Shitcoded and stole a bunch of code and placed them into the sacrifice script. Sacrificed players get a sacrificed comp so if you want to do anything with it you can. The safe teleport is a loop until it works so this MIGHT cause issues but im too stupid to figure it out. It will teleport you into walls but it avoids …
=> Heretics no longer gib people

Content.Server/_Goobstation/Heretic/Ritual/CustomBehavior.AshAscend.cs, Content.Server/_Goobstation/Heretic/Ritual/CustomBehavior.Sacrifice.cs
fixes some bugs with heretics
**Changelog**
=> Heretics are no longer allowed to sacrifice same target

Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
Why are we "celebrating" this guy.
Also we dont need the Goob Server host immortalized on a downstream fork.
**Changelog**
🆑 
- remove:  Removed the reference to the man. We do not need to remember.
=> Reverts "In Memorium"

Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Basic/plasma_cutter.yml
Updated the plasma cutter description (it looks like they copied the disabler description and forgot about it.)
:cl: 
tweak: Fixed the plasma cutter's description.
=> Plasma cutter description change

Resources/Changelog/Funkylog.yml, Resources/Locale/en-US/_Funkystation/guidebook.ftl, Resources/Prototypes/Guidebook/rules.yml, Resources/Prototypes/_Funkystation/Guidebook/command.yml, Resources/ServerInfo/Funkystation/Guidebook/Command/AlertLevels.xml, Resources/ServerInfo/Funkystation/Guidebook/Command/CommandStandardOperatingProcedure.xml, Resources/ServerInfo/Funkystation/Guidebook/SOP/SOP101.xml, Resources/ServerInfo/Funkystation/Guidebook/Security/EnemiesOfTheCorporation.xml, Resources/ServerInfo/Funkystation/Guidebook/Security/SecurityStandardOperatingProcedure.xml, SOP.md
:cl:
- add: Adds SOP to the game, along with the appropriate documentation
=> add SOP doc for mrp

Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/specific.yml, Resources/Prototypes/_Goobstation/Loadouts/Jobs/misc.yml
Body cams can now be equipped on the neck. Used to take up an outerwear slot.
Body cams are a new tool that are underutilized. In real life, body cams aren't clunky for police officers and other people who use them, so it shouldn't be clunky here. Wearing a Body cam is essential to making sure police officers are safe and that SOP is being followed properly.
Changed the base prototype and switched the starter loadout prototypes to use the appropriate neck tags
prob nothin lol
**Changelog**
:cl:
- tweak: Body cams now take up a neck slot
=> Body cams use a neck slot now

Resources/Locale/en-US/_Funkystation/guidebook.ftl, Resources/Prototypes/_Funkystation/Guidebook/command.yml, Resources/ServerInfo/Funkystation/Guidebook/AlertLevel/VioletAlert.xml, Resources/ServerInfo/Funkystation/Guidebook/Command/AlertLevels.xml
Added violet alert to SOP. 3rd time is a charm
:cl: add: Violet Alert added to SOP
=> Violet alert added

Resources/Locale/en-US/alert-levels/alert-levels.ftl
Updates Alert Level announcements to be consistent with Server SOP.
:cl: tweak: Tweaked alert level announcements.
=> Alert Level announcements tweaked to be consistent with Funky SOP

Resources/Maps/_Funkystation/divide.yml
i fucked up the doors on divide for evac
uhh you can actually evac the shithole
**Changelog**
=> fix le doors on le divide

Resources/Maps/_Funkystation/divide.yml, Resources/Prototypes/Maps/Pools/default.yml, Resources/Prototypes/_Funkystation/Maps/divide.yml
Adds divide to the map pool, along with little map changes
So it can be played without admin intervention
**Changelog**
:cl:
- add: Added divide to map pool
=> Add divide to map pool

Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/_Funkystation/game_presets.yml, Resources/Prototypes/_Goobstation/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml, Resources/Prototypes/secret_weights.yml
Increased antag caps overall, mostly decreased the player rate, basically just changed everything with the max amount of antags in mind on one max high pop round.
The current antag rate is absolutely terrible, you can get some really low amounts even on 80 pop rounds. I pumped it up, but mostly pumped up the cap for certain antags since they were getting really limited from the amount.
Added some calmheretics for the heretic ling gamemode. Honestly I have no idea if it'll work, this is my first time messing with it, but i coded it in the same way that calmlings work. 
**Changelog**
:cl:
- tweak: Changed antag rates to have a higher cap!
=> Change antag rates

Content.Server/Cargo/Systems/CargoSystem.Orders.cs
Cargo computer prints invoices with the same information you would find on a crate. Useful for keeping track of things between departments.
Cargo needs to keep records of purchases in case something goes wrong. It's also useful for bureaucrats.
Adds a new function called SetupInvoicePaper. Code is the same from how it would appear on a crate.
naw
**Changelog**
:cl:
- tweak: Cargo request computer now prints invoices.
=> Cargo Request Computer now prints invoices

Resources/Locale/en-US/_Funkystation/guidebook.ftl, Resources/Prototypes/_Funkystation/Guidebook/sop.yml, Resources/ServerInfo/Funkystation/Guidebook/Cargo/CargoSOP.xml, Resources/ServerInfo/Funkystation/Guidebook/Engineering/EngineeringSOP.xml, Resources/ServerInfo/Funkystation/Guidebook/SOP/SOP101.xml
Adds SOP for Cargo and Engineering, guidelines which the Quartermaster and Chief Engineer must follow.
Part of our on-going changes to add SOP to Funky Station.
XML files, nothin big.
naw
**Changelog**
:cl:
- add: SOP for Cargo and Engineering added to guidebook
=> Adds Cargo and Engineering SOP

Resources/Prototypes/Entities/Objects/Weapons/security.yml
Harmbaton damage upped to 12 from 7 and it now makes a very satisfying thwack when beating the clown's face in.
:cl:
- add: Added sounds for harmbatoning
- tweak: Harmbaton damage upped to 12
=> Thwack - Harmbatoning is So Back

Resources/Prototypes/Catalog/Cargo/cargo_medical.yml, Resources/Prototypes/Catalog/Fills/Crates/medical.yml
Added a surgery crate to Cargo
Surgery
Crate
No
- [ X] I have added media to this PR or it does not require an ingame showcase.
Probably
**Changelog**
:cl:
- add: Added surgery crate to Cargo
=> Adds surgery crate

Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
Adds a trashbag and holo projector to the ERT jani loadout and removed one of two box lights so everything spawns in backpack
Before the jani could only mop up spills and fix lights. Now they can actually clean up trash and not have their emergency kit spawn on the floor.
- [X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
- tweak: Fixes loadout issues with ERT Janitor
=> Adds stuff to ERT jani

Content.Server/_Goobstation/Heretic/EntitySystems/HereticSystem.cs, Content.Shared/_Goobstation/Heretic/Components/HereticComponent.cs
Heretics trigger a Delta Station Alert level after they ascend.
Heretics are too ambitious and obvious for their own good. No one takes the threat of a heretic seriously, so hopefully this gives people the necessary oomph to deal with them.
Rewrote the Update function in HereticSystem.cs
no
if we merge from goob again lol
**Changelog**
:cl: taydeo, Rainbeon
- tweak: Heretics now trigger Delta alert level when they ascend.
=> Heretics now trigger Delta station alert after they ascend

Content.Shared/Body/Systems/SharedBodySystem.Organs.cs, Content.Shared/Body/Systems/SharedBodySystem.Parts.cs, Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.Steps.cs, Resources/Locale/en-US/_Shitmed/surgery-popup.ftl, Resources/Prototypes/Body/Parts/silicon.yml, Resources/Prototypes/DeltaV/Entities/Mobs/Species/harpy.yml, Resources/Prototypes/DeltaV/Voice/speech_emote_sounds.yml, Resources/Prototypes/Entities/Objects/Tools/emag.yml, Resources/Prototypes/Nyanotrasen/Voice/speech_emote_sounds.yml
No credit to me, PR's merged in are listed below.
https://github.com/Goob-Station/Goob-Station/pull/918
https://github.com/Goob-Station/Goob-Station/pull/916
https://github.com/Goob-Station/Goob-Station/pull/933
https://github.com/Goob-Station/Goob-Station/pull/906
=> Mirror Goob Changes to Surgery

Resources/Prototypes/Maps/Pools/default.yml
lol
Removed Divide from mappool
Too many powergameable items, the scale feels way too big.
**Changelog**
🆑 
- remove: Removed Divide pending rework
=> Remove Divide

Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
This adds a spacelaw guidebook to the NTR lockers so they can deal with sec better if they are out of line.
Simple change to help the NTR's job go smoothly
Adds a single line to the contents of the lockerspawn list
**Changelog**
:cl:
- add: Space Law guidebook to NTR locker
=> Space Law in NTR Locker

Content.Server/_Shitmed/Medical/Surgery/SurgerySystem.cs, Content.Shared/_Shitmed/Surgery/SanitizedComponent.cs, Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.Steps.cs, Content.Shared/_Shitmed/Surgery/SharedSurgerySystem.cs, Content.Shared/_Shitmed/Surgery/SurgeryStepEvent.cs, Resources/Prototypes/Body/Parts/silicon.yml, Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml, Resources/Prototypes/_Shitmed/Body/Parts/cybernetic.yml, Resources/Prototypes/_Shitmed/Body/Parts/generic.yml
Ports: 
https://github.com/Goob-Station/Goob-Station/pull/969 - Bugfixes, prediction, cleanups.
https://github.com/Goob-Station/Goob-Station/pull/971 - Bugfixes too
Tested on local build, there still bug with no shoes even after 972 port
=> Port surgery fixes from goob

Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
Wrong surgery crate oops
:cl:
- fix: surgical supplies crate now contains surgical supplies
=> Surgery crate fix

Content.Server/Administration/ServerApi.cs, Content.Server/Administration/Systems/BwoinkSystem.cs, Content.Server/Discord/WebhookPayload.cs
Ported https://github.com/new-frontiers-14/frontier-station-14/pull/2283
No longer do admins need to be ingame for every AHelp.
This PR requires:
1. Something that can handle the discord side, see original PR for details. You can also use my [RedBot cog](https://github.com/sleepyyapril/april-cogs), if you use RedBot.
2. A set admin.api_token CVar value to use on the discord side.
3. CVar status.enabled being true
This PR changes the way the BwoinkSystem works to allow for custom URLs instead of just an id and a token for webhooks, as well as adding an admin API HTTP POST method under ``/admin/actions/send_bwoink``.
**Changelog**
:cl:
ADMIN:
- add: Added the ability to reply to AHelps while exclusively on discord.
=> Discord Ahelp Reply System (#2283)

Resources/Locale/en-US/reagents/meta/medicine.ftl, Resources/Prototypes/Reagents/gases.yml, Resources/Prototypes/Reagents/medicine.yml, Resources/Prototypes/Recipes/Reactions/medicine.yml
adds four (!) new chems: pyroxadone, ardthrynkole, natusixadone, and hypothium. the former three are alternatives to cryogenics, requiring medical to replace their freezer with a heater to use. pyroxadone works the same as cryox, while ardthrynkole and natusixadone are meant to be used on frozen or hollowed corpses, respectively. this also removes doxa's worksOnTheDead component, meant to discourage medical lings from roundstart eating corpses then healing them back up. hypothium is a side grade to healium, and gives its condensed version a use. condensed healium also very very minorly heals now, so it does Something when condensed. 
there's no chem to specifically meant to heal frozen corpses, excluding necrosol. ardthrynkole fills that niche, and introduces a subset of chems for medical …
=> Pyro update

Resources/Prototypes/_Funkystation/Catalog/Cargo/cargo_fun.yml, Resources/Prototypes/_Funkystation/Catalog/Fills/Crates/fun.yml
Added a cops and robbers crate to the cargo order console.
Because its goofy, fun and should lead to good shenanigans. Plus who doesnt love some harmless pew pew
Adds a crate with 2 cowboy hats, 2 outlaw hats, 4 cowboy boots,
4 capguns, 4 speedloaders, and 2 boxes of capgun rounds.
**Changelog**
:cl:
- add: Adds Cops and Robbers crate to cargo order console
=> Cops and Robbers

Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml, Resources/Prototypes/Loadouts/loadout_groups.yml
Added Cirno plushie to loadout.
**Changelog**
:cl:
- add: You can now add a Cirno plushie to your loadout.
=> Added Cirno plushie to loadout

Resources/Prototypes/Reagents/medicine.yml
it used to look exactly like bic
(hopefully) a little more accessible 
yml 
**Changelog**
:cl:
- tweak: changed pyroxadone's color to not look like bic
=> makes pyrox look less like bic

Resources/Prototypes/Reagents/medicine.yml
it sux. now it less sux
healing a linged corpse would cause the entire body + limbs to have ~100 burn damage. this isnt a major issue with surgery imo but it's really really annoying and honestly should not do that
**Changelog**
:cl:
- fix: buffed pyroxadone & related chems
=> buff pyrox and related

Content.Server/Explosion/EntitySystems/TriggerSystem.cs, Content.Server/Flash/FlashSystem.cs, Content.Server/_Funkystation/Construction/Condition/RevolutionaryCrafterHasComponent.cs, Content.Shared/_Funkystation/Revolutionary/RevolutionaryFlashOnTriggerComponent.cs, Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml, Resources/Prototypes/_Funkystation/Entities/Weapons/revolutionary_flashbang.yml, Resources/Prototypes/_Funkystation/Recipes/Revolutionary/revolutionary_flashbang.yml
:cl:
- add: The Revolutionary Flashbang, a new favorite for young revolutionaries.
=> REDO: Adds the Revolutionary Flashbang

Resources/Prototypes/Nyanotrasen/Entities/Objects/Specific/Mail/tools.yml
Adds the envelope to the mailbags whitelist
Kinda dumb to have a mailbag that cant hold basic mail
- [X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
- tweak: Mailbag can now hold envelopes
=> Mailbag Whitelist

Resources/Prototypes/Roles/Jobs/CentComm/official.yml
Removes the centcom pen from the debug outfits pocket.
There is already one inside the PDA the outfit comes from leading to extra forgery capable pens and generally just clogs the inventory.
No changelog as this only affects admins and admemes
- [ X] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
=> Centcom Default Outfit Change

Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/_Funkystation/game_presets.yml, Resources/Prototypes/_Goobstation/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/game_presets.yml, Resources/Prototypes/game_presets.yml, Resources/Prototypes/secret_weights.yml
Added blob as a normal spawning gamemode in secret, and added blobtots (traitors and blob) as well. I also removed the heretic gamemodes and reverted them back into a side antag like thief.
First off, heretic needs to be a side antag on the station. While they can be really powerful, they suck extremely bad without someone or something else getting secs time and attention. As well, they really don't work together as well, so having 4 of them really doesn't do much but make crossfire in the objectives. Don't get me wrong, I get the idea of having them in their own gamemode, but i think it would work better here as a side antag in any mode with a max of like 1 or 2 depending on how many tay wants. (tldr, heretics need to sacrifice like 4 people, tots at most have to kill like 1 on average, …
=> Secret antag rate changes

Resources/Prototypes/_Funkystation/game_presets.yml, Resources/Prototypes/_Goobstation/Changeling/Roles/Antags/changeling.yml, Resources/Prototypes/_Goobstation/game_presets.yml, Resources/Prototypes/game_presets.yml
Changed changeling req from 5 sec hours to 3 sec hours
Added subgamemode into every major mode so thieves and heretics can spawn.
I have no idea why it was disabled before but this should fix never seeing thief and heretic like ever.
**Changelog**
:cl:
- fix: Fixed thief and heretic spawning
=> Fix Subgamemode

Resources/Prototypes/GameRules/midround.yml
literally changed 1/15 to 1/25 so we only get 3 thieves on 75 instead of 45
i hate my life
**Changelog**
:cl:
- tweak: Changed thief rates
=> thief rate change

Content.Server/_Goobstation/Heretic/Abilities/HereticAbilitySystem.Ash.cs, Content.Shared/_Goobstation/Heretic/Heretic.Abilites.cs, Resources/Prototypes/_Goobstation/Heretic/Heretic/heretic_knowledge.yml
Fixed the issue of shitmed causing the poor ash ascended heretic to lose all their limbs and die
john shitcode
**Changelog**
:cl:
- fix: Fixed ash ascended heretic's limbs falling off
=> Fix ash heretics limbs falling off

Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
The HAMTR now accepts weaponry.
I'm sure allowing Hamlet to be armed will have zero effects on balance, and will result in zero exploded Robotics departments. :trollface: 
4 line YAML change real
(added equipmentWhitelist and set it to CombatMech and SmallMech)
**Changelog**
:cl:
- tweak: The HAMTR can now be armed.
=> Arm the HAMTR

Resources/Maps/Event/wcmonalds_shuttle.yml
On Wednesday, December 4th at 6:40 A.M., the CEO of Nanotrasen United Healthcare® was assassinated by an "Unknown" in the maintenance tunnels below Medbay on his way to an investors meeting. The attacker has been deemed a Syndicate Traitor. Any information leading to his arrest will be rewarded with an up to 10,000 credit reward.
tay brought up the idea of a event map / shuttle like this, and i was like "why not". 
adds "wcmonalds_shuttle.yml" to "/Resources/Maps/Event"
None. This just adds one YML file.
**Changelog**
:cl:
- add: Added the WcMonalds shuttle to the Event Map folder.
=> WcMonalds Event Shuttle

Content.Server/Procedural/DungeonJob/DungeonJob.PostGenBiome.cs
this has been fixed upstream for 3 weeks 
**Changelog**
:cl: TheShuEd
- fix: Fixed space chunks loot spawning
=> debris spawns loot again

Resources/Prototypes/borg_types.yml
https://github.com/Goob-Station/Goob-Station/pull/1231
**Changelog**
:cl: AstroDogeDX
- fix: Medborgs can now perform surgery again.
=> Port: Fix medborg surgery

Content.Shared/CCVar/CCVars.Surgery.cs
Allows you to do self surgery. (duh)
Uh cuz it's awesome???
**Changelog**
:cl:
- tweak: You can now do surgery on yourself!
=> Enable self surgery

Content.Server/Prayer/PrayerSystem.cs
Copied fax code so that prayers also give admins an alert so we don't miss prayers or rings (abusing this feature may result in a smite)
Not adding it to the changelog because I don't want casuals to know
=> The Prayerening

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/rehydrateable.yml
First off, made it so you can e mag the biofab in botany to produce carp cubes and abominations.
Second off, lower the plasma and biomass costs way down. Mostly the plasma costs because it was absolutely wayyy too much. The tick cube is still in the e magged cube fab, since it takes much more plasma it'll have more of a niche with it.
There's no real like reason to for this. Biomass is extremely annoying to get up, and botany, the biggest biomass maker, doesn't even have access to the biocube fab. So these buffs should make it much more viable to use naturally.
**Changelog**
:cl:
- add: Botany biofabs are now E-maggable!
- tweak: Antag cubes are much more less costly to fab!
=> Buff syndicate cubes

Resources/Locale/en-US/preferences/loadout-groups.ftl, Resources/Prototypes/Loadouts/loadout_groups.yml, Resources/Prototypes/Loadouts/role_loadouts.yml
Moved security bodycam from outerwear slot to neck slot in security loadouts
You can't even equip the bodycam in outerwear anymore
Five nights at wardens
yaml (real)
idk i can't code
**Changelog**
:cl:
- tweak: Moved security bodycam from outerwear to neck in loadouts
=> Moved security bodycam from outerwear to neck in loadouts

Resources/Prototypes/Catalog/Fills/Boxes/ammunition.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/light_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/light_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/light_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/light_rifle.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/security.yml, Resources/Prototypes/_Funkystation/Entities/Weapons/annabelle.yml
Added silver rifle ammo. It deals 10 blunt & 10 holy damage
For undead & other such supernaturals
a
dont wanna
- [ sure why not] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ nah] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
:cl: Miiish
- add: Added silver rifle ammo with Holy damage
- tweak: Annabelle is a little quieter
=> Added silver rifle ammo

Content.Server/_EinsteinEngines/Flight/FlightSystem.cs, Resources/ServerInfo/Guidebook/Mobs/Harpy.xml
ports [#1363](https://github.com/Goob-Station/Goob-Station/pull/1363) and [#1141](https://github.com/Goob-Station/Goob-Station/pull/1141)
documentation for new players
**Changelog**
:cl: SolsticeOfTheWinter
- tweak: harpies can start flying while walking
- tweak: harpy documentation is better now
=> [port] minor harpy fixes

Resources/Locale/en-US/station-laws/laws.ftl
Fixes dungeon master lawset.
Dungeon master was broken, it displayed "law-dungeon-1" for all the laws.
Replaces  the "game" with dungeon in laws
I hope there isn't any.
**Changelog**
🆑
- fix: dungeon master is now working! rejoice!!
=> fixes dungeon master lawset

Resources/Prototypes/_Funkystation/Entities/Objects/Fun/toys.yml
Added a few lines of code to make the cargo harpy plushie caw when used, thrown, etc. Some whitespace was changed, no clue if that matters.
tbh this isn't important to anyone but me. Wanted to add this in since I saw it was missing, was going to ask someone but I realized I already had a dev environment to do it myself.
Copied code from other plushies that made noises when interacted with, linked to deltaV's harpy caw noise.
https://github.com/user-attachments/assets/568814f5-f03e-4004-bfaf-5c6f1ace7327
N/A
**Changelog**
:cl:
- tweak: The Cargo Harpy plushie will now caw.
=> Cargo Harpy plushie will now caw

Content.Server/Zombies/ZombieSystem.Transform.cs, Content.Shared/Zombies/ZombieComponent.cs, Resources/Prototypes/Entities/Mobs/NPCs/animals.yml, Resources/Prototypes/ai_factions.yml
Mice and mothroaches deal damage once more, as God intended 
Also zom-bees are real & pests can now spread the virus.
ALSO ALSO zombies heal slightly more health passively now
:cl: Miiish
- tweak: Mice and mothroaches deal damage again (and can zombify people)
- tweak: Zom-bees are real
- tweak: Zombies have slightly better regeneration
=> Needs More Mouse Bites

Resources/Prototypes/DeltaV/Voice/speech_emote_sounds.yml
Harpies can now yap and gekker like Vulps.
Thought that they have every else sound in the game, that to give them gekker and yap too.
just copied pasted the code from vulp
**Changelog**
🆑 
- add: Harpies can now yap and gekker.
=> harpi yap & gekker

Resources/Locale/en-US/species/species.ftl
=> Fixes monkey not having a species name

Resources/Locale/en-US/store/uplink-catalog.ftl, Resources/Prototypes/Catalog/uplink_catalog.yml, Resources/Prototypes/Entities/Objects/Misc/monkeycube.yml, Resources/Prototypes/Entities/Objects/Specific/rehydrateable.yml
Dino ops real.
100 TC for 6 random dino cubes! Running after spraying HIGHLY recommended.
Per Keir's request
:cl: Miiish
- add: Added Syndicate Dino Cube boxes, purchasable by the Chef, Zookeeper, and Scientist.
=> Adds a Syndicate Dino Cube Box

Resources/Prototypes/Entities/Structures/Furniture/sink.yml
Title
Sinks having so little water was a lag change not a balance change https://github.com/Goob-Station/Goob-station/pull/1095
yaml
**Changelog**
:cl:
- fix: Fixed the station plumbing, sinks now have plenty of water again
=> Changed sink capacity from 500 to 9999999

Resources/Maps/_Funkystation/roid_outpost.yml
I added better SM room to roid.
The previous room had many issues such as no way to filter gases out and generally hard to maintain.
Added a new and improved SM room. It is much easier to use for newer players and gives more room to play with the SM.
**Changelog**
:cl:
- Added a new and improved SM room to roid.
=> Added better SM room

Resources/Prototypes/Guidebook/rules.yml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC0.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13MRPRoleplay.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13NoEORG.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC6Metagaming.xml
Added NLR in because I forgot.
Changed the RP server rules to just disallow EORG
Oopsies
=> Rules Update 2

Content.Shared/Physics/CollisionGroup.cs, Content.Shared/Standing/StandingStateSystem.cs, Resources/Prototypes/Entities/Structures/plastic_flaps.yml
RAHHHHHHHHHH Title
Also, plastic flaps are now MidImpassable (medium objects can pass through fine)
:cl: Miiish
- fix: Players can no longer crawl over tables
=> Players can no longer crawl over tables

Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
*gulps
spelling
makes it more readable
no
- [ i didn read that ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
idfk
**Changelog**
=> fixes spelling in heretic thingy

Resources/Prototypes/Catalog/uplink_catalog.yml, Resources/Prototypes/Entities/Objects/Misc/monkeycube.yml, Resources/Prototypes/Entities/Objects/Specific/rehydrateable.yml, Resources/Prototypes/_Funkystation/Catalog/uplink_catalog.yml, Resources/Prototypes/_Funkystation/Entities/Objects/Misc/monkeycube.yml, Resources/Prototypes/_Funkystation/Entities/Objects/Specific/rehydrateable.yml
Seriously? You're just gonna clutter our github with stupid garbage like this?
moves my dino cube stuff to funkystation folders :)
=> Moves Dino Cube Stuff To Proper Folders

Resources/Maps/_Funkystation/DMVStation.yml
Fixed the missing and incorrect spawns
Who would have thought that mapping for 9 hours straight would lead to errors?!?!?
**Changelog**
Still no CL because its an event map
=> Fixing the DMV

Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml
Renames all the pride clocks to {"name" pride cloak}.
Based off: https://github.com/space-wizards/space-station-14/pull/34645
Previously, the pride cloaks were all changed to be jokes, I didnt understand half of them and some people I know wanted to change it.
**Changelog**
:cl:
- tweak: Pride cloaks now show their names instead of a pun or joke.
=> Pride cloak renames.

Resources/Prototypes/_Funkystation/Entities/Weapons/miniaturelaserpistol.yml
Fixed a minor spelling mistake and the capitalization of disabler plus.
Maintain excellent player experience.
Spelling mistake was fixed.
**Changelog**
:cl: Cthyga
- fix: Fixed description of disabler plus
- fix: Changed capitalization of disabler plus to be in line with other items.
=> Fixed spelling for disabler plus

Resources/Prototypes/_Funkystation/Entities/Weapons/miniaturelaserpistol.yml
The disabler plus would lose it's flashlight after firing. This was due to netsync being disabled. Removing `netsync: false` fixed the issue.
The flashlight vanishing diminished the fun of the weapon.
`netsync: false` was removed totally in `miniaturelaserpistol.yml`.
**Changelog**
:cl: Cthyga
- fix: Fixed the disabler plus integrated light vanishing.
=> Fixed Disabler Plus Light Vanishing After Firing

Resources/Locale/en-US/species/species.ftl
forgot that kobolds exist - https://github.com/funky-station/funky-station/pull/296
technical details -
a line
=> Fixes kobolds not having a species name

Resources/Prototypes/Roles/Jobs/Wildcards/security_clown.yml
I was just advertising that this exists I swear!  Totally intentional!
**Changelog**
:cl:
- fix: security clown always showing up in job preferences
=> Fix Security Clown showing up in job pref. / loadout UI thing

Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml
Made cigarettes grindable
Prerequisite for a new Drink and is also Funny
Made the base cigar extractable
:cl: Miiish
- tweak: Cigarettes are now grindable
=> MAKE CIGARETTES GRINDABLE AGAIN

Resources/Prototypes/Maps/Pools/default.yml
Removed Train from map pool
Train is pain
put a # in front of it in the pool
- [ x] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
=> Remove Train

Content.Server/_Funkystation/Speech/EntitySystems/FunkyAccentSystem.cs
With minor modifications.  Makes you moderately hard to understand.
Logic is as close to the .dm code as possible.  Probably be refactored with C# in mind?
**Changelog**
=> Funky accent from goon

Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl
Heretic Ability Grammar
Makes it readable for big brain Heretic mains
Changes words.
**Changelog**
=> Heretic Wording change v1

Resources/Prototypes/_Goobstation/Entities/Objects/Misc/subdermal_implants.yml
=> Revert "Bluespace Implant description change (#366)"

Resources/Prototypes/Entities/Structures/Machines/holopad.yml
Changes the holopads general power draw as right now they, at a resting state use up 50 more watts than even a chemmaster and there are a LOT of them per station so it causes an unnecessary amount of power draw. On Roid for example going from 300 watts to 100 watts saves 11.4kW and would more than likely draw even more on bigger maps. 
Standby holopad power draw was just way too high. 100 watts is on par with a jukebox which feels fair for something that is powered down most of the time.
Watts 300 ->100
**Changelog**
:cl:
- tweak: Lowered holopad power consumption
=> Changes to holopad wattage

Resources/Locale/en-US/_Goobstation/Heretic/abilities/heretic.ftl, Resources/Locale/en-US/_Goobstation/Heretic/heretic/ascensions.ftl, Resources/Locale/en-US/_Goobstation/Heretic/heretic/misc.ftl, Resources/Locale/en-US/_Goobstation/Heretic/heretic/rituals.ftl, Resources/Locale/en-US/_Goobstation/Heretic/roles/heretic.ftl
Heretic wording to fix readability and 
Just fixing certain grammatical errors. 
**Changelog**
=> Heretic wording changes 1.1

Content.Server/StationEvents/Components/VentCrittersRuleComponent.cs, Content.Server/StationEvents/Events/VentCrittersRule.cs, Resources/Locale/en-US/deltav/station-events/events/vent-critters.ftl, Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/GameRules/pests.yml, Resources/Prototypes/_Goobstation/GameRules/Dynamic/midround.yml
- Originally from DeltaV, ported to Goob, Harmony, etc., & now here!
- This PR also includes changes from a follow up commit that fixes critters rarely spawning by replacing probability with an entity table for spawns.
See: https://github.com/DeltaV-Station/Delta-v/pull/2517 and https://github.com/DeltaV-Station/Delta-v/pull/2495
Going to go over this again at a later date to make sure I didn't miss anything.
**Changelog**
:cl: 
Ported vent critter rework from DeltaV
=> Port Vent Critter Event Rework

Resources/ServerInfo/Funkystation/Guidebook/Legal/LegalSOP.xml
Added Lawyer SOP section to the Legal SOP section of the Guidebook, partially inspired by Paradise Station IAA SOP.
Lawyers did not have SOP before now.
Added text to a .yml file.
N/A
N/A
**Changelog**
:cl:
- add: Added Lawyer SOP
=> Added Lawyer SOP

Resources/Audio/Lobby/attributions.yml, Resources/Prototypes/_Goobstation/Catalog/Jukebox/Standard.yml
Added a new custom song made by Funky's very own Dynzz.
Check out their stuff here!
https://open.spotify.com/album/647V2sE0CkxEShsYSdwAiC?si=8qPTUnWpSSCYMCdlGx2XNw
https://www.youtube.com/channel/UCvMmT757OxGUjaJs2ZTbbmg
:cl: Dynzz
- add: "Iron Will" by Dynzz added as lobby music
=> "Iron Will" by Dynzz as Lobby Music

Resources/ServerInfo/Funkystation/Guidebook/Legal/LegalSOP.xml, Resources/ServerInfo/Funkystation/Guidebook/Security/SecurityStandardOperatingProcedure.xml
Legal SOP and Security SOP
Specific guidelines were needed for Court proceedings, IAA's primary duties needed to be moved to the top, and new guidelines for how Security is meant to treat Lawyers was needed.
Edited SOP .xml files.
N/A
N/A
**Changelog**
:cl:
- tweak: Changed Legal SOP and Security SOP to reflect new guidelines for Lawyers, IAA, and Court
=> New Legal and Sec SOP

Content.Server/_Funkystation/EntityEffects/CureChangelingInfection.cs, Content.Server/_Goobstation/Changeling/ChangelingEggSystem.cs, Content.Server/_Goobstation/Changeling/ChangelingInfectionSystem.cs, Content.Server/_Goobstation/Changeling/ChangelingSystem.Abilities.cs, Content.Shared/_Goobstation/Changeling/Changeling.Actions.cs, Content.Shared/_Goobstation/Changeling/Changeling.DoAfter.cs, Content.Shared/_Goobstation/Changeling/ChangelingInfectionComponent.cs, Content.Shared/_Goobstation/Changeling/ChangelingInfectionImplantComponent.cs, Resources/Locale/en-US/_Funkystation/chemistry/effects.ftl, Resources/Locale/en-US/_Funkystation/implant/implant.ftl, Resources/Locale/en-US/_Funkystation/reagents/meta/medicine.ftl, Resources/Locale/en-US/_Goobstation/changeling/abilities/changeling.ftl, Resources/Locale/en-US/_Goobstation/changeling/store/changeling-catalog.ftl, Resources/Prototypes/_Funkystation/Implants/implanters.yml, Resources/Prototypes/_Funkystation/Implants/subdermal_implants.yml, Resources/Prototypes/_Funkystation/Reagents/medicine.yml, Resources/Prototypes/_Funkystation/Recipes/Reactions/medicine.yml, Resources/Prototypes/_Funkystation/Store/uplink_catalog.yml, Resources/Prototypes/_Funkystation/tags.yml, Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml, Resources/Prototypes/_Goobstation/Changeling/Catalog/changeling_catalog.yml
I love making people horrified over very simple game mechanics.
Adds suggestion https://discord.com/channels/1276640157511979008/1336249133081694291, specifically the first idea they had during their DM (conversion)
This makes Changelings a potential conversion antagonist.
I thought it was funny. Also, I need to get used to the Funky codebase.
Adds a new component: ChangelingInfected
People with this component will be converted into a changeling after a certain amount of time defined as three specific delays in the component.
The first delay, FirstSymptoms, defines when the infected begins experiencing the initial symptoms, specifically those of a highly low biomass changeling.
~~Congragulations for actually reading the Technical details. Don't open the Media tab, it's not Media.~~
The …
=> Changeling Infections

Resources/Maps/_Funkystation/amber.yml, Resources/Maps/_Funkystation/atlas.yml, Resources/Maps/_Funkystation/bagel.yml, Resources/Maps/_Funkystation/box.yml, Resources/Maps/_Funkystation/cluster.yml, Resources/Maps/_Funkystation/core.yml, Resources/Maps/_Funkystation/kettle.yml, Resources/Maps/_Funkystation/loop.yml, Resources/Maps/_Funkystation/marathon.yml, Resources/Maps/_Funkystation/meta.yml, Resources/Maps/_Funkystation/oasis.yml, Resources/Maps/_Funkystation/packed.yml, Resources/Maps/_Funkystation/saltern.yml
**Changelog**
:cl:
- tweak: silos are remapped
=> remap silo

Resources/Locale/en-US/_Funkystation/reagents/meta/exotics.ftl, Resources/Prototypes/Polymorphs/polymorph.yml, Resources/Prototypes/_Funkystation/Reagents/exotic.yml, Resources/Prototypes/_Funkystation/Recipes/Reactions/exotic.yml
corgium is no longer permanent (about a minute polymorph at 20u). instead evil corgium can be made with corgium + vestine to permanently polymorph people
this is my mald pr for spending an hour as a corgi
**Changelog**
:cl:
- tweak: corgium will no longer turn you into a corgi forever. now you have to make evil corgium
=> corgium nerf

Resources/Prototypes/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
Added more wintercoats to winterdrobe
A bigger variety of clothing
**Changelog**
:cl:
- add: Added more wintercoats to winterdrobe
=> More wintercoats

Resources/ServerInfo/Guidebook/Security/SpaceLaw.xml, Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Changed SpaceLaw.xml to include repeat offenses as well as making them both the same file.
- [x ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
- tweak: Tweaked Space Law to include repeat offenses
- tweak: Both instances of SpaceLaw.xml are now the same to prevent confusion
=> Space Law Changes

Content.Server/_EE/Supermatter/Systems/SupermatterSystem.Processing.cs
i forgor
**Changelog**
:cl:
- fix: the sm produces pluoxium again
=> readd pluox to the sm

medidrobe.yml
Added the psychologist jumpsuit/skirt to the MediDrobe.
Med can now look awesome, I guess that's a buff.
Added two lines of code.
**Changelog**
:cl:
- add: Psychologist Jumpsuit and Jumpskirt to the MediDrobe
=> Add Psychologist Clothes to MediDrobe

Content.Server/_EE/Supermatter/Systems/SupermatterSystem.Processing.cs
no longer will it delam after the intern spaces it 
**Changelog**
:cl:
- fix: the sm will no longer rapidly lose health while inactive
=> sm doesn't take damage while inactive anymore

Content.Server/_EE/Supermatter/Systems/SupermatterSystem.Processing.cs, Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Changelings.xml
**Changelog**
:cl:
- tweak: the cling guidebook entry has been updated to include information about natusixadone
=> update cling guidebook

Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Shields/shields.yml
it changes oraganic shield or whatever to organic shield
i saw it ingame and i was deeply saddened
i fixed a typo in one line on a file surely this won't break the game
- [yea] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [yea] I have added media to this PR or it does not require an ingame showcase.
shouldn't be any
**Changelog**
:cl:
- fiksss: corrected a spelling mistake for the organic shield
=> ummmm fixes another spelling mistake

Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
IPCs should leave fingerprints.  This is a one line .yml change :)
It honestly feels like an oversight, and I cannot think of any reason for them to leave no trace at all.
Just add the component EZPZ
**Changelog**
tweak: IPCs now leave fingerprints
=> Give IPCs the finger(print)

Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Blob.xml
Rewrites a majority of the Blob Guidebook page, making it accurate, along with some extra information.
Moreless for a more clear read of the page, considering it was slightly inaccurate. (No, it isn't Gamma Alert, and no, "Cbrn" isn't sent.)
Rewrite of the Blob Guidebook. That's it. That is literally the entire PR.
Confirm the following by placing an X in the brackets [X]:
**Changelog**
:cl:
- tweak: Major rewrite of the Blob Guidebook page.
=> Rewrite of the Blob.

Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Blob.xml
Reverts funky-station/funky-station#495
=> Revert "Rewrite of the Blob."

Resources/Locale/en-US/_Shitmed/surgery/surgery-popup.ftl
:cl: 
- remove: Cats are no longer blueberries
=> missing lang file fixed

Resources/Changelog/Funkylog.yml
Funkylog real again (and first)
yes
**Changelog**
=> Manually fixed the funkylog, made it first

Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
I put the psychologist clothes in the meddrobe without messing it up that time.
Cause I messed it up the first time.
Two lines of code.
**Changelog**
=> Psych Clothes For Real

Resources/Locale/en-US/_Funkystation/sacrificed.ftl, Resources/Locale/en-US/_Funkystation/traits/traits.ftl, Resources/Locale/en-US/_Goobstation/species/gingerbread.ftl, Resources/Locale/en-US/_Impstation/ghost/roles/ghost-role-dino.ftl, Resources/Locale/en-US/_Impstation/reagents/meta/biological.ftl, Resources/Locale/en-US/_Mono/Traits/traits.ftl, Resources/Locale/en-US/_NF/mail/mail.ftl
Rewording of a few things and spelling fixes
Makes things readable
**Changelog**
=> Grammar station 1.0

Content.Server/Flash/FlashSystem.cs, Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
Fixes #411, moves the popup to OnPostFlash
(previously, popup would occur regardless of conversion. now it occurs only on a successful conversion)
=> Rev flash popup on conversion

Content.Client/_DV/Surgery/SurgeryCleanSystem.cs, Content.Client/_DV/Surgery/SurgeryDirtinessItemStatus.cs, Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml, Resources/ServerInfo/_Shitmed/Guidebook/Medical/Surgery.xml
- adds info about the sterile system to the guidebook
- ports [DV #3215](https://github.com/DeltaV-Station/Delta-v/pull/3215) because i forgot to originally
- reverts the doAfter duration for tend burn/bruise (its faster again)
**Changelog**
:cl: correspond, sowelipililimute
- tweak: The clean meter of a surgery tool in the hotbar now also indicates the cleanliness of the gloves and absence of a mask
- fix: the guidebook now has info about sterile surgery tools
- tweak: tending bruise/burn is faster to do
=> sterile system fixes

Resources/Locale/en-US/store/uplink-catalog.ftl, Resources/Prototypes/Entities/Objects/Misc/business_card.yml, Resources/Prototypes/EstacaoPirata/Entities/Objects/Misc/syndicate_cards.yml, Resources/Prototypes/_Funkystation/Catalog/uplink_catalog.yml, Resources/Prototypes/_Funkystation/Entities/Clothing/Head/hats.yml
Adds a throwable damage dealing bowler hat to the uplink as well as make thrown syndicate business cards and playing cards deal damage.
Adds a new secret wearable weapon to syndis and makes more of a reason for people to have syndi business and playing cards on their person besides RP flair.
Razor Bowler hat added for 7 tc in uplink. Deals 20 damage on throw
Syndicate business cards now deal 10 damage on throw
Syndicate playing cards now deal 5 damage on throw
**Changelog**
:cl:
- add: Added razor lined bowler hat to uplink. 
- tweak: Syndicate business and playing cards now deal throw damage
=> Syndicard throwables update

Resources/Locale/en-US/flavors/flavor-profiles.ftl, Resources/Prototypes/Flavors/flavors.yml
*screams
oops. didn't realize I was missing two file edits.
altered flavors.yml and flavor_profiles.ftl to actually have the flavors for the fried shrimp
I dunno, having indescribable shrimp makes me sad?
it's pretty much a bug fix
I would actually be pissed if I somehow broke something with two file edits
**Changelog**
:cl:
- fixed: cooked shrimp (Shreersh) now has an actual flavor, rather than being indescribable
=> Shrimp was lacking flavor profile!

Resources/Maps/_Funkystation/atlas.yml, Resources/Maps/_Funkystation/bagel.yml, Resources/Maps/_Funkystation/box.yml, Resources/Maps/_Funkystation/cluster.yml, Resources/Maps/_Funkystation/core.yml, Resources/Maps/_Funkystation/elkridge.yml, Resources/Maps/_Funkystation/kettle.yml, Resources/Maps/_Funkystation/marathon.yml, Resources/Maps/_Funkystation/meta.yml, Resources/Maps/_Funkystation/oasis.yml, Resources/Maps/_Funkystation/omega.yml, Resources/Maps/_Funkystation/packed.yml, Resources/Maps/_Funkystation/saltern.yml
Adds Departmental Communications Consoles to most maps, removes some self-insert plushie crates I found.
Resolves #527 
**Changelog**
:cl:
- add: Most Maps now have departmental Communication Consoles.
=> Map Updates 18-03-25 v2 (Sick Edition Electric Boogaloo)

Resources/Prototypes/Catalog/VendingMachines/Inventories/pride.yml
Forgot to do it last time.
**Changelog**
:cl: 
- fix: The Ace Pride Cloak is now in the Pride-O-Mat!
=> Ace Pride cloaks in the pride-o-mat

Resources/Prototypes/_Impstation/CosmicCult/Tileset/monument.yml
**Changelog**
:cl:
- fix: you can relocate the cosmic cult monument
=> cosmic cult hotfix

Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml, Resources/Prototypes/_DV/Species/rodentia.yml, Resources/Prototypes/_Impstation/Entities/Mobs/Customization/Markings/scars.yml
Changes, Adds, and Removes some requirements for the use of markings in customization 
Shares the impstation scar markings among most species.
Removes `sexRestriction: [Male]' from the top surgery scars. Adds an extra slot to rodentia as most species dont have a 2 limit.
**Changelog**
:cl:
- tweak: More markings have been shared across species.
- tweak: Some requirements to use certain markings have been removed.
=> Marking Changes.

Content.Server/_Goobstation/Store/Conditions/HereticPathCondition.cs
thank you impstation for fixing this for us [#1960](https://github.com/impstation/imp-station-14/pull/1960)
**Changelog**
:cl:
- fix: heretics can use their stores again
=> [port] heretic fixy fix 

Resources/Prototypes/Reagents/medicine.yml
Make Ethylredoxrazine 10x more effective
Someone gave me so much healium that I didn't get better for the rest of the shift.
increase drunkenness reduction of Ethylredoxrazine from 6 to 60
n/A
n/A
**Changelog**
:cl:
- tweak: Ethylredoxrazine is now 10x as effective at clearing up drunkenness
=> Increase potency of Ethylredoxrazine

Resources/Audio/Lobby/attributions.yml, Resources/Prototypes/SoundCollections/lobby.yml
Adds two lobby songs, requested by taydeo
https://soundcloud.com/pigeonbeans/ashwalking
https://soundcloud.com/pigeonbeans/minerals
**Changelog**
:cl:
- add: New lobby music
=> 2 Lobby songs.

Resources/Locale/en-US/preferences/ui/humanoid-profile-editor.ftl, Resources/Prototypes/Traits/categories.yml, Resources/Prototypes/Traits/quirks.yml, Resources/Prototypes/_DV/Traits/altvision.yml, Resources/Prototypes/_Funkystation/Traits/quirks.yml, Resources/Prototypes/_Goobstation/Traits/religions.yml, Resources/Prototypes/_Mono/Traits/quirks.yml
This disables traits that can be gamified or otherwise abused, encouraging poor roleplay.
If you want these re-enabled, go ahead and revert this commit. 
Currently, most traits either are broken, have weird unintended consequences, or encourage people to power game. People take the Blindness trait and get surgery to replace their eyes. People min-max a thing that was originally intended to add flavor to role-play. It was a fun experiment to see what could be done, but ultimately they are not worth keeping around.
Comments out a bunch of stuff. Creates a new category called Vision that allows people to pick deuteranopia or ultravision.
None.
**Changelog**
:cl:
- remove: Removed the NaturalRegeneration, NaturalResiliance, Hemophiliac, CarefulSteps, TableHider, TemperatureTolerance and …
=> Removed Certain Traits

Resources/Prototypes/Entities/Structures/Power/smes.yml
Doubles adv. SMES capacity.
Fixes SMES names to align with fork capacities.
Triples SMES joule value. ~5k when full
Goob doubled basic SMES before the advanced one was added, so capacities were both 16MJ.
Makes power selling viable. (goob tripled it again, but it was strong enough)
Changed yaml.
Same idea as this.
https://github.com/Goob-Station/Goob-Station/pull/1474
**Changelog**
:cl:
- fix: Adv. SMES capacity buffed (2x)
- tweak: Filled SMES sell for good money.
=> SMES fixes and buff

Resources/Locale/en-US/_Impstation/alert-levels/alert-levels.ftl, Resources/Locale/en-US/guidebook/guides.ftl, Resources/Prototypes/Guidebook/rules.yml, Resources/Prototypes/_Funkystation/Guidebook/sop.yml, Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml, Resources/ServerInfo/Funkystation/Guidebook/AlertLevel/OctarineAlert.xml, Resources/ServerInfo/Funkystation/Guidebook/Cargo/CargoSOP.xml, Resources/ServerInfo/Funkystation/Guidebook/Command/CommandStandardOperatingProcedure.xml, Resources/ServerInfo/Funkystation/Guidebook/Engineering/EngineeringSOP.xml, Resources/ServerInfo/Funkystation/Guidebook/Medical/MedicalStandardOperatingProcedure.xml, Resources/ServerInfo/Funkystation/Guidebook/Science/ScienceStandardOperatingProcedure.xml, Resources/ServerInfo/Guidebook/NewPlayer/CharacterCreation.xml, Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml, Resources/ServerInfo/Guidebook/ServerRules/DefaultRules.xml, Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Blob.xml, Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Changelings.xml, Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Revolutionaries.xml, Resources/ServerInfo/_Shitmed/Guidebook/Medical/Surgery.xml
General fixes to the guidebook. Typos, errors, rewrites, stuff I found to be annoying that needed more explanation. Feel free to leave a comment here to point me to somewhere specific.
**Changelog**
:cl:
- tweak: Rewrote the Revolutionary Guidebook Entry
- tweak: Blob guidebook now has entry about the Blob carrier timer
- tweak: Surgery guidebook now mentions that certain surgeries require a surgical table
- tweak: Engineering SOP has been modified.
- tweak: Medical SOP has been modified.
- tweak: Changeling Guide now mentions the DNA Extraction sting, and it's intended use.
- add: Science now has an SOP entry.
=> Guidebook/SOP Fixes

Content.Server/Cargo/Components/StationCargoBountyDatabaseComponent.cs, Content.Server/Cargo/Systems/CargoSystem.Bounty.cs, Content.Shared/Cargo/CargoBountyData.cs, Resources/Prototypes/_Funkystation/Catalog/Bounties/bountyCategories.yml
Early changes for bounty stuff
Some early problems have been brought up, this will hopefully address these early problems
altered some bounty numbers and rewards, topicals have been disabled while I figure out an issue
skip timer reduced
can now only have one bounty category at a time
weighted to less items per bounty
**Changelog**
:cl: Gansu
- tweak: The bounty rewards for books, dice, board games, and laser guns have been increased.
- tweak: The amount of laser guns required for bounties has been reduced by 2.
- tweak: Basic medical topicals can no longer be generated as bounty items.
- tweak: Bounty skip timer has been reduced to 3 minutes, from 15 minutes.
- tweak: Each category can only have one bounty up at a time to reduce overlap.
=> Some bounty fixes/tweaks

Resources/ServerInfo/Guidebook/Engineering/Atmospherics.xml
Adding percentages each gas description, and standardizing the wording under each gas description so it's clear how to create each of them.
Many people in atmos are unsure of how to actually make the different gases, and have to open up the github to read how to actually make the gasses. This way there's an in-game way to know how to make Healium, BZ, and Nitrium.
Text only changes to the guidebook.
N/A, text only changes.
N/A
**Changelog**
Update: Atmospherics Guidebook now contains details on advanced gasses
=> Updating the atmospherics guide

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13NoEORG.xml
Rule 13 clarifications, shuttle bomb ruling did not exist in text before
Also clarify valid post-round antag actions
**Changelog**
=> Rule 13 shuttle bomb codification

Content.Server/_Viva/Borgs/LawSwapSystem.cs
one line fix (plus a few more for variable name consistency). was accidentally testing for a lawboundcomponent on the board when i wanted to check for a lawprovidercomponent.
i tested for the wrong component in the usedafterusing event
**Changelog**
- fix: fixed the feature i said i added so its actually added
=> small error in borg law swap, fixed so it works

Resources/Locale/en-US/_Goobstation/blob/blob.ftl
Did a large pass over all Blob localization, explaining the mechanics better in certain spots, and improving the overall written flavor of the antagonist.
**Changelog**
:cl:
- tweak: Updated and improved almost all in-game text relating to the Blob.
=> Overhaul Blob Localization

Resources/Maps/_Funkystation/bagel.yml, Resources/Maps/_Funkystation/marathon.yml
Removes  invalid configurators from the mapfile.
**Changelog**
=> Fixed map errors

Resources/Locale/en-US/_Funkystation/reagents/meta/medicine.ftl
=> fix aiuri desc

Content.Server/Store/Systems/StoreSystem.Listings.cs, Content.Server/Store/Systems/StoreSystem.cs, Resources/Prototypes/_White/Store/categories.yml
Re-added sales listings being applied anytime the uplink refreshes it's listings (fetches listings from prototype, I believe)
Sales didn't exist... Which was unintentional
StoreDiscountSystem is now a dependency of StoreSystem, and ApplyDiscounts is now run as part of RefreshAllListings.
I am cautious about if it will cause lag or any issues, as I see someone reverted the sales functionality at some point but I'm not sure why. I think it might just have been to prepare for the upstream merge but we should be cautious.
**Changelog**
:cl:
- fix: Fixed sales being broken and not existing
=> uplink sales fix

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC7PlayYourCharacter.xml, Resources/ServerInfo/Guidebook/ServerRules/Metashield.xml
Adds a Revolutionary mindshield, and changed Rule 7 to include "There are no main characters".
Security is often confused on when they can act on Revs due to lack of a proper mindshield. This PR fixes it.
Some players find the need to be the ONE to spice up the round with forced drama, be it IC or OOC.
**Changelog**
:cl: 
- add: A Revolutionary Mindshield has been added to the Metashield.
- tweak: Rule 7 now states "There are no main characters"
=> Rule changes.

Resources/Prototypes/_Funkystation/Entities/Objects/Specific/admeme.yml
Just some admeme items for us
Infinity crayon - 9999999 use crayon
Flash Master 5000 - 5000 use flash
admeme pie cannon - a speedy autocharging pie cannon
admeme spray bottle - ultracapacity spray full of water for those pesky felinids
the BIGGER nuclear option - RR's the majority of Bagel
idk do you hate fun?
No changelog, its admin shit
- [O] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [O] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
=> admeme items bundle

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC11SiliconPolicy.xml
Changed one word in Rule 11
Regarding #624 
Fixes #624 
Changes the wording in a rule, no technical code changed.
Picture of the error (Contradiction highlighted in different colors.)
Fixed Ruling
None
**Changelog**
:cl:
- fix: Fixed the wording on Rule 11 to not contradict itself in the same text.
=> Fixed RuleC11SiliconPolicy.xml

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC6Metagaming.xml, Resources/ServerInfo/Guidebook/ServerRules/Metashield.xml
More rule changes.
**Changelog**
:cl:
- tweak: Mindcontrol and Brainwashing has been clarified in Rule 6.
=> Rules changes pt2

Content.Server/Administration/ServerApi.cs, Content.Server/_Funkystation/Administration/ServerApi.Funkystation.cs
Allows whitelists through HTTP requests to the server admin API.
Discord bot usage!
Database shtuff
=> Whitelist Action HTTP API

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC12Antag.xml
Clarifies what Initial Infecteds and Zombies can and cant do.
**Changelog**
:cl: 
- tweak: Initial Infected and Zombie clarifications have been added to Rule 12.
=> Zombie R12 Changes

Resources/Prototypes/Entities/Objects/Fun/toys.yml
uhuh totaly
i added uhhh linge to foamblade
if you use the foamblade you get shot by john valid
man idk it's a yml file or something </3
no
idk
**Changelog**
:cl:
- tweak: foamblade now does stamina damage and can make flesh sound
=> yeah this probably works

Resources/Prototypes/Entities/Objects/Fun/toys.yml
Fixes toys.yaml to not have invalid spacing causing a client and server crash.
Client and server clashes without the fix
Small yaml edit. No changelog as the merge this comes from isnt live yet.
**Changelog**
=> Fixes foamblade crash

Resources/Maps/_Funkystation/bagel.yml, Resources/Prototypes/Entities/Objects/Fun/toys.yml
Expands atmos up a little bit to make room for the crystalizer and also adds bluespace gas vendor stations to atmos and around the station.
Brings Bagel up to date with current atmos content.
Adds the crysltalizer to north atmos and moves some storage canisters around to make room for the bluespace gas vendor sender in atmos, then also adds 7 bluespace gas vendor receivers around the station in publicly accessible areas for crew use. 
**Changelog**
:cl:
- add: Crystalizer and bluespace gas vendors added to Bagel
=> Bagel Atmos updates

Resources/Prototypes/_Impstation/Entities/Mobs/Species/thaven.yml, Resources/Prototypes/_Impstation/Species/Thavens/Moods/shared.yml
I HATE BUI KEYS 
**Changelog**
=> thaven hot fixes

Resources/ServerInfo/Guidebook/Service/Chef.xml
as in the title
also idunno if the butter description is enough? none of the other recipes list exact amounts, but then none of the other recipes differ from wizden...
fixes #684
because it wasn't described, like, at all
**Changelog**
idk does it really need a changelog entry?
=> Add cheese/chevre/tofu/butter instructions to the Chef guidebook page

Resources/Maps/_Harmony/barratry.yml, Resources/Maps/reach.yml
Adds Med biofab to Fland Reach and Barratry
the "guh" commits were because the button on the website to open this PR disapeared.
**Changelog**
:cl: 
- add: Medical Bio-fabricators have been added to the Medical bay in Fland, Reach, and Barratry.
=> Med biofab mapping

Resources/Locale/en-US/ghost/ghost-gui.ftl
Added a small reminder to the revival popup to clarify NLR
May or may not lower admin overhead depending on if people read
just touches a single ftl file, ghost-gui.ftl
=> Adds a small Rule 6 Reminder for revivals

Resources/Prototypes/Catalog/uplink_catalog.yml
Removed the sale component from the China Lake.
Allows nukies to still purchase the item, but prevents it from being spammed even on stealth ops for sales and creates a more balanced operative gameplan for crew.
A single line change, nothing major.
Unneeded
Shouldn't be any, the sale component is set from 1 -> 0, should still work as intended just not be purchaseable.
**Changelog**
=> Slightly tweaked nukies, the china lake now cannot go on sale

Resources/Locale/en-US/_Funkystation/station-laws/laws.ftl, Resources/Locale/en-US/station-laws/laws.ftl, Resources/Prototypes/_Funkystation/silicon-laws.yml, Resources/Prototypes/silicon-laws.yml
This PR adds 17 new lawsets which have been developed and playtested over 3 weeks. This content is intended to give more variety to silicons, adding many crew-aligned, neutral, and anti-crew lawsets
Lawsets included are: Tyrant, Lawyer, Skub, Opposite Day, Hippie, Teacher, Luddite, Cowboy, Free Will, Janitor, Paranoid, Capitalist, Poet, Clown, Revolution, Chaos, and Accountant
**Changelog**
:cl: Icepicked, oBerry
- add: Added 16 new lawsets to the Ion storm event.
- tweak: Ion storm weights have been altered.
=> Silicon law additions

Resources/Prototypes/_Shitmed/Entities/Structures/Machines/autodoc.yml
Increases the speed of the Autodoc.
So originally I tried to use the autodoc to replace a leg with a prosthetic - And it was painstaking. From the actual time investment in troubleshooting the operation system for the first time, to waiting for the machine to process, I was thinking "this is taking absurdly long". So I went to run some tests in a controlled environment, and the results seemed like something had to be wrong, but it was reproducible even on fresh repos.
These were my test results. The multitool, both at its current speed, and a slightly improved speed, were there for comparison without having to leave human error in inventory management as a factor to consider.
I don't play medical, and as such I have very limited surgery experience, even so, I was able to perform the test …
=> Autodoc Speed Increase

Resources/Locale/en-US/_Shitmed/autodoc.ftl
Changed to better fit with existing UI in the game.
The first time I used the autodoc, the UI was so out of place it felt like a mistake rather than intentional, and others have questioned the usage and asked why it was in Russian. It felt out of place and clashed with existing UI designs.
Changed entries in Autodoc.ftl
**Changelog**
:cl:
- remove: Removed Russian text in Autodoc UI
- tweak: Changed capitalisation in Autodoc UI
=> Changed Autodoc UI, removed russian and changed capitalisation

.github/workflows/build-map-renderer.yml, .github/workflows/labeler-pr.yml, .github/workflows/test-packaging.yml, .github/workflows/validate-rgas.yml, .github/workflows/validate_mapfiles.yml, .github/workflows/yaml-linter.yml, Tools/contribs_shared.ps1
=> Workflows Now Ignore Funkybot

Resources/Maps/_Harmony/barratry.yml
Cash money type beat
**Changelog**
=> Departmental Money Consoles for Fland and Barratry

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC11SiliconPolicy.xml
Re-writes Rule 11 to be incredibly explicit over what is and is not allowed for Silicons, as well as general definitions. They are VERY long but such is the price of Borg.
Nobody can agree on Silicon Laws, noone can even agree with what is actually written, it had to be done.
**Changelog**
:cl:
- tweak: Rule 11 (Silicon Rules) has been entirely re-written.
=> Rule 11: Silicon Rules Rewrite

Resources/Prototypes/Catalog/uplink_catalog.yml, Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
All ammo is sale-blacklisted, except histov ammo box.
Encryption keys sale-blacklisted.
Radio implant price 5 (from 2)
Changlog message partially carries from [my last PR](https://github.com/funky-station/funky-station/pull/489).
Ammo was made cheaper.
Low priced items block good sales.
Radio implant was cheaper than encryption keys(2 for 5). It wasn't updated since upstream merge.
yaml
**Changelog**
:cl:
- tweak: Mass-production cause syndicate ammo prices to dip. Expect no sales.
=> Remove Uplink Ammo Sale

Content.Server/Body/Components/LungComponent.cs, Content.Server/Body/Systems/RespiratorSystem.cs
My Bad. 
**Changelog**
:cl:
- fix: you need air to breathe again. Sorry.
=> breathing hotfix

Resources/Prototypes/Entities/Objects/Misc/implanters.yml
Smoke implant can now be removed. BSO's lifeline and pacifism still can not. No other known.
Fix issue https://github.com/funky-station/funky-station/issues/852
Comment says goob because it's a goob implant.
yaml
Comment says goob because it's a goob implant.
**Changelog**
=> Make smoke implant removable

Resources/Prototypes/Entities/Objects/Devices/Electronics/firelock.yml
Reverts funky-station/funky-station#839
Causes integration test error.
=> Revert "Reduce the selling price of firelock electronics"

Resources/Prototypes/Entities/Objects/Misc/implanters.yml
Continuation of https://github.com/funky-station/funky-station/pull/867
Added missing implants, so they can now be removed.
Disclaimer: CC implants are separate and are not be removable.
Since their admin items, I don't think they should.
That guy is whispering to himself. He might have a radio implant.
Yaml
**Changelog**
=> Deimplant fix 2: Radio & Fake Mindshield

Resources/Prototypes/Entities/Clothing/Belt/belts.yml, Resources/Prototypes/Entities/Structures/Machines/chem_master.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml, Resources/ServerInfo/_Goobstation/Guidebook/Medical/Medicalpatches.xml
[Add therapeutic patch.](https://github.com/Goob-Station/Goob-Station/pull/1086) Injects 0.5 per second, making it last as long as the large patch.
Removed patch reliance on chem master. Now you can insert reagents directly.
[Makeshift patch cost reduced](https://github.com/Goob-Station/Goob-Station/pull/1072)
[Patches fit in belts](https://github.com/Goob-Station/Goob-Station/pull/1246)
Updated guidebook entry based on [someone else's changes.](https://github.com/Goob-Station/Goob-Station/pull/1707)
Therapeutic patch prevents OD without the need to dilute the solution.
Chem master is no longer gatekeeping patches.
Makeshift patch should be easy to make. Maybe we should add base toxin to complement its poor sanitation.
yaml and port. I think it's all yaml.
**Changelog**
:cl:
- add: …
=> Medical patch tweaks

Resources/Locale/en-US/guidebook/chemistry/effects.ftl
it's annoying because "temporarily" could be 1 minute or half an hour
also sorry tay imma skip the template because this is smol
**Changelog**
=> Add duration to narcolepsy reset description

Content.Client/Cargo/UI/BountyEntry.xaml, Resources/Prototypes/_Funkystation/Catalog/Bounties/bountyCategories.yml
Tweaked some bounty stuff, kitchen bounties are generally better, worth more and require less. Atmos firesuit is gone and so is the salvage category
People complained about the worthwhileness of kitchen bounties due to quantities and costs, should be better now, especially for meat food and pancakes. Atmos firesuit proves to valuable to sell for a bounty without any replacement method. Salvagers generally didn't fulfil bounties and it feels like even at 50k a carp they still wouldn't do it so the entire category is gone since the carp/minnow was the main appeal of that category. Also donk pockets, always struggled with them and donuts are better flavour anyway
bounty console now uses a grid instead of a box container to ensure the buttons stay to size and uses a margin to ensure that …
=> Bounty tweaks and fixing the bounty console ui

Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
Admin glasses were added to the NTR locker.
Currently the NTR gets no access to the admin glasses, so this would provide them access to flash protection, as well as the ability to see Crew ID types at a glance.
Honestly I think it's something they should have had the whole time. Part of their job involves managing the actions of various roles, and they should be able to see that easily. Also they are archetypical admin agents, and I think deserve the admin glasses.
admin glasses ID added to the locker fill file
N/A
**Changelog**
:cl:
- add: Admin glasses added to NTR locker
=> Added admin glasses to NTR locker

Resources/Maps/_Funkystation/bagel.yml
Adds a water Vapor miner and randomized a bunch of maints goods using the new PR.
It was brought to my attention that Bagel lacked a water vapor miner. Also used the new PR to make maints more unique per round.
Mapping changes
**Changelog**
:cl:
- add: Added water vapor miner to Bagel
- tweak: Randomized Bagel maints
=> Bagel Water Vapor Miner

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC1DBAA.xml
We have had a issue regarding characters that a purposefully incendiary and rude, to the point where players will outright avoid them in game if they can. This rule change clarifies what can and cant be done as an "asshole" character, as well as gives admins clearer definitions for when they need to enforce it. 
**Changelog**
:cl: 
- tweak: Clarifications have been added to Rule 1 around playing certain types of characters.
=> Rule 1 Changes

Resources/Maps/_Funkystation/atlas.yml, Resources/Maps/_Funkystation/cluster.yml, Resources/Maps/_Funkystation/omega.yml, Resources/Maps/_Funkystation/saltern.yml, Resources/Maps/_Goobstation/cluster.yml
removes remaining self insert plushies
Parity
bro mapped in his own plushies
=> removes self insert plushies v2

Resources/Maps/Shuttles/mining.yml
Removed the smuggler's satchel
tay told me to
**Changelog**
Removed the smuggler's satchel
=> removed the smuggler satchel from the salvage shuttle

Content.Server/Cargo/Systems/CargoSystem.Bounty.cs, Content.Shared/Cargo/Prototypes/CargoBountyPrototype.cs
Added the weight field to bounty entries to allow for weightings of entries to make them more or less likely to be bountied.
Added the AmountStep field to bounty entries to allow for different step sizes, mostly for liquids but other stuff might get a use.
No cl currently as it's technical but if it's wanted it can be uncommented. Otherwise it'll be mentioned when I make changes after this is merged.
Currently all bounties have to be roughly balanced as they can all happen so they all have to be equally viable, weightings allow for weirder bounties since you can make them less likely.
Step sizes are so that liquid bounties can have differing amounts in a way that won't make those involved want to kill me
New data fields for entries, AmountStep and Weight. 
New method for selecting an …
=> Added bounty weighting and entry step sizes

Resources/Locale/en-US/guidebook/guides.ftl, Resources/Prototypes/Guidebook/rules.yml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC6Metagaming.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC8Names.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC9UseProperEscalation.xml, Resources/ServerInfo/Guidebook/ServerRules/Metashield.xml, Resources/ServerInfo/Guidebook/ServerRules/NamingScheme.xml
Changes multiple rules. 
Heretics, Wizards, and Cultists have been added to the Metahshield under "Magic Users". They are shielded in a way to encourage charging people off crimes they commit rather then their (meta) antag status. The shield lifts once the antag gets going or if they go loud. Which reveals their goals.
Added naming schemes to the Rulebook, to clarify inconsistency in rulings.
Atmos bombs are no longer allowed without prior admin approval, to stop issues of atmos techs doing nothing all round then blowing up a department due to a minor antagonist presence.
**Changelog**
:cl:
- tweak: The Metashield, Naming Rules, and Escalation Rules have been tweaked.
=> 1984 (Rule changes)

Resources/Prototypes/SoundCollections/harpy.yml, Resources/Prototypes/Voice/speech_emotes.yml, Resources/Prototypes/_DV/Voice/speech_emote_sounds.yml
I made it so the weh emote is only accessible through the wheel for lizards, and added the reptilian hiss to the harpy pool of sounds. I won't be including a changelog, as this doesn't need it
oopsie
yml type shit
=> Fixing a small oversight from my lizard noises pr

Content.Server/Cargo/Systems/CargoSystem.Funds.cs, Content.Server/Cargo/Systems/CargoSystem.cs
I changed how the system handled money when it deals with withdraws and transfers from department accounts.
This makes transferring money, either cash in hand or through the transfer option in the request computers work properly. This additionally stops an easy abuse where someone could cause other departments to have negative funds.
I've added a new function to deal with withdraws, which calls the normal function, just with the distribution removed.
I've also added a new function to deal with deposits, in the same fashion as the withdraws.
**Changelog**
:cl:
- fix: Cash withdrawals no longer steal from other departments.
- fix: Inter-department money transfers are no longer spread through all departments.
=> Money transfer fixes for withdrawing cash or transferring between departments.

Content.Server/Spawners/EntitySystems/ConditionalSpawnerSystem.cs, Content.Shared/Xenoarchaeology/Artifact/Components/XenoArtifactComponent.cs, Content.Shared/Xenoarchaeology/Artifact/Components/XenoArtifactNodeComponent.cs, Content.Shared/Xenoarchaeology/Artifact/SharedXenoArtifactSystem.Node.cs, Content.Shared/Xenoarchaeology/Artifact/SharedXenoArtifactSystem.Unlock.cs, Content.Shared/Xenoarchaeology/Artifact/SharedXenoArtifactSystem.XAE.cs, Content.Shared/Xenoarchaeology/Artifact/SharedXenoArtifactSystem.cs, Resources/Maps/Shuttles/ShuttleEvent/incorporation.yml, Resources/Maps/_Funkystation/divide.yml, Resources/Maps/_Funkystation/elkridge.yml, Resources/Maps/_Funkystation/roid_outpost.yml, Resources/Maps/elkridge.yml, Resources/Prototypes/Entities/Markers/Spawners/Random/artifacts.yml, Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_xenoartifacts.yml, Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/structure_xenoartifacts.yml, Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/xenoartifacts.yml, Resources/Prototypes/Recipes/Crafting/Graphs/artifact.yml, Resources/Prototypes/XenoArch/effects.yml, Resources/ServerInfo/Guidebook/Science/Xenoarchaeology.xml, Resources/migration.yml
Cherrypicked this: space-wizards/space-station-14/pull/36604, this: space-wizards/space-station-14/pull/36598, and this: space-wizards/space-station-14/pull/36745
Fixing artifact is good :+1:
See relevant PRs
**Changelog**
:cl: EmoGarbage404
- add: When an artifact's node is unlocked, the effect will now also occur. Effects can still be triggered manually through interaction.
- tweak: Artifacts will now have more nodes on average.
- tweak: Higher-class artifact nodes now grant significantly more points.
- tweak: Sentient artifacts can once again activate themselves.
- tweak: Increased sentient artifact self activation cooldown.
=> Cherrypicking three artifact prs from Wizden

Content.Server/GameTicking/Rules/ZombieRuleSystem.cs, Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs, Content.Server/_Goobstation/Blob/BlobCoreSystem.cs, Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs, Resources/Locale/en-US/_Funkystation/shuttle/fail_reasons.ftl, Resources/Locale/en-US/_Goobstation/blob/blob.ftl
This reverts commit 46dcdf4a677df78e9f995e8474dc5cc8669f5843.
broken
=> Revert "Shuttle loop fixes (#936)"

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC10SecandCommand.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13NoEORG.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC2English.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC3Age.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC5ERP.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC7PlayYourCharacter.xml
Clarifies some rules, and adds to others.
**Changelog**
:cl:
- tweak: Core Rules 2, 3, 5, 7, 10, and 13 have been tweaked.
=> Rule Changes pt 1985

Resources/Prototypes/Entities/Clothing/Shoes/base_clothingshoes.yml
Title
Missed it in my last PR
https://github.com/user-attachments/assets/beb69893-f8b0-449a-a712-a77efe47e832
:cl: Miiish
- fix: Added random variation to jackboot sounds as intended.
=> Adds a small bit of variation to boot sound effects

Resources/Prototypes/_Funkystation/Catalog/Cargo/cargo_atmospherics.yml
While the HFR is in game it is currently unobtainable so this adds it to the cargo order console under atmospherics.
HFR chambers are on most maps now so its time to make it orderable. Its put at a very large price that will probably need adjusted after some testing, its befitting of a late game item to cost such a large amount considering how much money atmos is currently able to make during a shift.
Adds a new file to the cargo catalogue that holds the cargo order selection. 
**Changelog**
:cl:
- add: HFR added to cargo order console
=> Adds HFR to cargo order console

Resources/Prototypes/Catalog/uplink_catalog.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
Enabled new modes for stealth op nukies. Incredibly minor tweak to new dsword reflect chance to make it worth it but not busted.
Allows Nukies to use the biofabricator for evil like they always should have.
Minor YAML changes.
None
**Changelog**
:cl: UristMcWiki
- add: Allowed carp to be purchase from Nukie shops since they cannot be made at all normally.
- tweak: Slightly buffed the reflect chance on the new Dsword but kept it manageable.
=> Nukie and DSword Minor Rework

Resources/Prototypes/Body/Organs/Animal/animal.yml
**Changelog**
:cl:
- fix: fixed some species only being able to metabolize 2 chems at a time, now they can metabolize three!
=> fix some species having a lower metab limit

Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Mech/Weapons/Gun/combat.yml
Mech gun fixes
Mech gun fixes
Bug fixes
None
**Changelog**
:cl: UristMcWiki
- fix: Certain mech guns had broken energy costs. Fixed those values and slightly buffed others.
=> Mech Changes But For Real

Resources/Prototypes/Entities/Objects/Weapons/Bombs/firebomb.yml, Resources/Prototypes/Entities/Objects/Weapons/Bombs/pipebomb.yml, Resources/Prototypes/Entities/Objects/Weapons/Bombs/plastic.yml
I made the pipe bomb and firebomb major contraband, as well as their partially finished versions.
I also made the seismic charge cargo-only gear.
It seems like an oversite that IEDs are not marked as contraband, and I feel like they should probably be illegal.
Similarly with seismic charges. Having non-salvage with them should be 'sus' to say the least.
Low balance concerns. Just fixes a hole in the contra system.
added parentage to the respective contra class for each of the items, in their yaml
n/a
**Changelog**
:cl:
- tweak: Made pipe bombs, fire bombs, and seismic charges illegal for the general crew. Seismic charges are legal for cargo.
=> IEDs made illegal to crew. Seismic charges restricted to cargo.

Content.Server/Telephone/TelephoneSystem.cs, Content.Shared/Eye/Blinding/Systems/EyeClosingSystem.cs, Content.Shared/Telephone/TelephoneComponent.cs, Resources/Prototypes/Entities/Mobs/Player/silicon.yml
* Cleanup
[Cleanup: Remove ``TelephoneComponent.RequiresPower`` (#38823)](https://github.com/space-wizards/space-station-14/pull/38823)
[Tiny Tiny Cleanup of the EyeClosingSystem. (#38734)](https://github.com/space-wizards/space-station-14/pull/38734)
Looked helpful.
Cherry-pick
**Changelog**
=> Wizden Cleanups 1

Resources/Prototypes/Maps/fland.yml
Fland has a Magi now, also I changed the sentries in the new AI core.
**Changelog**
=> fland magi and AI sentry fix

Content.Server/Explosion/Components/SpawnOnTriggerComponent.cs, Content.Server/Explosion/Components/TriggerOnCollideComponent.cs, Content.Server/Explosion/Components/TriggerOnUseComponent.cs, Content.Server/Explosion/EntitySystems/TriggerSystem.cs, Content.Server/Polymorph/Systems/PolymorphSystem.Trigger.cs, Content.Server/Polymorph/Systems/PolymorphSystem.cs, Resources/Prototypes/Polymorphs/polymorph.yml
(cherry picked from commit 175f5e6c2fbefc4d810fe9b6c04e22daf9798260)
cherry picked a broken commit, not really changes? it adds some polymorph effects, and makes the ones we had not broken any longer
During the last upstream merge the deletion portion of this commit was applied, but none of the addition or modification portions were applied. Because of this, all polymorph trigger effects were broken.
its a cherry pick. But specifically, the Content.Server.PolymorphSystem.Collide.cs file was deleted by the upstream merge, but the Content.Server.PolymorphSystem.Trigger.cs file was not ADDED. I don't even know how this could happen, unless someone explicitly deleted it, idk. All of the upstream merge PR's get atomized, so like, not really a good way to tell why this happened.
uhhhh …
=> Cherry pick commit that somehow got dropped during an upstream merge and broke polymorphing

Resources/Maps/_Funkystation/core.yml
read the technical details I guess? just a bunch of small stuff that would have been needed to be fixed roundstart, but wouldn't have affected gameplay much.
core. the map. the movie.
I broke the old core map by fixing it. It was really outdated since it got merged more than 2 hours ago.
**Changelog**
:cl: JoulesBerg
MAPS:
- fix: Core
- remove: Core bugs
- add: some lightbulbs to core
=> Core build12

Content.Client/Physics/Controllers/MoverController.cs, Content.Server/Physics/Controllers/MoverController.cs, Content.Shared/Movement/Systems/SharedMoverController.Input.cs, Content.Shared/Movement/Systems/SharedMoverController.cs
This hand-picks some of the changes from ff18f18c72c83973c0ba2e268dff1a43fe710678 on upstream with some modifications to (hopefully) fix the entirety of the bug since upstream still has some issues with it.
https://github.com/user-attachments/assets/7dbc683d-39ab-42d6-b295-5f46518f48f9
(Chrome froze 6 times uploading this video.)
**Changelog**
:cl:
- fix: Fixed mech movement breaking when rotating camera or grid transferring to a shuttle/station.
=> Fix mech grid rotation issues

Content.Server/Administration/Systems/AdminVerbSystem.Smites.cs
Some admin smites were using names from other admin smites so it looked like you were admin abusing the hell out of people when all you did was turn them into bread or something. Copy paste error moment.
**Changelog**
=> Fix admin smites just straight up lying in logs

Resources/Maps/_Funkystation/omega.yml
Fixes and appropriate changes requested by either admins or caught by members of Funky Station for Omega Station Map. Check changelog for full list of all adjustments.
HFR room won't fit nicely, also didn't want to provide the flatpacks even if they weren't all there anyways. Material silo is being removed in preparations for department silos by request of the admins, everything else is general needed fixes to play the game more smoothly
Just mapping additions/removals
**Changelog**
:cl: salpphie
- add: Add Psychologist camera, added AI turrets to AI room, added lv for unpowered scrubber and air vent in Courtroom
- remove: Removed Material silo, removed extra mining suit in the QM's locker, removed salvager supplies crate in salvage, removed HFR flatpackers and HFR room
- tweak: Connected …
=> Omega Map Adjustments [7/20/25]

Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Hardlight bow is gone from uplink
I'm working on a rework just let me finish that 
like 4 lines of comment tagging
**Changelog**
:cl: UristMcWiki
- remove: Removed the Hardlight Bow for a test period. Cannot be bought. Will return with a reworked concept later.
=> Actually Remove The Bow

Content.Client/Physics/Controllers/MoverController.cs, Content.Server/Physics/Controllers/MoverController.cs, Content.Shared/Movement/Systems/SharedMoverController.Input.cs, Content.Shared/Movement/Systems/SharedMoverController.cs
This reverts commit 75bc3416a388f91f0640ee6d260d8d478686e380.
**Changelog**
=> Revert "Fix mech grid rotation issues (#1136)"

Resources/Prototypes/Catalog/uplink_catalog.yml
Removed the Elite suit.
Get the suit out of here
YAML
One comment out
**Changelog**
:cl:
- remove: Removed the Elite Hardsuit.
=> Remove Elitesuit

Resources/Prototypes/_Funkystation/Entities/Weapons/annabelle.yml
Changes Annabelle from minor contra to Chaplain only contra as per #1224
Why was it not
Replaces the parent BaseMinorContraband with BaseChaplainContraband 
**Changelog**
:cl: gaesnek
- fix: Chaplain is now actually allowed to have their gun.
=> Annabelle Contraband Fix

Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
Makes the Gorlex Hypospray actually syndicate contra as per #1216 
Why was it not.
Adds BaseSyndicateContraband to the hypospray's parents.
**Changelog**
:cl: gaesnek
- fix: Gorlex Hypospray is now actually syndicate contraband.
=> Gorlex Hypo Contra Fix

Resources/Prototypes/Maps/Pools/default.yml
Added up to date maps to the default pool and nixed the maintainerless ones, as an interim so we can get playtesting feedback and more map variety while server-specific map pools are being sorted out. 
I hate Origin and Reach
yaml
**Changelog**
:cl:
- add: new interim map rotation. rejoice for Reach is finally dead.
=> Interim map pool

Content.Server/Atmos/EntitySystems/FlammableSystem.cs, Content.Shared/Atmos/Components/OnFireComponent.cs
Ports over [#3374](https://github.com/Goob-Station/Goob-Station/pull/3374) from Goob. Improves performance. 
**Changelog**
:cl:
- fix: Dramatically improved performance of the flammable system.
=> flammable performance improvements (Port of Goob's port of EE #2462)

Resources/Maps/_Funkystation/glacier.yml
Glacier:
- Added missing pets
- Removed material silo
**Changelog**
:cl:
- add: Missing pets to Glacier
- remove: Material silo from Glacier
=> Glacier changes and fixes for the week of Aug. 1

Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_snacks.yml, Resources/Prototypes/Entities/Markers/Spawners/Random/trash.yml, Resources/Prototypes/Entities/Markers/Spawners/Random/vending.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml, Resources/Prototypes/_Funkystation/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/_Funkystation/Catalog/Fills/Crates/vending.yml, Resources/Prototypes/_Funkystation/Entities/Objects/Specific/Service/vending_machine_restock.yml, Resources/Prototypes/_Goobstation/Catalog/VendingMachines/Inventories/solsnack.yml, Resources/Prototypes/_Goobstation/Catalog/VendingMachines/Inventories/weebvend.yml, Resources/Prototypes/_Goobstation/Entities/Objects/Consumable/Food/snacks.yml
Adds three vending machines that currently mostly sit unused, alongside their contents into the apropriate random spawnsers 
These are the Nippon-tan, SweatMAX and Mars Mart vendors
all of the trash items from them have also been added to the random trash spawner, and the snack items themseleves into the random snack spawner, for the sake of completeness
alongside this, it has also been changed so that trash items on being recycled produce plastic instead of steel
These are three vending machines with their own unique stock of items that are currently not used outside of being specifically mapped in, likely because they were just fogotten about and never added to the spawns
With them being added the number of possible snack items that can exist on station is now significantly increased, …
=> VendingMachineAdditions

Resources/Prototypes/Entities/Clothing/Neck/base_clothingneck.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/softsuits.yml, Resources/Prototypes/Entities/Clothing/Shoes/base_clothingshoes.yml, Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
Scarf actually insulates from cold.
All uniforms and shoes now have minimal cold resistance.
This marginally affects space's lethality without EVA.
Emergency EVA nerfed slightly to compensate.
You're telling me scarfs didn't insulate before?
Basic clothes should be better than nothing. 
Emergency EVA keep you from dieing to cold only something like 20 seconds less(5 min total from 38C body temp until crit) when normally clothed, and about half the time with only EVA. Exact values shouldn't matter since it only affects space walks, not even spaced rooms. Just wearing winter boots already negated freezing.
Yaml
No visual changes.
**Changelog**
:cl:
- fix: Scarfs are warm now.
=> Warmer Clothes

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC12Antag.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC13NoEORG.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC6Metagaming.xml, Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC8Names.xml
Changes and tweaks rules 6, 12, and 13. Also does some spell checks.
The in-game definition of EORG has been updated for clarity.
The shuttle bombing rule has been moved from rule 13 to rule 12.
Definitions around spontaneous unconsciousness has been added to rule 6.
**Changelog**
:cl: Icepick, Frostwight
- tweak: Rules 6, 12, and 13 have been tweaked.
=> Rule tweaks.

Content.Server/_Funkystation/Atmos/Effects/TemperatureAdjustingComponent.cs, Content.Server/_Funkystation/Atmos/Effects/TemperatureAdjustingSystem.cs
A component and system that adjusts the temperature of the air in the surrounding tile. 
Mostly just the fire anomaly code without the anomaly bit.
None
**Changelog**
:cl:
- add: Added temperature adjusting component
=> Add temperature adjusting component

Resources/Prototypes/GameRules/meteorswarms.yml, Resources/Prototypes/_DV/CosmicCult/game_presets.yml, Resources/Prototypes/_Goobstation/game_presets.yml, Resources/Prototypes/game_presets.yml
Reenables meteors with a *far longer scheduler*
30 mins minimum into the round, 25 minutes minimum between events.
cool, staff chat discussion
**Changelog**
:cl: Miiish
- tweak: Reenabled meteors.
=> Reenables meteors

Resources/Maps/_Funkystation/omega.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/clothing.yml
Added Psychologist Jumpsuit/Jumpskirt, Straight Jacket, and Hi-Vis vests to the Uniform Printer
Psychologist clothes were not in the printer, just the medi drobe. Straight Jacket isn't available anywhere else and can be useful for highly dangerous patients/criminals who are self harming or difficult to keep under control. And Hi-Vis is a cargo bounty but it is extremely difficult or impossible to get them in the quantities needed.
**Changelog**
:cl: salpphie
- add: straight jacket, hi-vis vests, and psychologist jumpsuit/skirt to the uniform printer
=> Uniform Printer Additions  (3 new ones)

Resources/Maps/_Funkystation/omega.yml
> Added: tropico spawn, polly spawn
> Removed: two windows in Lawyer/IAA room
> Tweaked: salvage dock
Tropico and Polly are important pets, salvage dock had a hard time docking without getting in the way of cargo. This is a temp fix while I look at reworking it more. Lawyer and IAA were annoyed with the directional windows and so was I.
**Changelog**
:cl: salpphie
- add: tropico spawn, polly spawn
- remove: two windows in Lawyer/IAA room
- tweak: salvage dock
=> Omega Pet Addition and Minor Update

Resources/Prototypes/Catalog/Fills/Crates/vending.yml, Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml
Replaces all (player-facing) instances of NanoMedPlus with NanoMed Plus
This really, really seems like a typo or an unfathomably rare way of referring to it
=> Replaces all (player-facing) instances of NanoMedPlus with NanoMed Plus

Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Medical/medical_patch.yml, Resources/ServerInfo/_Goobstation/Guidebook/Medical/Medicalpatches.xml
Fixed guidebook entry.
Fixed refill-ability of makeshift patch. (oops, I broke it)
Halved therapeutic patch cost. Now it's the same as base patch.
I feel patches should be overall cheaper, as they aren't the medicine, but rather the delivery method. For the time being, I balanced the cost compared to the rest.
yml
**Changelog**
=> medical patch tweaks 2

Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml
made the light on the sec hardsuit blue instead of yellow to match the resprite
**Changelog**
=> bluesec (real)

Resources/ServerInfo/Guidebook/ServerRules/CoreRules/RuleC7PlayYourCharacter.xml
Rule 7 Change.
Clarifications for how crew should act during major threats, per a complaint.
**Changelog**
:cl:
- tweak: Rule 7 has been tweaked.
=> Rule 7 tweak

Resources/Prototypes/Catalog/Fills/Lockers/service.yml
It just adds the plant analyzer to the botanist locker's loot, this is my first PR here as well and my first PR to something in a while in general, if I did something wrong do let me know and I'll fix it right away.
This iteration of the plant analyzer is woefully underpowered compared to some of its other versions accross servers and games, it made sense to have it be a research on frontier to engage players in interacting with science vessels, but it doesn't make sense here since it is just traditional spessmans. It offers less value than something like a health analyzer does for a doctor for example and this item has been a staple of the botanist loadout for the last decade or so in 13, without it the job is an infuriating mess of RNG down to its own essential features.
For balance it …
=> Spawns the plant analyzer on botanist lockers roundstart.

Resources/Locale/en-US/_Funkystation/records/medical_info.ftl, Resources/Prototypes/_Funkystation/Records/prescriptions.yml
Adds more flavor to the records.
Just adds an extra option to medical records.
**Changelog**
=> Adds antipsychotics prescription

Resources/Prototypes/Entities/Mobs/Player/observer.yml
During a round, a fellow spectator suggested that this issue might've been caused by some code in the nightvision port. The idea of this scared me deeply. Luckily, after a little digging, it turned out to be a 1 line yaml fix that upstream already implemented in https://github.com/space-wizards/space-station-14/pull/37335 .
Bugfix
netsync: false in the observer yaml
**Changelog**
:cl:
- fix: Fixed observer light not working
=> Fixes observer light

Content.Shared/CartridgeLoader/CartridgeLoaderComponent.cs
+2 cartridge app limit
With the addition of new apps, it is increasingly difficult for certain roles to have all the nesseary apps.
**Changelog**
:cl:
- tweak: Upped app limit from 8 to 10.
=> More app space

Content.Server/Radio/EntitySystems/RadioSystem.cs
Common channel nerf only affected entities with headsets, which excluded IPCs
Changed the check from headsets to an absence of a law component or an intercom component
**Changelog**
=> Fixing IPCs being able to talk on common when nobody else can

Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs, Resources/Locale/en-US/_Impstation/thavens/shared.ftl, Resources/Locale/en-US/game-ticking/game-presets/preset-revolutionary.ftl, Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/Changeling/Actions/changeling.yml, Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml, Resources/ServerInfo/_Goobstation/Guidebook/Antagonist/Changelings.xml
Makes some Changeling / Rev mechanics more clear, also fixes a typo in a Thaven mood for making a feast (not a feasEat)
Example of Rev message (the light blue is a personal-highlight and not present in-message)
**Changelog**
:cl:
- tweak: Head Rev briefing now explicitly mentions your uplink code, and that you get the Flash from the uplink.
- tweak: Changeling's DNA Sting action description + Guidebook entry now explicitly specify the target must be critical or dead past the first use.
- tweak: Updated the Revolutionaries guidebook a bit.
- fix: Fixed Head Rev briefing displaying twice.
=> Text Changes for Revs, Changelings, Thaven Mood

Resources/Prototypes/Catalog/Fills/Lockers/medical.yml, Resources/ServerInfo/Funkystation/Guidebook/Medical/MedicalStandardOperatingProcedure.xml
Handheld Crew Monitor now spawns in Paramedic lockers as well, you no longer need to share the CMO's single one between 2 Paramedics.
No more Greencomms increases demand on suit sensor vigilance, sitting in front of the Computer as your job 24/7 sucks for interaction. Also we wanted to do this anyway like months ago, just the demand is more existant now.
**Changelog**
:cl:
- add: Handheld Crew Monitors are now roundstart for Paramedics, available to them in their lockers.
=> Handheld CM is now available in para lockers

Resources/Locale/en-US/reagents/foreverweed.ftl, Resources/Locale/en-US/reagents/meta/narcotics.ftl, Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/misc.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml, Resources/Prototypes/Reagents/medicine.yml, Resources/Prototypes/Reagents/narcotics.yml, Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
forever weed funny
- [ x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x ] I have added media to this PR or it does not require an ingame showcase.
:cl: LucasTheDrgn
- add: Added forever weed brownie
=> forever weed brownie

Resources/Prototypes/Loadouts/Jobs/Science/scientist.yml, Resources/Prototypes/Loadouts/loadout_groups.yml
Added the white hardhat to scientist loadouts.
I was inspired by having played some maps on other forks where they were mapped in the department, and I think they look really great and wish they were obtainable normally in the game when playing science.
Changes 2 yml files, adds an ID for ScientistHardhatWhite and then uses that in the scientist head loadout group.
**Changelog**
:cl: Max_Power
- add: Added the white hard hat to science loadouts!
=> Add white hardhat to research Loadouts

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/medical.yml, Resources/Prototypes/Recipes/Lathes/misc.yml
i made it possible to lathe pens, stethoscopes, and tank harnesses
you should be able to make a pen and other things at lathes; might affect the singular cargo bounty that asks for pens but proxima says its getting reworked lol
i added recipes for the vox tank harness, stethoscope, and basic pen and changed the master lathe file's static recipes to include those recipes i made by default
I didn't actually test if this even works ingame because I forgot how to update and maintain my test server
It's probably fine though, I can't see how it doesn't work
**Changelog**
:cl:
- add: Added the ability to lathe pens and vox tank harnesses at autolathes, as well as stethoscopes at medical techfabs
=> I want to lathe pens it makes sense

Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Makes AI an ion storm target, making Station AI gameplay more interesting as the round progresses
Add more content for AI gameplay, the ion storm event is expected to be considerably rare in the round.
**Changelog**
:cl: EmillyCoelho
- add: Station AI are now an Ion Storm target
=> Makes AI an ion storm target

Resources/Prototypes/Recipes/Lathes/sheet.yml
waow
**Changelog**
:cl:
- fix: Fixed Ore Processor steel recipe still using coal when it was supposed to have been changed to not.
=> Hotfix Ore Processor

Resources/Prototypes/Body/Organs/arachnid.yml, Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml, Resources/Prototypes/Reagents/toxins.yml
Arachnid organs now use the Arachnid metabolizer type. This means that drinks and chemicals that target Arachnids specifically function properly again. This is specifically used by two chemicals already, such as certain cryogenics chemicals and Copper.
There are several chemicals that have different functionality based on if the metabolizing organ is an Arachnid organ. Since Arachnid organs have the Animal metabolizer type, they metabolize like an Animal organ, not an Arachnid organ.
Edited the arachnid organs (Prototypes/Body/Organs/arachnid.yml) to use the Arachnid metabolizer types.
Edited toxins.yml (Prototypes/Reagents/toxins.yml) to properly account for having an Arachnid organ, just like how the Vox metabolizer type does.
None.
Certain reagents which are supposed to target Animals …
=> Arachnids Now Use Their Own Metabolizer Type

Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_percussion.yml
Microphones work in your offhand.
cuz.
yaml shit
- [X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
:cl: ATDoop
- tweak: Microphones now work in your offhand.
=> make microphones work in your offhand 

Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
- [X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
=> for rplamsa.yml , changed WallLayer to GlassLayer , fixing laser effects so they pass through instead of colliding

Content.Client/IconSmoothing/IconSmoothComponent.cs, Content.Client/IconSmoothing/IconSmoothSystem.cs, Resources/Prototypes/Entities/Structures/Walls/walls.yml, Resources/Prototypes/Entities/Tiles/chasm.yml, Resources/Prototypes/Entities/Tiles/lava.yml
(cherry picked from commit 63ecf4241a4e6f8e7070220941d6bde9e7589e73)
https://github.com/space-wizards/space-station-14/pull/35790
LICENSE: MIT
Ported additional keys for smoothing from https://github.com/space-wizards/space-station-14/pull/35790
Looks nice, only effects ingame puddles, chasms, & lava
Just adds additional functionality to IconSmoothComponent/System.cs, no breaking changes encountered cherrypicking this PR
**Changelog**
:cl: TheShuEd
- tweak: Chasms, puddles, and lava now visually stick to walls
=> [PORT] IconSmooth additional smoothing keys (spacewizards#35790)

Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
Adds one of the base mime and clown masks to the autodrobe.
The other Mime and clown masks can already be easily obtained at the autodrobe. Why exclude the classics?
Just added two entries to the upstream theatre vendor list, one for the base mime mask and one for the base clown mask.
**Changelog**
:cl:
- tweak: Added the base mime and clown masks to the autodrobe.
=> Add base Mime and Clown Masks to the Autodrobe

Resources/Prototypes/Entities/Clothing/Ears/headsets.yml, Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
This is an experiment to see how well lawyers would fare without security comms. As a non-combatant, they don't need to hear about current threats on the station, and should instead be called by the warden or magistrate when needed or when a prisoner requests a trial. We have PDA messages for these people to communicate with lawyers, so security comms aren't needed for this purpose.
See the discussion over at https://github.com/funky-station/funky-station/pull/1596#issuecomment-3342001102, I hope to continue the conversation here.
Lawyers now start with security headsets on roundstart or latejoin. In addition, security headsets are considered contraband for lawyers now.
**Changelog**
:cl:
- add: Lawyers now start with service headsets.
- remove: Lawyers no longer start with security …
=> Lawyers now have Service Comms

Resources/Maps/_Funkystation/amber.yml, Resources/Maps/_Funkystation/box.yml, Resources/Prototypes/Maps/Pools/default.yml
Updated Box and Amber to fix reported problems as well as adding in new features that were missing. Removed Fland and Pioneer (Barratry) from rotation.
Map updates help keep the maps relevant with new features. Removing Fland and Pioneer from the rotation helps keep the quality of the maps up since those two are currently orphaned maps. Doing this we can bring in new maps that are being maintained to help keep the pool up.
**Changelog**
:cl:
- add: Material Silos to Box
- add: Material Silos to Amber
- add: Science Communications console to Amber
- tweak: Adjusted decals on Box to make areas blend in
- tweak: Adjusted decals on Amber to make areas blend in
- remove: Removed Fland and Barratry from rotation.
=> The catchup (Finished first set of school work)

Content.Server/Prayer/PrayerSystem.cs, Content.Shared/Prayer/PrayableComponent.cs, Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_misc.yml
Atheists can now use the Red Phone
Fixes #1566
Atheists probably should believe in Phones
Added a new Field to PrayableComponent "UsableByAtheists".
In PrayerSystem I added new logic to check for that.
**Changelog**
:cl:
- fix: Red Phone is now usable by atheists
=> fix: Prayable Phones are now usable by atheists

Content.Client/_DV/CustomObjectiveSummary/CustomObjectiveSummaryWindow.xaml.cs
Upgraded pinktext character limit from 256 to 1024.
256 is not enough. I want to write in my little diary.
I changed a number to make it bigger.
**Changelog**
=> Bigger Pinktext (I fucking hate gitbash)

Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml, Resources/Prototypes/_Goobstation/Loadouts/loadout_groups.yml
Fixes Cargo Technicians spawning with two PDAs
Because I'm stupid and didn't do it properly last time
Removes PDA from jobs/cargo_technician.yml
**Changelog**
:cl: AraiMaia
- fix: Cargo Techs no longer spawn with two PDAs
=> Cargo Technician PDA fix
