- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
Adds a damage modifier to cold, so spacing for felinids is more dangerous. Also adds a thirst modifier, making felinids thirsty.
Felinids are essentially big hairless cats. They cannot regulate body temperature. They are also the exact same to humans, except just a smaller hitbox. This PR aims to balance felinids with more thirst management and extra vectors for something to go wrong (i.e, spacing is a bigger deal now).
YAML lol
**Changelog**
:cl:
- tweak: Felinids now take more cold damage
- tweak: Felinids are thirsty
> Felinid balances pt.1

- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
Felinids are now human-size and can no longer be put into duffelbags.
The scaling messes with the art & makes felinids just better mechanically than humans with no real downside beyond the cat ears. 
Removed the code that made felinids a protoitem & removed their scaling.
**Changelog**
:cl:
- tweak: Felinids are human size & can no longer be put in duffelbags.
> Felinid size increase & they no longer fit into duffelbags.

- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
-Increased heretic and thief rates
-lowered player requirements for lings, heretics, and zombies
Low pop doesn't get heretics and lings at all
Just changed a couple of the yml values and changed numbers for minplayers and weights
**Changelog**
:cl:
- tweak: Increased heretic and thief rates
- tweak: Lowered player requirements for zombies, heretics and lings
> Lower player requirements for antags

- Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
Reduced number of max changelings and heretics, helps with balance.
Too many heretics can spawn at once in a round. Same with changelings
Changed some numbers
**Changelog**
:cl:
- tweak: Tweaked numbers on max heretics and changelings
> lowered max numbers of changelings and heretics

- Content.Server/Atmos/Reactions/BZFormationReaction.cs
- Content.Shared/Atmos/Atmospherics.cs
Changes BZ formation mechanics to be more in line with original /tg/ code
BZ formation was unwieldy and was not acting as intended.
BZ can now be formed with fewer mols. When plasma levels are significantly higher than n2o levels, the mixture will decompose into oxygen and nitrogen. BZ will not be formed at temperatures that can ignite plasma or tritium. 
None
**Changelog**
:cl:
- tweak: BZ Formation mechanics
> update bz formation to be more in line with /tg/ mechanics

- Content.Server/_Goobstation/Heretic/Ritual/CustomBehavior.Sacrifice.cs
Just changed the loop so it actually works like its meant to, and also will now refuse to send you into solars or off station.
It's just better teleporting so you don't get teleported into solars and die a horrible death.
Added it so it moves the player when testing to see if the spot works. This isn't visible through normal gameplay since its so fast so there's no reason to not do this. This allows me to check if the player has atmos and if they're on a grid.
**Changelog**
:cl:
- tweak: Getting sacrificed places you in better spots
> Better Sacrifice Teleporting

- Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
Added a check to see if a player has a Heretic or Changeling component.
Heretics and Changelings able to turn into revolutionaries causes confusion with both groups of players. Heretics have separate goals that need to be achieved (ultimately ascension) and Changelings ultimately don't care about what happens
See the About.
**Changelog**
- tweak: Changelings and Heretics can no longer be converted to the revolution.
> Heretics and changelings can no longer be revolutionaries

- Resources/Prototypes/_Goobstation/Entities/Clothing/Back/backpacks.yml
Goobstation backpacks, not sure if I should add a comment about this or if it's so minor it doesn't matter.
Fixed grammar & spelling in the 2.
:cl: tweak: Fixed spelling of centcomm & blueshield backpacks.
> Minor spelling fixes w/ centcomm & blueshield backpacks

- Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs
Increased avg. round-end time in RampingStationEventScheduler (the survival scheduler) to 2 hours, which is about what we're aiming for with shifts. Current Survival modes end ramping up considerably after the 1 hour mark which usually ends up with a ninja, a few ratkings, and a dragon spawning within 10 minutes which, while often fun, is a little excessive for what should really be the midround.
**Changelog**
:cl: tweak: Slowed down Survival a little bit.
> Slows down the Survival gamemode a bit

- Content.Server/Medical/Stethoscope/StethoscopeSystem.cs
- Resources/Locale/en-US/health-examinable/stethoscope.ftl
Stethoscopes now emit static when someone is sacrificed.
There is no way to tell if someone is sacrificed other than circumstantial evidence. Changelings can be blood tested, so it makes sense heretics can have cases built against them in the same way you can do with a Changeling.
Checks for a component, then returns early. Simple stuff.
naw
**Changelog**
:cl:
- tweak: Stethoscopes can now tell if someone has been sacrificed.
> Stethoscopes can tell if someone's sacrificed

- Resources/Locale/en-US/_Goobstation/game-ticking/dynamic.ftl
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/base.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/dynamic.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/midround.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/roundstart.yml
Dynamic is not laughably bad anymore, and _actually_ scales past the 20 player mark. 
Traitor objectives - 10 shits out 4-6 objective games regularly. 6 brings that back to the 2-4 we all know from back in the day and probably love. 
Midgame Changes - Shit actually depletes the threat level more than maybe 10 a game when it regularly is at 15-30, and major antags actually require the game to of dumped threat into mid game [Leaving very little for the start] or the shift to be at shitfest levels already.
Costs have generally been readjusted, with the solo antags generally being in the same realm without being EXACTLY the same- Lings aren't literally double traitors, just  a little extra, and heretics a little extra than lings- and on the other side thieves slightly less than traitors, not …
> Dynamic doesn't suck now - why was this not done months ago?

- Resources/Prototypes/_Funkystation/Guidebook/sop.yml
Moved Cargo & Engineering SOP back down to SOP 101 :)
:cl:
- fix: SOP placement error in guidebook
> oops - SOP fix!

- Resources/Prototypes/Datasets/ion_storm.yml
Added Johns to ion storm laws, as threats and part of the crew
JOHNS MUST NEVER BE ALLOWED TO ESCAPE HUMAN HARM
:cl:
- add: Johns are now included in ion storm laws
> John Ion Storm

- Resources/Prototypes/Reagents/medicine.yml
- Resources/Prototypes/Recipes/Reactions/medicine.yml
Buffed Aloxadone to what I had wanted it to be originally. Boosting it's heat healing from 3 to 5, and changing the recipe to be less costly.
Aloxadone was originally made very expensive by me to appeal to WizDen maintainers, even if it made it fairly annoying to actually make and use. This buffs it to how near what I had originally envisioned it to be.
**Changelog**
:cl:
- tweak: Aloxadone now heals 5 heat damage, up from 3.
- tweak: Aloxadone's recipe has been buffed to be 20u Aloe, 20u Sigynate, and 60u Cryoxadone for 100u Aloxadone. This results in 2.5x more product per resource intensive ingredient.
> Aloxadone buffed to the original vision

- Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
- Resources/Prototypes/Entities/Structures/Specific/Atmospherics/vox.yml
- Resources/Prototypes/XenoArch/Effects/normal_effects.yml
adds missing gasses to xenoarch and vox atmos stuff
funny
**Changelog**
:cl:
- fix: added missing gas references to xenoarch
> Add custom gases to yaml files

- Resources/Prototypes/Maps/Pools/default.yml
Removes Barratry from the map pool
:cl:
- remove: Removes Barratry from the map pool
> Barratrauma

- Resources/Prototypes/RPD/rpd.yml
Fixed volume pump building a pressure pump. It now builds a volume pump as intended. Also took out the rule requiring pipes be built on subfloors. For parity with the build menu, they can now be built under tiles.
RPD was not working as intended
Changed some yaml properties
None
**Changelog**
:cl: 
- tweak: RPD can now build under tiles
- fix: RPD can now build volume pumps
> RPD - fix volume pump and add building under tile

- Resources/Prototypes/Reagents/gases.yml
Healium now has an upwards limit on how much it can heal, as well as increased booze power. At it's strongest, healium heals about as quickly as cryo does. You can also use slightly more before being forced asleep. 
Healium was too over-powered, allowing people to heal massive amounts of damage in a single a breath. It may still need some more tweaks, but very much needed to be nerfed. 
Changed some yaml properties
None
**Changelog**
:cl:
- tweak: Added max heal rate to healium
- tweak: Increase healium booze power
- tweak: Increase healium minimum mols needed to force user asleep.
> Adjust healium effects for balance

- Resources/Prototypes/Loadouts/role_loadouts.yml
Moved a line in Role_loadouts.yml for the chaplain. 
This change fixes the bug where the chaplain would not receive Annabelle. 
Moved the ChaplainAnnabelle line to be below the CommonBackpack, this would result in Annabelle being replaced by the backpack(presumably)
N/A
**Changelog**
:cl:
- fix: Fixed an issue where the Chaplain's weapon would be replaced by the backpack during loadout application.
> Fix for Annabelle missing from backpack.

- Content.Server/_Funkystation/Medical/SmartFridge/SmartFridgeSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/smartfridge.yml
Title
good
adds a component and now checks for a Wrench tag on OnInteractEvent
**Changelog**
:cl:
- tweak: SmartFridge can now store syringes.
- fix: SmartFridge can now be unanchored.
> SmartFridge is now unanchorable, also takes Syringes

- Content.Server/Explosion/EntitySystems/TriggerSystem.cs
- Content.Server/Flash/FlashSystem.cs
- Content.Server/_Funkystation/Construction/Condition/RevolutionaryCrafterHasComponent.cs
- Content.Shared/_Funkystation/Revolutionary/RevolutionaryFlashOnTriggerComponent.cs
- Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
- Resources/Prototypes/_Funkystation/Entities/Weapons/revolutionary_flashbang.yml
- Resources/Prototypes/_Funkystation/Recipes/Revolutionary/revolutionary_flashbang.yml
Exactly what it sounds like. They can also be crafted by using a screwdriver on a flashbang, with a 15 second do after. Regular revolutionaries / non revs cannot craft them. Head revs are the only ones who can activate and use the flashbang like you would expect it to. Regular revolutionaries cannot.
Funny as hell (plus I felt it was missing)
Adds a RevolutionaryFlashOnTrigger comp, as well as a RevolutionaryCrafterHasComponent construction condition. plus some more yamling
wizden changes
**Changelog**
- add: The revolutionary flashbang, a new favorite for young revolutionaries.
> Adds the revolutionary flashbang

- Content.Shared/Implants/Components/ImplanterComponent.cs
- Resources/Prototypes/Catalog/Fills/Crates/medical.yml
- Resources/Prototypes/Recipes/Lathes/medical.yml
I'm not doing 3 prs for simple yaml changes.
* Reduces implant remover time by 40 seconds.
* Doubles the amount of mindshields in a crate.
* Implanters are now cheaper, only costing 2 glass and 2 steel. 
Rev's should be encouraged to find alternative ways to do a successful revolution, and in a way that's also lore friendly. Capturing command should be made easier, and removing the implants of security should also be made easier. Mindshields also need to be more plentiful, as it makes it easier for command to respond to a rev threat.
yaml
**Changelog**
:cl:
- tweak: Mindshields come in crates of 6 now.
- tweak: Implanters now cost 2 glass and 2 steel.
- tweak: Implanters can now remove implants in 20 seconds now.
> Revolutionary Balance Changes

- Content.Client/Actions/UI/ActionAlertTooltip.cs
- Content.Client/Stylesheets/StyleNano.cs
- Content.Client/UserInterface/Systems/Alerts/Controls/AlertControl.cs
- Content.Client/UserInterface/Systems/Alerts/Widgets/AlertsUI.xaml.cs
- Content.Server/Silicons/Borgs/BorgSystem.cs
- Content.Shared/Alert/AlertState.cs
- Content.Shared/Alert/AlertsSystem.cs
Ports my Dynamic Message Alert support from RMC14 at https://github.com/RMC-14/RMC-14/pull/4150, adds it to the Borg Battery alert so it functions in real-time
Cool generically useful feature
Video Demonstration
https://github.com/user-attachments/assets/819e8d97-9b1a-483e-bd5e-7740e652e213
**Changelog**
:cl:
- add: Added the ability for Alerts to show dynamically updating text in real-time.
- add: The Cyborg's Battery Alert on the sidebar will now show your charge percentage in real-time when you hover over it with your mouse.
> Port Dynamic Message Alerts + add to Borg Battery Alert

- Content.Server/_Goobstation/Changeling/ChangelingSystem.Abilities.cs
- Content.Server/_Goobstation/Changeling/ChangelingSystem.cs
- Resources/Prototypes/_Goobstation/Changeling/Entities/Mobs/headcrab.yml
Ling biomass drain is halfed, vomiting blood is changed with normal vomit, and the headslug can go through doors and tables (and can be used while cuffed)
Headslug was so terrible it needed a huge buff, despite being a last resort you literally can never use it at all since it would get stuck on doors or you were cuffed and couldn't use it.
Biomass drains too much, so you'd need to kill every 20 minutes so you wouldnt puke blood
Vomiting blood was a dead giveaway. It's just complete bullshit just walking around and then suddenly you've got a full clip of lead in your head cuz you forgot to eat a clown.
**Changelog**
:cl:
- tweak: Changed biomass drain and vomit
- tweak: Changed headslug to work in cuffs and to move under doors
> Ling biomass change + Headslug buff

- Resources/Locale/en-US/reagents/meta/gases.ftl
- Resources/Prototypes/Atmospherics/gases.yml
- Resources/Prototypes/Reagents/gases.yml
- Resources/Prototypes/Reagents/narcotics.yml
Makes small changes to tg gases. Reagent colors have been changed to match original hex values. BZ effects have been tweaked so that it actually does something when you inhale it. Nitrosyl plasmide slowly deals poison damage. Some reagent descriptions have been slightly changed. 
Mostly cleaning up placeholder values and descriptions. Most changes are very minor, however this does include a fix for BZ's seeing rainbows effect. Nitrosyl plasmide has also been changed to deal 0.1 poison damage as it metabolizes. 
None
None
None
**Changelog**
:cl:
- tweak: Added poison damage to nitrosyl plasmide
- fix: Fixed BZ rainbow effects
> clean up /tg/ gas code

- Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
lowered heretic spawning from 20 to 8
lowpop mrp will be forced into extended if this isn't done, and it just so happens mrp is like 15 players half the time.
I also removed the wait time, it was basically useless anyways since it was literally just 30 seconds.
So this is basically a bandaid fix, im not messing around with gamerule stuff just to allow like 1 tot on a 8 pop server. Plus its quicker for me to do this so the mrp heads can actually enjoy the game.
**Changelog**
:cl:
- tweak: Heretic can spawn on low pop
- fix: Fixes lowpop getting set to extended if the heretic player req isnt met
> Lower Heretic Player Req

- Content.Shared/Flash/Components/FlashComponent.cs
- Resources/Prototypes/Entities/Objects/Weapons/Melee/stunprod.yml
- Resources/Prototypes/Entities/Objects/Weapons/security.yml
Stun batons are now a 2 hit stamcrit if timed well, and flashes now stun for double duration (1.5s -> 3s), allowing a flash cuff if timed quickly enough.
Why?
Sec equipment kinda sucks ATM. Buffing Sec equipment can lead to more fun antag equipment down the road so everyone has better tools to deal with everything without admin intervention.
:cl:
- tweak: Stun batons now stamina-crit in two hits rather than three
- tweak: Flash stun duration doubled to 3 seconds
> Flash & Baton buff

- Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
This PR just adds the non hardsuit carp costume to the AutoDrobe, with only one in stock. From my memory, it was like this in Space Station 13, and also is like this on Delta V.
This is a very very simple change. All it does it add the original non-hardsuit carp costume to the AutoDrobe, this isn't meant as some kind of fix for meta gaming the suit or anything, I just really like how the carp suit looks and would like to see it as a easily accessible costume again, seeing as the AutoDrobe is meant for re-enactments and theater and such. Currently, the only other way to get a carp suit is either from an uplink or from The Grand Lottery, meaning its almost impossible, and very unlikely to come across one.
Changes \Resources\Prototypes\Catalog\VendingMachines\Inventories\theater.yml to add …
> Add (non hardsuit) Carp Costume to AutoDrobe

- Resources/Prototypes/Entities/Mobs/Species/base.yml
https://github.com/Goob-Station/Goob-Station/pull/1210
**Changelog**
:cl: AstroDogeDX
- fix: All playable species can now wriggle free from being carried.
> Port: Add CanEscapeInventory component to BaseMobSpecies

- Resources/Locale/en-US/_Goobstation/game-ticking/game-presets/presets-revolutionaries.ftl
Fixes the shuttle-call announcement when revs lose
So that's why it does that . . . no CL needed really
> Fix rev shuttle call announcement

- Resources/Prototypes/_Funkystation/Entities/Objects/Fun/toys.yml
All self insert plushies from https://github.com/funky-station/funky-station/pull/168 have been changed to generic names and descriptions, while still keeping the branding of "Self Insert Plushies" in the shift click / inspect description.
Helps avoid causing too much attention to be given to specific crew member's characters just because they have self insert counterparts, as it may be perceived as favoritism from the Contributors to a specific person. While for a time it did give some quality, interesting role play opportunities, that time has passed.
Edit toys.yml to make everything generic.
**Changelog**
:cl:
- tweak: Not So Self Insert; All self insert plushies are now more generic.
> Not So Self Insert

- Resources/Maps/_Funkystation/cluster.yml
- Resources/Maps/loop.yml
Gate station is now in pair with other stations in difficulty with setting up power,
updated loop atmos and fixed an error in cluster station atmos.
Gate is basically a death-sentence for the engineering department.
updated map files
**Changelog**
🆑 
- add: plasma gas miner to loop
- tweak: gate station is now playable for engineering department
- fix: fixed storage chamber in cluster station atmos having round-start plasma
> Gate, Loop, and Cluster Atmos Improvements

- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/dynamic.yml
- Resources/Prototypes/_Goobstation/game_presets.yml
- Resources/Prototypes/game_presets.yml
(cherry picked from commit 66fea4fcf191f27bd084a50b17ae119fc405b1e2 https://github.com/Goob-Station/Goob-Station/pull/1010)
https://github.com/Goob-Station/Goob-Station/pull/1010#issue-2704797573
> ## About the PR
> Now there will be much less midround antags, no ninja, lone ops, multiple skeletons and rat kings every shift. Also added heretic to all at once gamemode.
> 
> ## Why / Balance
> ## Technical details
> ![2024-11-29-135838_1920x1080_scrot](https://private-user-images.githubusercontent.com/93730715/391065191-4a119f8b-7c63-4e78-abc3-16779a15dcad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NzY5MzIsIm5iZiI6MTczNTg3NjYzMiwicGF0aCI6Ii85MzczMDcxNS8zOTEwNjUxOTEtNGExMTlmOGItN2M2My00ZT …
> Fix absurd amount of midround antags (#1010)

- Content.Shared/Atmos/Atmospherics.cs
- Resources/Prototypes/Atmospherics/gases.yml
Reverted the Frezon Oxygen:Tritium Ratio Nerf
Changed Frezon tritium ratio to 1:50 from 1:8 / Nerfed price from 2 A mol to 0.5 A mol
Due to frezon being requiered in higher amount for making other gasses.
Yaml.
**Changelog**
🆑 
- tweak: Reverted the Frezon Oxygen:Tritium Ratio Nerf
> Revert frezon tritium:oxygen ratio

- Resources/Locale/en-US/job/job-description.ftl
- Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
Roboticist now has a proper job description ~~and robotech encryption keys now have access to the binary channel.~~
**Changelog**
:cl:
- fix: Roboticist now has an actual job description.
> Roboticist tweaks

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
- Content.Server/Antag/AntagSelectionSystem.cs
- Content.Server/Antag/Components/AntagSelectionComponent.cs
- Content.Server/Station/Systems/StationJobsSystem.Roundstart.cs
- Content.Server/_Goobstation/PendingAntag/PendingAntagSystem.cs
- Content.Shared/Antag/AntagAcceptability.cs
- Resources/Locale/en-US/_Goobstation/preferences/ui/humanoid-profile-editor.ftl
- Resources/Prototypes/GameRules/midround.yml
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
- Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
- Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/midround.yml
- Resources/Prototypes/_Goobstation/GameRules/Dynamic/roundstart.yml
- Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
- Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml
https://github.com/Goob-Station/Goob-Station/pull/1012#issue-2705214193
> ## About the PR
> Now all antags except initial infected (there must be a delay for them so no zombies roundstart) are not delayed and are rolled before jobs. So you can pick a sec officer and you can still roll antag (your job will be different though). Made that all intern roles can roll antag because why not.
> 
> Hopefully nothing breaks.
> 
> ## Why / Balance
> People asked for it.
> 
> ## Technical details
> ## Media
>  antag.mp4 (pretend this is a video)
> ## Requirements
> * [x]  I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
> * [x]  I have added media to this PR or it does not …
> Roll antags before job

- Content.Server/Atmos/Components/AtmosResinDespawnComponent.cs
- Content.Server/Atmos/EntitySystems/AtmosResinDespawnSystem.cs
- Content.Server/Explosion/EntitySystems/SmokeOnTriggerSystem.cs
- Content.Server/Fluids/EntitySystems/SmokeSystem.cs
- Content.Shared/Chemistry/Components/SmokeComponent.cs
- Content.Shared/Explosion/Components/OnTrigger/SmokeOnTriggerComponent.cs
- Resources/Prototypes/Entities/Clothing/Back/specific.yml
- Resources/Prototypes/Entities/Effects/chemistry_effects.yml
- Resources/Prototypes/Entities/Objects/Tools/firefightingnozzle.yml
ATMOS resin has been changed to remove toxins and normalize temperatures on dissipation rather than on initial tile spread, making ATMOS resin much stronger. Duration, and therefore spread, of ATMOS resin has also been increased, making it capable of effecting much larger rooms. Cost of firing resin has been reduced from 50 to 40, and the firefighting backpack capacity has been lowered from 1250 to 1200. 
The old system was built into SmokeSystem and needed to be moved to it's own atmospheric system and component. Having resin only clean the tiles on initial spread scaled poorly with duration and spread properties. 
- Reverted SmokeSystem, SmokeComponent, and SmokeOnTriggerComponent to their originals
- Made a AtmosResinDespawnComponent and AtmosResinDespawnSystem to handle temperature …
> ATMOS Resin changes

- Resources/Maps/_Funkystation/kettle.yml
I added station beacons to kettle for players to see more clearly the departments around the station.
It was changed so players can find their way about more.
**Changelog**
:cl:
- Added Whisky to Chief Engineer's office in Kettle.
- Added beacons across the station inside kettle station.
> added station beacons to kettle

- Resources/Prototypes/Damage/modifier_sets.yml
- Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
Title
Silver ammo might prove useful now.
Zombies still don't take holy damage (they can't unless I modified the damage container which I can't figure out how to do)
:cl: Mish
- tweak: Skeletons now take twice as much brute and holy damage.
- tweak: Zombies take less damage from most sources besides holy.
- tweak: Holy damage real?
> Adds holy to damage modifiers, buffs zombies, nerfs skeletons

- Content.Shared/_Goobstation/Blob/Components/BlobCoreComponent.cs
- Resources/Prototypes/_Goobstation/Blob/blob_mobs.yml
- Resources/Prototypes/_Goobstation/Blob/misc_blob.yml
* Blob attack costs 1 instead of 4
* Midround blob now spawns as a regular mouse
* Blobbernauts now have short raffles
Hopefully making blob a little less painful to play and get set up
**Changelog**
-->
:cl:
- tweak: Blob abilities tweaked & midround blob spawns as a regular mouse
> Minor blob changes

- Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
- Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
Title
It's how it always ends anyhow, people have to stop feeding rat kings and letting their army grow to massacre the station.
**Changelog**
:cl: Mish
- tweak: Rat kings are now officially antagonists
> Rat kings are antagonists now

- Content.Server/Body/Systems/BodySystem.cs
- Content.Shared/Body/Part/BodyPartComponent.cs
- Content.Shared/Body/Systems/SharedBodySystem.Parts.cs
ports [#1406](https://github.com/Goob-Station/Goob-Station/pull/1406) from goobstation. no more 300 bloodloss damage while transplanting limbs
**Changelog**
:cl: deltanedas
tweak: Losing a limb makes you bleed profusely instead of dealing bloodloss damage.
> [port] make limb severing bleed instead of bloodloss damage

- Content.Server/_Goobstation/Blob/Components/StationBlobConfigComponent.cs
- Content.Shared/_Goobstation/Blob/Components/BlobCoreComponent.cs
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Blob is a midround spawn now as well, weight is slightly less than a dragon
Station alert time is increased
Attack cost doubled (set to 2)
:cl: Miiish
- tweak: Blob can now spawn midround!
> Blob tweak

- Resources/Prototypes/Entities/Objects/Specific/Medical/surgery.yml
The Medical Multitool's doAfter speed (the speed at which the loading bar progresses) has been changed from 2x the normal tool speed to 0.75x the normal tool speed.
Credit to Cthyga on the Funky Station Discord for the original idea for this nerf.
If the normal tools are considered the baseline of speed, then there are only two ways they could be improved. One could either:
1) Increase the speed of the loading bar (shorter doAfter speeds), shortening the amount of time it takes to complete a single step
or
2) Combine multiple surgical tools into one object, decreasing the time it takes for you to move from one step to the next.
Going beyond the basic surgery tools, a set of upgraded tools already exists that accomplishes the first possibility (the Advanced Retractor, the Energy Scalpel, …
> Nerfed the Medical Multitool's doAfter Speed

- Resources/Prototypes/_Goobstation/game_presets.yml
Now in-line with the rest of the gamemodes so events aren't firing double what they should be
Removed a line
> Removes Antag scheduler from Blob gamemode

- Content.Server/_Goobstation/Blob/BlobCoreSystem.cs
Mousing over the alert Blob Resources alert will show you how many points you have
The current display method is evil and inaccurate, more integration of ported feature
https://github.com/user-attachments/assets/02dce84a-7f52-435c-9e0e-90e3c957c80a
**Changelog**
:cl:
- add: The Blob can now see their exact resource total in real-time by mousing over the Blob Resources Alert on the right side of the screen.
> Add exact Blob Resource display on alert

- Content.Server/GameTicking/Rules/Components/RevolutionaryRuleComponent.cs
- Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
- Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
- Resources/Locale/en-US/_Funkystation/shuttle/fail_reasons.ftl
- Resources/Locale/en-US/_Goobstation/game-ticking/game-presets/presets-revolutionaries.ftl
When Command calls the evac shuttle, after the wait period ends, the evac shuttle doesn't arrive. Instead, a message is broadcast that the evac shuttle could not dock because of strange activity on the station. Also with this change, when all of command is dead, the round just ends. (We understand that rounds with no command will just auto-end, too bad too sad.)
This PR also changes `revolutionaries-win-sender` to Yucatan Communications, to be more in-line with Funky lore.
Too many half measures and half baked features make revs terrible to play on Goob down-streams. Having the communications console just not be able to call evac makes the game-mode so easy to meta. The terror and panic (or …
> Revs: Evac shuttle doesn't arrive when HRevs are alive

- Content.Server/GameTicking/Rules/Components/RevolutionaryRuleComponent.cs
- Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
- Resources/Locale/en-US/game-ticking/game-presets/preset-revolutionary.ftl
If there are still alive Head Revolutionaries, but none of them are on station, they will prompted to return to the station within 1 minute, or else they lose. Upon atleast one returning to the station, all Head Revs will be notified that the Revolution is no longer at risk, and the timer will stop. 
The timer will reset to its full length and activate if this condition is triggered again.
Prevent ATS/shuttle camping and round stalling. Just like Command has to be on station to progress the round, so do Head Revs.
**Changelog**
:cl:
- tweak: If all alive Head Revolutionaries abandon the station, a 1 minute timer will now start that counts down until a Head Revolutionary returns. If no Head …
> Revs: Revolution fails if HRevs abandon station for >1 minute.

- Resources/Prototypes/Entities/Mobs/base.yml
(cherry picked from commit 53c9543cd6edf96ff9576d94cd7967b9f2918294)
https://github.com/Goob-Station/Goob-Station/pull/1057 - thanks deltanedas
**Why**
Ashing is broken as hell with Shitmed and results in unrevivable bodies with no organs
**Changelog**
:cl: deltanedas
- remove: Extreme heat no longer turns people to ash.
> [port] [goob #1057] disables ashing

- Resources/Prototypes/Atmospherics/gases.yml
Changed the following prices of atmospheric gases:
Tritium 1.4 -> 0.4
Frezon 0.5 -> 1.2
BZ 1.0 -> 1.2
Healium 2.5 -> 2.7
With current Atmospheric setups that are becoming slowly more common knowledge, it is possible to produce canisters of 1,000,000 spesos with only thirty or so minutes of waiting. Said canister consists of only Tritium being sold at 1.4 spesos per mole. Honestly this has grown a bit boring and I have been settling to do more work for less money (Making healium cans only worth 20,000ish after two hours of work). I think a change in prices can lead newer atmos players to want to learn the hard setups and make actually doing hard setups worthwhile. 
This only really changes the experience inside atmospherics as cargo is going to get rich no matter what.
changed gases.yml …
> atmospheric gas pricing rebalance

- Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
Removes Self-insert plushies from Locker loot tables.
**Changelog**
:cl:
- remove: Self-insert and Stowaway brand plushies no longer spawn in lockers.
> Self-insert and Stowaway spawn removal

- Content.Server/Station/Systems/StationSpawningSystem.cs
- Resources/Locale/en-US/_Goobstation/preferences/ui/humanoid-profile-editor.ftl
Ports https://github.com/Goob-Station/Goob-Station/pull/1479 from goob, allowing Station AI to use preferred borg (now silicon) name.
Customisation!
Borg name code now checks if you are AI, and doesnt apply the identifier lable (e.g. Si-1346) if you are.
I don't know why yet but im having difficulty launching compared to goob but the code is the same so it should work.
**Changelog**
:cl:
- add: Station AI now uses preferred silicon name!
> Port AI preferred name from goob

- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Added the luxury hardsuit to spawn in the quartermasters locker, where it belongs.
QM lacks a hardsuit spawn, this fixes that.
**Changelog**
:cl:
- add: added luxury hardsuit spawn to the quartermasters locker
> Luxury Hardsuit Spawns in QM Locker

- Resources/Maps/packed.yml
Reverted Packed to its previous version
The SM area feels tacked on, for a lack of better words. It's also very overpowered round start. 16 SMES, Over 10 Freezers. It looks like something that someone would create during a course of a Frontier Station shift (6 hours) in terms of the sheer amount of things pre made for it.
- [ x] I have added media to this PR or it does not require an ingame showcase.
> Revert Packed to Singulo

- .gitmodules
- Content.Shared/Roles/Jobs/SharedJobSystem.cs
- Content.Shared/StepTrigger/Components/StepTriggerImmuneComponent.cs
Fixed "The Error" that made it impossible to tell what was or wasn't actually needing to be updated. 
Because without fixing The Error no progress would be made.
I had originally planned to rollback RobustToolkit engine optimizations to fix The Error, hence the name of the branch, but I was persuaded otherwise. Those rollbacks aren't present in this because RobustToolkit isn't present in the repository itself, and the rollback wouldn't be necessary anyways. The actual fix was just to change a single duplicate class definition in StepTriggerImmuneComponent.cs . In other words noslips broke the game for multiple weeks. 
Also there was exactly one change I made to how a job role was accessed to fit update class structures, but there's a lot more of that that needs to be done and I don't even …
> Fixing ISerializationGeneration errors or THE pull request of all time

- Content.Shared/_Goobstation/Changeling/ChangelingInfectionComponent.cs
I made the sleep time of changeling shorter. Less painful. More funner. Also I made it take five minutes longer for you to show symptoms so the total infection time isn't too short. And it also makes it more stealthy!
It means players who get infected won't just ghost due to thinking it's bugged as often. 
Changed default value of FullyInfectedDelay from 1800 to 1320, and FirstSymptomDelay from 300 to 600, as well as KnockedOutDelay from 900 to 1200, in the ChangelingInfectionComponent.cs file.
Hopefully none, as it was just a change of a few float values.
**Changelog**
tweak: made changeling infection cause way less sleep-time
> Changeling infection tweaks 

- Resources/Prototypes/StatusIcon/faction.yml
one line yaml change. Revolutionaries can no longer see each others status, they can only see Head Revolutionaries.
Revolutionaries have a severe snowballing problem. Doing this will force revolutionaries to co-ordinate more through other means, and using IC methods to do so, rather than just looking at each other, finding the red R, and going in and killing people. That entirely defeats any methods to do fun stuff IC, because you already know who's who.
**Changelog**
:cl: 
- tweak: Revolutionaries can no longer see each others rev status.
- tweak: Revolutionaries can only see HRevs.
> Revs: Revolutionaries can no longer see each others rev status

- Content.Server/Flash/FlashSystem.cs
- Resources/Locale/en-US/flash/components/flash-component.ftl
- Resources/Prototypes/StatusIcon/faction.yml
A small pop up appears when a crew member is converted.
`Dawn Leander's eyes turn white for a second, before returning to normal.`
Finally, a give for when someone is a head rev. No more LOOC mald nonsense.
**Changelog**
:cl:
- tweak: Converting someone as a head revolutionary now creates a pop-up for everyone who witnesses it.
> Revs: Popup now appears when an HRev converts crew

- Resources/ServerInfo/Guidebook/Security/SpaceLaw.xml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Tweaked it to follow with repeat offenses so that highest-ranking security in lieu of a HoS or Warden can sentence
Small wording to give the sentencing power to highest security member instead of just command
Liberal Wall of text....
- [ x] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
:cl:
- tweak: Wording change to give sentencing power to highest ranked security instead of just command
> Small wording tweak

- Content.Client/HealthAnalyzer/UI/HealthAnalyzerWindow.xaml
- Content.Server/_Goobstation/Heretic/EntitySystems/MansusGraspSystem.cs
- Resources/Prototypes/_Goobstation/Heretic/Entities/Objects/Specific/heretic.yml
Fixed the assert crashes/changed the code to fit other code changes from merging upstream (maybe??) with heretic. Changed the scale of the body part selection sprite on the health analyzer so it is no longer larger than it's own viewport and fits neatly and correctly within the bounds of the clickable buttons for the individual parts. 
Not a change but noteworthy: I screwed around with Heretic and Shitmed for like two hours and did not experience a crash after these changes, further testing is probably a good idea but it seems mostly stable ish.
Because, uh, uhm, upstream, uh
Hristov rework is cool so yea because this enables us to have that
The mansus grasp was triggering an assert crash because it kept checking if the grasp was deleted and then throwing the assert. The mismatch probably …
> Fixed health analyzer limb display and asserts on Heretic mansus

- Resources/Prototypes/_Funkystation/Reagents/exotic.yml
Changed the description for Muigroc to inverted
Makes more sense to have it match with juice that makes you hew which is also spelled backwards. 
minor YML changes
**Changelog**
:cl: Changed evil corgium descriptor
> Change evil corgium descriptor

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
…l consensus is that this 'Rebalance' is just a mald pr from someone bad at aiming. --Reverts commit f964908
Reverts the changes made in commit f964908 on wizards upstream. General consensus on the discord from those who commented was that this seemed like a mald pr from someone who can't aim.
Undoes an upstream "Rebalance" that in others and my opinions just makes disablers and the disabler SMG overpowered.
just changed the values in the two yml files to what they were before the upstream merge
pew pew
- [x ] I have added media to this PR or it does not require an ingame showcase.
pew pew (none)
unless you …
> Reverts the 'Rebalance' done to disablers by wizards upstream

- Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
makes a very low chance for the mining hardsuit on the already legendary rarity loot table to be replaced by the maxim hardsuit
it makes the maxim hardsuit actually obtainable aside from an extreme edge case that i haven't quite figured out yet on a certain exped type
changed the ClothingOuterHardsuitSalvage on the legendary loot table to a GroupSelector between the COHS and the ClothingOuterHardsuitMaxim with a 0.05 weight on the COHM
there's no media it's a code change grrrr
- [totally] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [hella] I have added media to this PR or it does not require an ingame showcase.
THE MAXIM HARDSUIT IS REAL!!!!
**Changelog**
:cl: …
> makes maxim hardsuit real

- Resources/Prototypes/_Goobstation/Loadouts/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/_Goobstation/Loadouts/Jobs/Command/nanotrasen_representative.yml
Blueshield Officer and Nanotrasen Representative's mantle time requirements were previously 50 hours. They are now 20 hours, matching the rest of the mantles' time requirements.
I see no convincing reason for BSO/NTR to specifically have more difficult mantles when compared to command members.
2 lines have been changed in yaml...
NO!!!
N/A
**Changelog**
:cl:
- tweak: BSO/NTR mantle time requirements are now 20 hours instead of 50 hours
> Standardize mantle time requirements for BSO/NTR

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
This 'Reversion' is just a mald pr from someone upset at people using non-lethals. --Reverts commit fe2f7f7
Reverts the changes made in commit fe2f7f7 on funky station.
Undoes a downstream "Rebalance" that in others and my opinions just makes disablers and the disabler SMG underpowered.
In all seriousness -- a weak disabler makes Security toothless to combat anybody for whom lethals are not authorized. The reversion this PR undoes would serve to make Security generally unable to effectively fight people without either being
1) Very robust (which sec isn't supposed to have to be, thus why they are allowed to carry this sort of equipment)
or
2) Willing to use lethals against people they should be disabling (which nobody should want)
Discouraging Security from using non-lethal modes of …
> Reverts the 'Reversion' done to the rebalance to disablers

- Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
- Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
- Resources/Prototypes/Roles/Jobs/Command/captain.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
- Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
- Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
- Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
- Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
- Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
- Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
- Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
- Resources/Prototypes/Roles/Jobs/Science/borg.yml
- Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
- Resources/Prototypes/Roles/Jobs/Science/research_director.yml
- Resources/Prototypes/Roles/Jobs/Science/roboticist.yml
- Resources/Prototypes/Roles/Jobs/Science/scientist.yml
- Resources/Prototypes/Roles/Jobs/Security/detective.yml
- Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/warden.yml
- Resources/Prototypes/_Funkystation/Roles/Jobs/Command/internal_affairs_agent.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
Biggest changes:
NTR now requires 10 hours IAA and 40 hours Command playtime
Across the board, all Command (besides BSO and QM, both of which require 20 overall and 20 departmental respectively) now require 25 hours overall time and 20 hours in their department. Captain and HoS both require 40 hours overall playtime.
Interns now need 4 hours (or a playtime transfer) to graduate instead of 2, and can continue to play until 20 hours playtime as that intern role (previously 15)
Also added Law access to IAA (I double dipped sorry)
Overall discussion about roletime changes in the Discord
Particularly for Command and Sec.
This was beyond due as our playerbase now collectively has a lotta hours to justify increasing from our previously low time requirements (which was necessary at the time …
> Role timer updates

- Resources/Prototypes/_Funkystation/Entities/Weapons/miniaturelaserpistol.yml
Updated disabler plus and miniature laser pistol capacity and shot cost to match buffed disablers. 
Disabler plus now has 30 shots (a 50% increase in capacity, like before). Miniature laser pistol has capacity for 30 disabler shots or 15 lethal shots.
Disabler plus was intended to be a high capacity weapon for the head of personnel. When disablers were buffed, they surpassed the capacity of the disabler plus. This PR puts the disabler plus back in line with the original intent. Changes to the Miniature Laser Pistol are to keep it inline with current balance.
No code, just changes to YML.
**Changelog**
:cl: Cthyga
- tweak: Updated disabler plus capacity from 15 to 30 shots.
- tweak: Updated miniature laser pistol disabler capacity from 10 to 30 shots.
- tweak: Updated miniature laser …
> Updated Disabler Plus and Mini Laser Pistol Capacity

- Resources/Prototypes/Entities/Mobs/NPCs/space.yml
why are snails stored in the salvage creatures dataset
Speed snails now have the same singing capabilities as a harpy (for better or worse. Could just restrict it to one type if needed)
Another quest PR from the maintainer QnA
singular yml change
https://github.com/user-attachments/assets/789af528-40bb-4ac5-b534-a1b0986c5873
**Changelog**
:cl: Middleson
- tweak: Speed Snails can now sing!
> Singing Speed Snails

- Content.Shared/_DV/Surgery/SurgeryContaminableComponent.cs
- Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
tend wounds no longer causes bleed stacks )hopefully) (it worked locally) (im scared)
less poison damage if you forget to clean your gloves or whatever
**Changelog**
:cl:
- fix: tend wounds no longer causes bleeding
- tweak: unsterile surgery causes a little less poison damage
> make surgery easier (again) 

- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/clownpatrol.yml
- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/foamroid.yml
- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/loneroboticist.yml
- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/mouseJumpscare.yml
- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/skeletonMafia.yml
- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/wanderingNomad.yml
- Resources/Prototypes/GameRules/unknown_shuttles.yml
- Resources/Prototypes/_Funkystation/Entities/Mobs/Player/ShuttleRoles/roles.yml
- Resources/Prototypes/_Funkystation/Entities/Mobs/Player/ShuttleRoles/settings.yml
- Resources/Prototypes/_Funkystation/Entities/Mobs/Player/ShuttleRoles/spawners.yml
- Resources/Prototypes/_Funkystation/GameRules/unknown_shuttles.yml
- Resources/Prototypes/_Funkystation/Roles/Jobs/Fun/visitors_startinggear.yml
- Resources/Prototypes/_Funkystation/Shuttles/shuttle_incoming_event.yml
Added 6 new shuttles to the randomeventshuttle spawnpool- shuttles included are:
New Janitorial shuttle! (mouseJumpscare.yml)
New Roboticist shuttle! (loneroboticist.yml)
New hidden challenge / asteroid shuttle! (foamroid.yml)
New Skeleton free agent shuttle! (skeletonMafia.yml)
New Security clown shuttle! (clownpatrol.yml)
New Nomad cigarette / Smokeables salesman shuttle! (wanderingNomad.yml)
Added Ghostrole spawner markers for each shuttle as well - small code additions for proper ghostrole spawning. All organized under funkystation branch and utilizing the same conventions as other spawners.
New, interesting shuttles are good to have to help spice up the normal shuttle spawning pool- I am hoping that these shuttles will lead to increased roleplay and utilization of the ss14 shuttle …
> Added 6 New Midround Ghostrole shuttles - added to shuttlevent spawnpool as well

- Resources/Prototypes/_DV/Entities/Mobs/Species/rodentia.yml
- Resources/Prototypes/_DV/Species/rodentia.yml
Re-enables rodentia.
I've had a change of heart on the Rats. Rodentia are no longer scaled to be smaller, which allows their features to be more known and present (makes them less ugly). Oh yeah, their crawl is also gone.
**Changelog**
:cl:
- add: Rodentia have been re-enabled.
> MAKE RODENTIA GREAT AGAIN

- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/clownpatrol.yml
- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/loneroboticist.yml
- Resources/Maps/_Funkystation/Shuttles/ShuttleEvent/mouseJumpscare.yml
- Resources/Prototypes/_Funkystation/GameRules/unknown_shuttles.yml
Minor map changes / fixes
Fixed some issues with power getting to thrusters on mouseJumpscare.yml and loneroboticist.yml, swapped place of gravgen and air tank on loneroboticist.yml for easier tank swappage. Got rid of bugged blast doors on clownpatrol.yml
Altered the weights of loneroboticist and foamroid to be slightly higher but still uncommon to rare
Just makes the shuttles better and easier to play on and work with, should have done this since the beginning.
upped the rates because I hadn't seen any of the new shuttles outside of the most common ones for almost three days (at least in replay logs), may tweak further as time goes on
Changes to maps mouseJumpscare.yml, loneroboticist.yml, and clownpatrol.yml
N/A
N/A
**Changelog**
:cl:
- tweak: Shuttle fixes.
> Minor shuttle tweaks and spawnweight changes

- Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
Makes sure all current job names are aligned
Overlength Nanotrasen Representative name shifted the buttons to the right
Increased minimum width of the job name label in the job selector for character creation.
Before:
After:
none
**Changelog**
:cl:
- tweak: Aligned Nanotrasen Representative name with the rest of the job names
> Align items in job selector

- Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
- Content.Server/RoundEnd/RoundEndSystem.cs
- Content.Server/Shuttles/Systems/EmergencyShuttleSystem.cs
- Resources/Locale/en-US/game-ticking/game-presets/preset-revolutionary.ftl
Converting command is now considered a major victory. Other win conditions have been changed.
This is to accurately reflect the direction we want Revs to go in. Revolutionaries should be encouraged to Roleplay and succeed in different ways. While sometimes it is fun for a game to turn into a deathmatch, that's not fun *all* the time.
Changed some logic on how round-end text is decided. I also fixed up the bug where after evac is supposed to dock, if theres still revolutionaries aboard, you can't call it again after you win as command.
**Changelog**
:cl:
- add: Converting all of Command is now considered a Major Victory.
- tweak: Killing or detaining some of command is now considered a Partial …
> Revs: Converting all of command is now considered a Major Victory

- Content.Server/_Goobstation/Blob/BlobFactorySystem.cs
- Content.Server/_Goobstation/Blob/NPC/BlobPod/BlobPodSystem.cs
- Content.Server/_Goobstation/Blob/ZombieBlobSystem.cs
- Content.Shared/_Goobstation/Blob/Components/BlobPodComponent.cs
Blob Factories will now produce more Blob Pods to meet the cap (3) when its Blob Pods die
The factories just became useless after the Pods all died
When a Blob Pod dies (normal or as a Zombie) it will now decrement the Spawned counter on the Factory by 1 and remove itself from the Factory's list of produced Pods.
When a Blob Factory dies it will remove itself as the Blob Pods' parent factory so the Pods do not try to tell its dead parent anything when they also die.
Counter Decrement showcase, it will produce more Pods as a result
https://github.com/user-attachments/assets/2d18e6cb-ce59-4491-9e6a-b574168909ee
**Changelog**
:cl:
- tweak: Blob Factories will now resume production of Blob Pods when its previously produced Pods die.
> Blob Factories now actually produce more Pods when the originals die

- Content.Shared/Tools/Components/FirefightingNozzleComponent.cs
- Content.Shared/Tools/Systems/SharedToolSystem.FirefightingNozzle.cs
- Content.Shared/Tools/Systems/SharedToolSystem.cs
- Resources/Locale/en-US/tools/components/firefighter-nozzle-component.ftl
- Resources/Prototypes/Entities/Clothing/Back/specific.yml
- Resources/Prototypes/Entities/Objects/Tools/firefightingnozzle.yml
Rebalances water cost so that it's not all immediately eaten. 
Backpack can only be filled by water tanks and can no longer be used as an OP flamethrower
Adds a system for filling the backpack from the nozzle
Removes the inventory slot from the backpack. Nozzle is now removed with alt+click. 
Removes ability to add chems or fluid to backpack
Allows for filling containers from the backpack
Sinks are currently not capable of filling the backpack. They actually don't have as much water in them as you would think so I decided to avoid that issue entirely for now. Only water tanks can be used to fill the atmos backpack. 
It's way better
None
None
None
**Changelog**
:cl:
- tweak: Atmos water tank backpack QOL changes
> firefigher nozzle and backpack updates

- Content.Server/Atmos/Reactions/NitriumProductionReaction.cs
- Content.Shared/Atmos/Atmospherics.cs
- Resources/Prototypes/Reagents/gases.yml
Pretty significantly buffed healium and nitrium. With so much new content now, the novelty of these gases have kind of worn off, and there isn't really much reason to make them when you can just build yourself robot legs or do maints surgery on yourself instead. 
Also made BZ a slightly more viable huffing drug as the original concept of BZ is that it should be available to crew who want to use it for religious reasons.
The things atmosians make take some of the most dedicated time and effort, and late game atmosians should be something to fear, the same way late game chemists, scientists, virologists and geneticists always have been. 
Increased max healing mols on healium and meticulously tested and balanced to make sure capped healing thresholds are accurate. Also slightly lowered booze …
> nitrium healium and bz buffs

- Resources/Prototypes/Entities/Structures/Machines/flatpacker.yml
Now the Flatpacker can be linked to the Silo
Shuffling materials out of lathes and into the Flatpacker is annoying.
**Changelog**
:cl: Quantus
- add: Flatpacker 1001 can be linked to the silo.
> Allow Flatpacker to be linked to the Material Silo

- Resources/Prototypes/_Goobstation/Changeling/Catalog/changeling_catalog.yml
Removed the transform sting from the changeling catalog
It's generally unenjoyable to get transformed at the start of the round and be stuck like that all round.
Ideally, this would be temporary or there would be a way to revert this, through Genetics or Chemistry. For the time being, it doesn't really fit Funky.
**Changelog**
:cl: Miiish
- remove: Removed transform sting from the changeling catalog
> disable changeling transform sting

- Content.Server/Atmos/Portable/ElectrolyzerSystem.cs
- Content.Server/Atmos/Reactions/HydrogenFireReaction.cs
Fixes the hydrogen fire reaction so that it only produces one mole of water vapor for every 2 moles of hydrogen burned, rather than 1:1.
In this house we obey the laws of thermodynamics.
Simply halved the amount of water vapor the hydrogen fire reaction creates. 
None
**Changelog**
:cl:
- fix: Fixed infinite water vapor bug
> Fix an infinite water vapor bug

- Content.Shared/Drunk/DrunkSystem.cs
- runclient.bat
Adds a cap of 25 minutes to the drunk status. 25 minutes should still allow players to experience the full effects of being drunk for a decent amount of time, while at the same time having an end in sight that will encourage players to sleep off or medicate away the effects. 
People were drunk for entire 2 hour shifts. 
DrunkSystem.cs has been modified to check remaining time on drunk status and only set status time up to a maxDrunkTime. 
None
Modifies Shared/Drunk/DrunkSystem.cs
**Changelog**
:cl:
- fix: Fixed permanent drunkeness
> Cap drunk time to end permanent drunkeness

- Resources/Prototypes/GameRules/roundstart.yml
Made it so there was 1 max commander and 1 max medic for nukie spawns. Also, apparently heretic was disabled. Heretic was re-enabled as a side effect because I cherry picked the vocaloid names commit again. I don't think it did anything else.
Hopefully it makes it so three nukie commanders don't spawn????
Added "max: 1" field to the nukie commander and nukie agent/medic antagspawn components. Re-cherrypicked Vocaloid names, but I think they were already in anyways. I have no idea what's causing the issues on the server.
**Changelog**
:cl:
- fix: Made it so only one nukie commander and one nukie agent can spawn MAX.
- fix: Re-added heretic to sub-gamemodes
> Nukies fixes + accidental heretic fix????????

- Content.Server/EntityEffects/Effects/NitriumMoveSpeedModifier.cs
This PR fixes some unintended behavior with nitrium. Breathing nitrium now consistently grants 6 seconds of move speed enhancement each breath. Since you breathe every 4 seconds, it will consistently last until your next breath. You will no longer have effects last longer than 6 seconds after your last breath of nitrium. 
This is what nitrium was always supposed to do. 
Changes NitriumMoveSpeedModifier so that nitrium effects will no longer stack under any circumstances, and will consistently extend the effects 6 seconds from the time of your last breath. 
None
None
**Changelog**
:cl:
- fix: Fixed nitrium move speed bug. Nitrium speed increase will always last 6 seconds from the moment you last breathe it in.
> Nitrium move speed modifier minor fix

- Content.Server/_Shitmed/Body/Systems/EyesSystem.cs
Perma Blindness now works when you get your eyes removed. Only nearsightedness can be fixed with surgery.
Alternative ways should exist for players to treat blindness in-game, although the old way of replacing someones eyes with surgery should not be it.
Part of a series of patches to balance Quirks.
Code now checks for a PermanentBlindnessComponent. Also checks if its set to 0 (the max value there is).
**Changelog**
:cl:
- tweak: Permanent blindness is now un-treatable.
> Perma Blindness Trait Fix

- Content.Server/_Viva/Borgs/LawSwapSystem.cs
- Content.Shared/_Viva/Silicon/LawboardDoAfterEvent.cs
Borgs are now able to have their laws changed with a lawboard when their chassis is unlocked and opened. It has a 25 second doafter, to ensure you can't just run around zapping borgs with it.
Basically jank lawsync that uses way more manual labor.
The hope is that this would make borg gameplay significantly more varied by allowing it to have a similar degree of variety to AI, however, the increased probability for borgs that are hostile to zombies, nukies, etc could be a concern. Crew Borg weapons aren't particularly strong, but I think it should still be looked out for. 
Added a new LawSwapSystem which listens for a AfterInteractUsingEvent that (I believe, documentation on AfterInteract vs AfterInteractUsing is a bit vague, either way it still works due to how borgs function) uses an …
> Added ability to change laws of borgs using a lawboard 

- Resources/Prototypes/_Goobstation/Changeling/Entities/Mobs/headcrab.yml
Head Slug no longer attempts to open doors when passing under them. Also it can now pilot the Vim Mech.
The slugs are so loud for no reason because of the door bumper, and they pass under all doors anyway so they have no use for it.
It's also small enough that it should be able to pilot the Vim .
New TagComponent to overwrite SimpleMobBase (which has DoorBumpOpener), instead replaces with the VimPilot tag 
**Changelog**
:cl:
- fix: Changeling Head Slugs no longer attempt to open doors they pass under.
- tweak: Changeling Head Slugs can now pilot the Vim.
> Headslug no longer has door bumper + can pilot Vim

- Content.Server/Atmos/Reactions/NitriumDecompositionReaction.cs
Prevents nitrium decomposition sometimes exceeding 100C. This prevents it from being used as an ignition source for tank bombs. 
It was never meant to exceed 70C for this reason, but is capable of going above that temperature at smaller scales. 
Changes NitriumDecompositionReaction so that it will not in any cases exceed 100C
None
**Changelog**
:cl:
- fix: Fixed nitrium decomposition sometimes exceeding 100C
> Fix nitrium decomposition temperature exceeding FireMinimumTemperatureToExist

- Content.Client/Atmos/Monitor/UI/Widgets/ScrubberControl.xaml
- Content.Client/Atmos/Monitor/UI/Widgets/ScrubberControl.xaml.cs
- runclient.bat
Added Select All and Deselect All buttons to air alarms gas filter settings for scrubbers. 
Quality of life
Adds buttons. Entirely client-side. 
None
**Changelog**
:cl: 
- tweak: Added 'select all' and 'deselect all' buttons to the gas filters drop down menu on air alarms
> Scrubber Quick Select/Deselect Buttons

- Resources/ServerInfo/Guidebook/Mobs/IPCs.xml
Adds missing newline to IPC guidebook entry. This fixes the header.
This fixes the header.
This doesn't even add a single letter. This was fixed on DeltaV and Goobstation.
Not needed.
> Adds missing newline to IPC guidebook

- Content.Server/GameTicking/Rules/BloodCultRuleSystem.cs
- Content.Server/GameTicking/Rules/Components/BloodCultRuleComponent.cs
Fixes the off-station timer so that it functions correctly and doesn't just cycle the target every 2 minutes indiscriminately.
Adds a timer for the brain being taken out of the body, allowing Blood Cultists to still sacrifice the brain if they do so within 5 minutes of it being taken out of the body, but prevents the brain from being lost forever due to being unidentifiable as the target's brain, hid in a locker somewhere (or blue space storage implant, for an extreme), or being put inside a Borg which can just lie forever about who it was. Prevents round-stalling from loss of brain overall.
Tracks the original body at time of target assignment (as the target is a mind), for the purpose of tracking mismatches.
Adds a second timer for body mismatches that runs alongside the off station …
> Blood Cult Timer Fix + Additions

- Content.Server/_Goobstation/Heretic/EntitySystems/EldritchInfluenceSystem.cs
Heretic no longer shows their DoAfter to everyone when draining influence.
It is very easy to recognize a heretic draining an influence because of the DoAfter popup that spawns. The intention is to allow heretics to be sneaky when draining influence in the open space. You can still identify a heretic draining an influence if he chooses to carry his book open to gain more points.
Changed the bool Hidden of the DoAfter to true.
- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
**Changelog**
:cl:
- tweak: Heretic influence drain DoAfter are no longer visible to others.
> Hide DoAfter for Heretic influence draining

- Resources/Prototypes/_Impstation/CosmicCult/Mobs/astralforms.yml
The Rogue Ascended mid-round antag currently can currently be made into a zombie, this doesn't really make sense. This gives them the ZombieImmune component to prevent it.
**Changelog**
:cl:
- fix: The Rogue Ascended can no longer be turned into a zombie.
> Make rogue ascended zombie immune

- Resources/Prototypes/_Goobstation/Blob/blob_tiles.yml
Added a glowing effect to some blob tiles: Blob Core, Blob Factory tile, Blob Node tile and Blob Resource tile. Blob Core tile is more visible than the others.
Generally, blob is a lot more dangerous when it's already grown to medium sizes. Blobs often start in maintenance and dark places, where it's hard to see them. Fighting against that is too annoying. While the crew could throw flares and the like, you don't have an infinite supply of them. Now the crew doesn't have to worry about light and focus on the fight strategically - trying to hurt the blob where it hurts, while the Blob player(s) must account for defense, reinforcements and positioning. In theory, this should make the rounds more fun, give "clutch 1000 IQ plays" to the crewmembers, and remove possible boring stalemates.
Just …
> tweak(antag): Adding light to special Blob Tiles

- Resources/ServerInfo/Funkystation/Guidebook/AlertLevel/RedAlert.xml
- Resources/ServerInfo/Guidebook/Security/SpaceLaw.xml
- Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml
Space Law updates!
Under certain circumstances, Mind Shield Implantation is no longer deniable (a known threat is revealed that is committing mass brainwashing/mind control, such as Revs, Blood Cult, etc.)
Crew members that have been de-converted can no longer be sentenced for their crimes if a clear de-conversion takes place (Revs de-converting by dropping to the floor + remembering allegiance, Blood Cultists being de-converted by Chaplain Holy Water and losing the eyes/halo, etc). 
Trespassing in Maints during Red Alert is now Secure Trespassing, instead of Trespassing. Both so it is actually worth it time-wise for Security to enforce this order, and so maybe people actually respect this part of alert procedure.
Not having Suit Coords on Red now has a defined crime attached to it …
> Update space law relating to mind shields, deconversion, red alert

- Content.Server/GameTicking/Rules/Components/RevolutionaryRuleComponent.cs
- Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
- Content.Server/Mindshield/MindShieldSystem.cs
- Content.Server/Revolutionary/RevolutionarySystem.cs
- Content.Shared/Revolutionary/Components/HeadRevolutionaryComponent.cs
- Content.Shared/Revolutionary/Components/ShowRevolutionaryIconsComponent.cs
- Content.Shared/Revolutionary/Revolutionary.Actions.cs
- Content.Shared/Revolutionary/SharedRevolutionarySystem.cs
- Resources/Locale/en-US/_Goobstation/game-ticking/game-presets/presets-revolutionaries.ftl
- Resources/Prototypes/StatusIcon/faction.yml
- Resources/Prototypes/_Funkystation/Actions/revs.yml
Open Revolt is a state where all Revolutionaries can see each other, but the Head Revolutionaries names are revealed in a global announcement by CentComm, causing them to "go loud".  This state triggers whenever a Head Rev chooses to with an action, or whenever the Emergency Shuttle fails to dock (with a ~0-20 second grace period afterward, before it occurs).
Head Revs are prevented from calling for Open Revolt within the first 10 minutes of the round, but may do so at any point afterwards.
This allows Security to progress the game state more narrowly when the revolt is triggered, allowing them to hunt down all the Head Revs specifically (instead of having to kill everyone and hope they get …
> Revs: Open Revolt!

- Content.Server/_Funkystation/Atmos/EntitySystems/BluespaceVendorSystem.cs
- Resources/Maps/_Funkystation/bagel.yml
- Resources/Prototypes/_Funkystation/Entities/Structures/Machines/BluespaceGas/bluespace_gas.yml
- runclient.bat
This PR fixes an issue with the bluespace gas vendor that forced the game back to lobby on map load. The vendors can now be safely mapped in and linked to their sender before the map initializes. 
Bugfix
None
**Changelog**
:cl:
- fix: Fixed issue with bluespace gas vendors forcing the game back to lobby.
> bluespace gas vendor bug fix

- Content.Server/_Impstation/CosmicCult/CosmicCultRuleSystem.cs
- Resources/Locale/en-US/_Impstation/cosmiccult/preset-cosmiccult.ftl
Made it so if the cosmic cult leader fucks off they can elect a new leader and not lose the ability to 1. place the monument if it was never placed, and 2. move the monument if the leader died and its still phase 2
Right now if security finds out where the monument is, or it needs to be moved for some other reason, thats not an option.
Additionally, if they know where the monument is, and its already been moved the cult is just SOL if the leader dies, or if the ability has been used.
This way if the leader dies or cryos (or ssds I am pretty sure) a new leader can be elected, and the cult can have a chance to start anew.
caught the MindRemovedMessage event with an event subscription, removed the leader component from the old leader, then initiated the steward vote again. Also makes a …
> Cosmic Cult Revote on leader death / cryo

- Resources/Prototypes/Catalog/Fills/Crates/service.yml
related to #681
as in the title
there's no way to craft it, but it's requested in bounties - so might as well make it purchasable
self-explanatory
**Changelog**
:cl:
- add: Added the holoprojector to janitorial supplies crate
> Add the holoprojector to janitorial supplies crate

- Resources/Prototypes/_Funkystation/Catalog/Bounties/bountyCategories.yml
related to #681
as in the title
because otherwise the bounty doesn't make sense to anyone
basically, synced the tags from `OrganReptilianStomach`, excluding pills and crayons
**Changelog**
:cl:
- fix: Fixed "Reptilian food" bounty matching only a handful of items
> Make "reptilian food" bounty match all reptilian foods

- Resources/ServerInfo/Guidebook/Engineering/Gasses.xml
Many new gasses were added to the Atmospherics guidebook page, but not to the sub-page of Gasses under it. This update includes those gas details on the Gasses page as well, so someone looking in either location would find the same gas details.
Changes the Gasses page in the guidebook, as a sub-entry under Atmospherics
I've had a number of people ask about new gasses, and say they went to the guidebook to find them but couldn't see it. They were surprised it was under atmos, and not under the sub-heading specifically for gasses
Guidebook only changes.
N/A
N/A
**Changelog**
> Updates Gasses page in the guidebook

- Resources/Prototypes/Maps/Pools/default.yml
This PR reduces the amount of maps in rotation, trying to offer a good mix between low, medium, and high pop maps.
The quality of maps is difficult to ensure when we have so many and so much custom content when compared to Wizden or other forks. We are also going to be including several roles that are not present in upstream and this is the best way to ensure that all maps can reach the same level of quality that is demanded.
Generally, our goal is to up the amount of maint tunnels in these maps and try to give antags more room to breathe, as we feel that a lack of maints tunnels and places to hide hinder the antag experience.
Below are my reasonings for picking these maps, other maintainers and members of the community are free to comment:
Reach: fun map for low pop and is only expected …
> Reduce map pool from 19 to 8

- Resources/ServerInfo/_Goobstation/Guidebook/Medical/Medicalpatches.xml
Very minor guidebook fix I noticed while reading the medical guidebook
Before fix (current round):
After fix:
**Changelog**
too minor to warrent cl
> Fix 'Makeshift' header in Medicalpatches.xml

- Resources/Locale/en-US/chat/emotes.ftl
- Resources/Prototypes/Voice/speech_emotes.yml
- Resources/Prototypes/_DV/Entities/Mobs/Species/vulpkanin.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/ipc.yml
- Resources/Prototypes/_EinsteinEngines/Voice/speech_emotes.yml
- Resources/Prototypes/_Funkystation/tags.yml
Fixed other species' ability to click (and popping up on the emote wheel) IPC and vulp-exclusive emotes
They still work for Silicons and Harpies for the applicable emotes
Added a new IPCEmotes tag, following what was done for Vulps, and whitelisted all relevant emotes
:cl: Miiish
- fix: Fixed IPC and Vulp emotes on the emote wheel
> Fixes IPC & Vulp emotes displaying for other species

- Content.Shared/Clumsy/ClumsySystem.cs
Title, entities with ClumsyComponent can now be put onto tables and into biomass reclaimers (if they are dead)
Previously, you couldn't put clowns and/or monkeys into biomass reclaimers, and you could continually bonk a corpse into losing its limbs.
Added a check in the OnBeforeClimbEvent that checks if the entity is dead before tablebonking them.
**Changelog**
:cl: Miiish
- fix: Monkeys and clowns can now have their biomass reclaimed.
> Clumsy things can now be put onto tables and biomass reclaimers

- Resources/Prototypes/Body/Parts/base.yml
- Resources/Prototypes/Body/Parts/vox.yml
- Resources/Prototypes/_DV/Body/Parts/harpy.yml
- Resources/Prototypes/_DV/Body/Parts/rodentia.yml
- Resources/Prototypes/_DV/Body/Parts/vulpkanin.yml
Removes Limb Ashing from all species as an experimental change for random RR reduction. Experiment to see if our fork would just be better off without it.
Losing your head forever or just being flat out removed from a random bit of superheating sucks for basically everyone, for the average player once you walk into a place that's superheated it's fairly unlikely you both get out in time + cool down fast enough to not ash, and a lot of people end up getting RRed this way when such occurs. Granted it is still *hard* to come back from with this change, but not *impossible*.
Simply comments out the ash behavior for all limb parts.
**Changelog**
:cl:
- remove: Body parts will no longer turn into Ash when taking semi-large amounts of heat damage.
> Experimental: Remove Limb Ashing

- Content.Shared/Implants/Components/ImplanterComponent.cs
- Content.Shared/Implants/SharedImplanterSystem.cs
- Content.Shared/Revolutionary/SharedRevolutionarySystem.cs
- Resources/Prototypes/Entities/Objects/Misc/implanters.yml
- Resources/Prototypes/_Goobstation/Entities/Objects/Misc/implanters.yml
Prevented Revs from Mind Shielding themselves, they should never be doing this anyway, and any circumstances of occurences are silly but highly consequential accidents or invalid actions roleplay-wise.
The Head Rev's fast draw implanter now crushes implants it removes, its purpose is removal of mind shields, and you shouldn't have to mind shield random station pets to be able to use it again.
Cut all implanter times in half, it took 5 years to draw before to prevent implant checking by Security, this problem has been highly mitigated by the specified implant draw system and self-damage on fail. As compensation for this however still, standard implanters will now deal 90 damage to the failed implanter, rather than 60, nearly critting them.
The Head Rev's fast draw implanter fail damage has …
> Revs: implanter draw changes, prevent rev self-mindshielding

- Resources/Prototypes/Catalog/uplink_catalog.yml
For some reason the fake mindshield purchase had no product assigned, so now it does
**Changelog**
:cl:
- fix: The Fake Mindshield Implant can now actually be purchased in the Syndicate Uplink, instead of purchasing thin air.
> Fix Fake Mindshield Implanter

- Content.Shared/Salvage/Fulton/FultonComponent.cs
Added the "PhysicalComposition" component to the whitelist in FultonComponent.cs
I did this because the broken-down generators found by salvage couldn't be fultoned, despite the functional generators being able to. As it turns out, most items in the game are covered by the Item and Anchorable tags, and I haven't found anything like a mob that has the PhysicalComposition tag.
See #709 
**Changelog**
:cl:
- fix: Fixed fultons not attaching to scrap generators
> Added "PhysicalComposition" to the fulton whitelist 

- Content.Server/_Funkystation/Atmos/EntitySystems/CrystallizerSystem.cs
Removes the minimum moles needed in the temperature regulator to perform temperature changing processes.
Fixes a bug
None
:cl:
- fix: Crystallizer will no longer maintain temperature with a low amount of gas in it's regulator port.
> Update CrystallizerSystem.cs to fix skipping temperature calculations

- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
Gives the Blueshield Cargo and Atmos access, gives Blueshield a CentComm radio, removes Blueshield's extra survival box.
BSO's job is to protect command and CentralCommand VIPs. Currently they can't communicate with just the other centcomm employees, and they also can't access a lot of the station where Command members could be harmed. Ex: CE gets killed in atmos, and BSO slams their fists against the glass atmos airlock, sobbing while they watch the atmosians drag the CE into the burn chamber.
**Changelog**
:cl:
- tweak: Granted Blueshield extra access, and a centcomm overear headset.
- fix: Removed Blueshield's extra survival box.
> general BSO tweaks.

- Content.Server/_Impstation/Thaven/ThavenMoodSystem.cs
- Content.Shared/_Impstation/Thaven/SharedThavenMoodSystem.cs
- Resources/Prototypes/_Impstation/Species/Thavens/Moods/no_and.yml
- Resources/Prototypes/_Impstation/Species/Thavens/Moods/wildcard.yml
- Resources/Prototypes/_Impstation/Species/Thavens/Moods/yes_and.yml
reimplemented some moods, with job requirements for who can roll them. moods are now rolled after jobs, so if the job event doesn't run (ex. initial launch into the dev map) then thavens won't get their initial moods. shouldn't be an issue in game. mainly command thavens cant roll certain moods that would fuck up the round. also prevented thavens from being emagged if they are mindshielded (though it is still very obvious if you tried). 
this is my first time using EQEs so hopefully its okay??? plz let me know if i need to change something
**Changelog**
:cl:
- add: some more thaven moods have been added, though only certain jobs can roll them
- tweak: mindshielded thavens can no longer be emagged
> thaven job requirements + emag interaction

- Content.Server/_Funkystation/Atmos/Portable/ElectrolyzerSystem.cs
Changes the electrolyzer's power consumption so that it will slowly ramp down in power, fixing issues with flickering. Turning off the electrolyzer will reset it's power draw to baseline. 
Unfortunately SS14 doesn't deal with varying power levels too well. This is the easiest solution for the problem at the moment. 
The electrolyzer powerload will only drop by 100kW per second. Might be a bit overkill but it protects against flickers even with setups that use a large amount of electrolyzers in a single chamber. The alternative is having them draw a consistently high power, so I find this is better. 
None
None
**Changelog**
:cl:
- tweak: Electrolyzer powerload will now return to baseline more slowly, causing fewer power fluctuations.
> Electrolyzer power fix

- Resources/Prototypes/_Goobstation/Changeling/Roles/Antags/changeling.yml
Remove sec time requirement for changeling.
This seems like it was just mistakenly included in the [IPC port PR](https://github.com/funky-station/funky-station/pull/183)...
But also, selfishly? I just don't want to security, really.
I yaml'd a little
**Changelog**
:cl:Quantus
- tweak: Removed security time requirement for Changeling.
> Remove sec time requirement for changeling.

- Resources/Maps/_Funkystation/cluster.yml
… 
Adds economy computers, a salvage recycler and silo relay, bluespace gas tech, a medical biofabricator, AI core turrets (yay!), a crystallizer, and some very minor layout changes to cluster.
Because these things are neat and make cluster better and genpop stuff isn't 100% done yet.
**Changelog**
- add: added economy computers and lockboxes to cluster
- add: added a salvage recycler and silo relay to cluster
- add: added a bluespace gas sender and 3 vendors to cluster
- add: added a medical biofabricator to cluster morgue
- add: added a crystallizer to cluster atmos
- add: added four AI core turrets to cluster
- tweak: changed size of the cluster armory to fit more hardsuits and to move the swat crate into it
- tweak: slightly changed the cluster engineering main area in order to move …
> Cluster Temporary Touch-up

- Content.Server/_Funkystation/Atmos/Portable/ElectrolyzerSystem.cs
- Content.Server/_Funkystation/Atmos/Reactions/HydrogenFireReaction.cs
- Content.Shared/Atmos/Atmospherics.cs
Completely redid the HydrogenFireReaction to more closely follow /tg/ hydrogen fires. This will make them far more consistent and solves an issue with water vapor being overproduced by the reaction in a far neater way than it currently is. 
This also slightly buffs the efficiency of electrolyzers when it comes to making hydrogen as the changes solve part of the reason for the efficiency cap.
Hydrogen fires are meant to act exactly like tritium fires but without the radioactive element, so when originally adding hydrogen, I just modified the existing tritium fire code thinking it was solidly written. I was wrong. Tritium fires just don't make a lot of sense in ss14. This will allow hydrogen fires to act more consistently and cleanly output an amount of heat and water vapor that actually …
> Rework hydrogen fires to make more sense

- Content.Client/_Funkystation/Atmos/UI/CrystallizerWindow.xaml
- Content.Client/_Funkystation/Atmos/UI/CrystallizerWindow.xaml.cs
- Content.Server/_Funkystation/Atmos/EntitySystems/CrystallizerSystem.cs
Adds a max limit of 250 mol/s to the crystallizer's input rate. The UI also now displays the recipes in order. 
The input rate should have been limited to a maximum of 250 mol/s in the first place, and UI changes are just for cosmetic reasons.
None
None
**Changelog**
:cl:
- fix: The crystallizer's max input rate is now capped to 250 mol/s
> crystallizer ui tweaks and cap input rate

- Resources/Maps/_Funkystation/cluster.yml
- Resources/Prototypes/_Goobstation/Maps/cluster.yml
This PR changes the layout of Cluster's medbay, making it less open and more defined.  Two surgical wards have been added, alongside a few changes to the general setup of where everything is on the map.
I really like cluster's overall feel as a map, and so I wanted to improve its medbay to make it more usable.
Shows everything
Just fullbright
As the players would see it
Would you like to play a game? (what happened to the original maints surgery room)
**Changelog**
:cl:
- tweak: changed the design of the medbay to make it more usable
- tweak: changed one of the tables in the armory into a rack
- tweak: added an EOD suit locker to the sec locker room
- tweak: converted the maints surgery room into a potential saw trap room
- tweak: added a paramedic locker and opened the paramedic role on …
> Cluster Medbay Changes

- Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
Fixes the bug related to the digital audio workstation board that made the musician hardsuit impossible to craft.
Resolves issue #805.
Re-added the tag component to the digital audio workstation board entity. 
**Changelog**
:cl:
- fix: Fixed the bug that prevented musician hardsuits from being crafted.
> Digital Audio Workstation Boards Bugfix

- Resources/Prototypes/Entities/Objects/Consumable/Food/soup.yml
Made reptiloids (and anything that eats meat) able to eat chili
Chili has meat in it. Even the clown chili, chili con carnival, is a reference to the name chili con carne (which is just chili). It makes me sad when my lizard can't eat chili :(
Added the meat tag to all 3 chili dishes
https://github.com/user-attachments/assets/e57de345-716c-48b4-bbdd-3b0a0e16c80f
**Changelog**
:cl:
- tweak: Chili is now considered a meat dish.
> Makes reptiloids able to eat chili

- Resources/Prototypes/_Impstation/Reagents/Consumable/Drink/drinks.yml
- Resources/Prototypes/_Impstation/Reagents/biological.yml
I disallowed Thaven Blood and Fever Dream from affecting Thaven with hallucinations. 
The blood is in them all the time. There's no reason it should affect them. Currently, can take blood out currently with a syringe, inject it back in, and get high. Fever Dream is a drink derived from Thaven blood, and also likely shouldn't affect them.
No balance changes.
Added a conditional to the narcotic effect for both yml entries. I followed the code format of their carpotoxin immunity.
**Changelog**
:cl:
- tweak: Thaven are immune to the drug effects of Shimmering Blood and Fever Dream.
> Thaven blood doesn't affect Thaven

- Resources/Prototypes/_Shitmed/Body/Organs/Animal/animal.yml
Add the eyes tag to the animal eyes, so that it can be used in heretic rituals.
This allow the heretic to use animal eyes when eyes are required for rituals
Add the eyes tag to the animal eyes
**Changelog**
:cl:
- add: Animal eyes can be used in heretic rituals (animal eyes now have the eyes tag assigned to it)
> Add eyes tag to animal eyes

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/_Funkystation/Recipes/Lathes/rehydrateable.yml
Velociraptor Cubes are now available in emagged biocube fabricators. They cost 10 sheets of plasma (5x that of abomination cubes) and 20 units of biomass.
The Dino Wars must continue.
They are still very expensive unless Botany gets a large supply of plasma, and only spawn velociraptors rather than the assorted dinocube box zookeepers and scientists can buy.
:cl: Miiish
- add: Added velociraptor cubes to emagged biocube fabricators
> Adds Velociraptor Cube to emagged biocube fabricators

- Content.Server/_Goobstation/Changeling/ChangelingSystem.Abilities.cs
- Content.Server/_Goobstation/Changeling/ChangelingSystem.cs
- Content.Shared/_Goobstation/Changeling/AbsorbedSystem.cs
- Content.Shared/_Goobstation/Changeling/ChangelingComponent.cs
- Content.Shared/_Shitmed/Body/Systems/SharedBodySystem.Targeting.cs
- Resources/Locale/en-US/_Goobstation/changeling/abilities/changeling.ftl
- Resources/Prototypes/GameRules/roundstart.yml
- Resources/Prototypes/Recipes/Lathes/rehydrateable.yml
- Resources/Prototypes/secret_weights.yml
- Resources/ServerInfo/Guidebook/ServerRules/Metashield.xml
**Changelog**
:cl: taydeo, Rainbeon
- tweak: Changelings can now sting one alive person for DNA extraction, then other targets must be either crit or dead.
- add: Changelings now eat random non-vital organs and a limb when absorbing someone.
- remove: Removed hollowing text on absorbed bodies, and removed genetic damage dealt when absorbing.
- remove: Ferrochromic Acid no longer replaces someones blood when absorbed.
- tweak: The metashield for Changelings has been changed to account for hollowing changes, and now allows for bloodtests in very specific circumstances.
- tweak: The Medical Biofabricator is now significantly cheaper to operate, with prices being more than halved overall for all objects except the Heart.
- tweak: All organ and limb print times have been reduced to 10 seconds …
> Changeling/Antag weight Update

- Resources/Prototypes/_Funkystation/Atmospherics/crystallizer.yml
Increases the amount of CO2 needed to create a diamond in the crystallizer by 10 times. This should stop this from being abused as an exceptionally easy way to make huge amounts of funds for the station. Suggested by @Terkala
CO2 required from 1500 -> 15000
Currently it is far too easy to make an insane amount of cash quickly due to the sell price of diamonds and how quickly they can be made.
N/A (one value)
N/A
**Changelog**
> Crystallizer Rebalance

- Content.Server/_Goobstation/GameTicking/Rules/BlobRuleSystem.cs
- Resources/Locale/en-US/_Goobstation/blob/blob.ftl
Just Blob blocking shuttle recall
When there are zombies and a blob on the station simultaneously, the zombie event continually tries calling the evac shuttle, while the blob continually recalls it, leading to annoying announcement spam. This situation is particularly common on Survival.
Just deleted the code for recalling the shuttle from blob, and removed reference to shuttle being unable to be called
**Changelog**
:cl:
- remove: Removed blob blocking shuttle recall
> Shuttleloop hotfix

- Resources/ServerInfo/Guidebook/Mobs/Species.xml
moved two letters around
because otherwise it's incorrect
:)
it breaks my mind that this typo exists
**Changelog**
nah
> Fix incredibly important typo in the species guidebook page

- Resources/Prototypes/_Funkystation/Entities/Clothing/Eyes/glasses.yml
Removed protectionTime from Jamgoggles so you don't take any damage from welding at all as opposed to taking a little every time. Oops!
They're engineering goggles, full protection is a requirement.
Removed "protectionTime" line from Resources/Prototypes/_Funkystation/Entities/Clothing/Eyes/glasses.yml (line 104)
Bug reported at https://github.com/funky-station/funky-station/issues/900
**Changelog**
> Fix protectionTime from Jamgoggles

- Content.Server/Atmos/EntitySystems/BarotraumaSystem.cs
Humans dead in space no longer automatically delimb after a few minutes
If they still have a lot of part damage, it is still possible for their parts to spontaneously fall off
You shouldn't gib from being in space/low pressure, this will likely reduce incidental round removal / med headache tons so people can get back in the action
Just multiplies part/individual limb damage taken by barotrauma by 0.1
**Changelog**
:cl: Miiish
- fix: Fixed low-pressure delimbings on corpses
> Prevents humanoids delimbing/gibbing from low pressure

- Resources/Prototypes/_Impstation/Entities/Mobs/Species/thaven.yml
I changed two words in the code to fix an oversight. Thavens now actually have separate screams for each gender
It was really annoying that female thavens would use the male scream.
I changed two words across two lines in Resources/Prototypes/_Impstation/Entities/Mobs/Species/thaven.yml
**Changelog**
:cl: amethystowo
- fix: Thavens no longer all have unisex screams, and now have separate screams for each gender.
> Thavens are fixed now, everyone clap

- Content.Server/Destructible/Thresholds/Behaviors/RemoveOrganicShield.cs
- Content.Server/_Goobstation/Changeling/ChangelingSystem.Abilities.cs
- Content.Server/_Goobstation/Changeling/ChangelingSystem.cs
- Content.Shared/_Goobstation/Changeling/ChangelingComponent.cs
- Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Shields/shields.yml
Delete organic shield Uid in changeling equipment dictionary if destroyed.
When your organic shield gets destroyed, if you recast the ability, it will not do anything, but still cost you chemicals.
You have to cast it a second time to have your shield back. This made the organic shield one of the least used ability, due to its high cost (having to trigger it twice once broken) and low return of investment (fleshmend was simply superior).
Now that this is fixed, organic shield should see the light more often now, and have a real benefit to the player.
If the shield isnt destroyed, the player will still have to retract it and pay the full ability price.
When the organic shield is destroyed, it was not removing itself from the equipment list in the changeling component. This issue was fixed …
> Organic shield fix

- Resources/Prototypes/Catalog/uplink_catalog.yml
Slightly increased ammo prices all around, prevented power gaming as nukies with millionaires being banned from Ops but still readily available for the daring traitor.
Dual millionaires will one shot any person no matter the armour. For sec and their movement slowing hardsuits, this is a death sentence. Against a lone traitor? Flashes and stun grenades and such can be enough to take down someone like this. But a nukie team with these things?  They will just down any person in front of them. The ammo was cheap and I don't want to change that but they should be using the Hiristov and not just the infinitely better gun.
Minor YAML changes.
**Changelog**
:cl:
- tweak: Slightly changed ammo costs. The Millionaire's is not nerfed but is traitor exclusive.
> Update Changelog (#929)

- Content.Shared/Zombies/PendingZombieComponent.cs
- Resources/Prototypes/Entities/Objects/Specific/Medical/randompill.yml
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/secret_weights.yml
Removes Zombies from the roundstart and midround antags pool.
Zombies are very half-baked (well, just old and unmaintained really) and don't really mesh within rounds. Additionally, they derail pretty much every round they're in and are unable to be cured via, for example, a system like Virology. In lieu of an entire overhaul, this disables them from rolling. This does not remove Romerol, so there is still potential for zombie-ops and traitor gimmicks.
Removed Zombies from the roundstart pool as well as midround events. No more zombies that aren't player-or-admin made. This does not remove Romerol.
Adds Romerol as a 0.1% (1/1000) chance to the maints pills pool.
Removes poison damage for pending zombies, as well as any warning that you're infected. Best not get bit!
**Changelog**
:cl: …
> Readds Self-Insert Plushies

- Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
- Resources/Prototypes/Entities/Mobs/Player/familiars.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
- Resources/Prototypes/Entities/Mobs/Species/moth.yml
- Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
- Resources/Prototypes/Entities/Mobs/base.yml
- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
- Resources/Prototypes/_EinsteinEngines/Entities/Mobs/Player/silicon_base.yml
I've increased the cold damage from temperature loss across the board by about 5x
While spacing is a real threat currently, cold damage is pathetic outside of the actual slowdown it gives you, especially when compared to fire damage. This is the beginning part to a Void heretic buff I will be making a PR for after, however this PR doesn't actually affect void because Void sucks ass.
Ultimately, this PR makes the Emergency EVA less useful in a full spacing, as it protects from the pressure still, but doesn't protect from the cold of space as well as a proper hardsuit or EVA suit, as it should be. Previously, you could wear an Emergency EVA and never really notice any ill effects when in space, or a completely spaced area.
I edited the coldDamage value under Temperature wherever I could …
> Multiplies cold temperature damage by 5

- Content.Server/Containers/ThrowInsertContainerComponent.cs
- Content.Server/Containers/ThrowInsertContainerSystem.cs
- Resources/Prototypes/Entities/Mobs/Species/slime.yml
This buffs the effective rate at which trash lands in the trash bin if you throw an item at it. Players are rewarded for an "accurate" throw that would have "landed" in the vicinity of the trash can with an extra roll to get in.
Comes with free goofy crap because having something thrown at you as a slimeperson only to have it embed in your own personal storage is funny.
Original hit rate for disposal units was 25% due to some backward code. This was frustrating. MALD PR DETECTED
Also, funny.
A "good throw" gets defined as a throw which would "land" within 0.2 seconds of colliding with the trash can. If it's a "good throw", the probability to hit is rolled _twice_ and passes if either roll succeeds.
**Changelog**
:cl:
- tweak: Disposal units now more receptive of thrown items. Aim well for …
> Buff throwing away items + slimes become ThrowInsertContainer because funny

- Resources/Locale/en-US/reagents/meta/toxins.ftl
Removes mention of Dexaline Plus from Heartbreaker toxin
Dexaline plus no longer exists
> One line Change

- Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs
This change will properly update the ammo indication UI when reloading an in-hand weapon, such as an Enforcer, Kammerer, etc. 
Now players can have an accurate view of how many rounds are in a weapon. Previously, the ammo indicator UI would only update when the weapon was fired, or if the weapon was dropped and reequipped. 
The change is very simple, UpdateAmmoCount is now invoked within the SimulateInsertAmmo function. This will cause the ammo count to be updated when ammo is inserted from an AmmoProvider on an in-hand weapon.
https://github.com/user-attachments/assets/cf6f5ebd-15a7-4b47-8b52-d9d18b6a47f9
The ammo indicator UI at the bottom of the screen is now updated upon insertion of ammo directly into the weapon.
No known issues.
**Changelog**
:cl: nullrout3
- fix: Ammo indicator UI …
> Properly update UI ammo counter when ammo is directly inserted into an in-hand weapon (primarily shotguns)

- Resources/Prototypes/_DV/Voice/speech_emote_sounds.yml
This PR allows rodentia to scream properly.
Currently, speaking, screaming and squeaking uses the same sound for rodents. Which makes no point in squeaking/screaming, since the sounds are identical. Rodents' sounds are identical to human ones except for screaming, we also removed their smaller size and ability to crawl under tables which doesn't make them small n' squeaky anymore.  This PR makes screaming sound like actual screaming, and keeps squeaking so you can squeak. 
https://github.com/user-attachments/assets/b3a51c8f-6cb1-48dd-b423-8d5a29a2619b
- [ x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x ] I have added media to this PR or it does not require …
> Fix rodentia screams

- Content.Server/_Goobstation/Blob/BlobTileSystem.cs
Removed flashbang dealing damage to blobs.
This is something that was intentionally added in but doesn't really seem to fit with the blob and seeeems like an exploit.
Just commented out the OnFlashAttempt in the BlobTileSystem, so now flashes won't do anything.
Additionally, removed unused usings.
https://github.com/user-attachments/assets/b1c14a9a-fe95-4c31-b582-b684200af955
**Changelog**
:cl: Miiish
- tweak: Blobs no longer take damage from flashbangs.
> Removes Flashbang dealing damage to Blobs

- Resources/Locale/en-US/rcd/components/rcd-component.ftl
The RPD uses the FTL entry of "pumpsvalves", which didn't exist in the RCD FTL. I renamed the existing "pumps" entry to "pumpsvalves" to fix this.
This did work, I just didn't bother taking a screenshot
> Fixes missing FTL entry for the Pumps & Valves section of the RPD

- Resources/Prototypes/Catalog/VendingMachines/Inventories/atmosdrobe.yml
- Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
- Resources/Prototypes/Roles/Jobs/Wildcards/reporter.yml
- Resources/Prototypes/Roles/Jobs/Wildcards/zookeeper.yml
Changes the white shoes of the Atmospheric Technician, Reporter, and Zookeeper
The white shoes are horrifically ugly for anything but the Medical department and even then it's pushing it. They're horrible as placeholders too, and I'd genuinely rather just see the black shoes.
Using workboots for the Zookeeper is a bit questionable, but I choose that as the lesser of many evils and it's not contraband so whatever
(here's how the zookeeper would look with black shoes. still not perfect)
**Changelog**
:cl: Minerva
- tweak: Atmos Technician, Reporter, and Zookeeper no longer start with white shoes. The AtmosDrobe has been changed accordingly. Look for a ClothesMate if you liked them.
> Changes the white shoes of the Atmospheric Technician, Reporter, and Zookeeper

- Resources/Prototypes/_DV/Entities/Objects/Weapons/Melee/home_run_bat.yml
_I promise this isn't a mald pr I am making this as someone who has USED this a few times_
- Decreased the blunt damage of the bat from 30 to 27, so it shouldn't kill unarmoured targets in 3 swings
- Massively nerfed the swing speed to 0.40 to prevent knockdown stunlocking
- Decreased the entity launching speed from 30 to 20
Full swing speed on the bat allows for effortless knockdown stunlocking, sometimes even on multiple people at once. Getting hit should only trip you for 0.1 second while you're launched (as the stuntime on hit is 0.1) but because getting back up now has a do-after, it's closer to 1.5 seconds on the floor...which was long enough to stunlock someone as long as there's a wall to hit them into, since the weapon had base swing speed and getting hit while knocked down …
> Home-Run Bat Nerf

- Content.Client/_Goobstation/Heretic/Ritual.CustomBehaviors.cs
- Content.Server/_Goobstation/Heretic/Ritual/CustomBehavior.Ascension.cs
- Resources/Locale/en-US/_Goobstation/Heretic/heretic/rituals.ftl
- Resources/Prototypes/_Goobstation/Heretic/Heretic/heretic_rituals.yml
The heretic must complete all its sacrifices objectives in order to ascend.
Currently, heretics can passively gain knowledge through rifts and unlock their ascension ritual fairly easily. During that time, security can do very little to prevent them, as part of the removal of EOC, since the heretic doesn't need to commit any crimes (apart from trespassing). Once the heretic unlocked its final ritual, he simply needs to collect three bodies to trigger the ascension, potentially wiping the entire station without giving security a chance to prevent it.
It is very often to see a heretic ascending without completing its tasks, which is weird considering ascending should be the final goal.
This change aims to stop heretics from being a passive antagonists until they go loud through ascension, …
> Heretic ascension

- Content.Server/Station/Systems/StationSpawningSystem.cs
See title. When players are spawned into station jobs via roundstart or latejoin, their PDA's ID card is assigned a job, including accesses. This means we don't need to run PresetIdCard and assign the ID card a job, including accesses, because it's already done.
This is ostensibly an upstream bug and I will be filing it as such on Wizden. I won't claim to know the best way to solve this; if they have a better idea, feel free to pull that when they fix it.
_I do not know if this somehow breaks some weird edge case somewhere._ All I did was check to make sure that NTR's accesses are correct and that the game doesn't implode.
This PR fixes #1078.
This fixes an issue with the Nanotrasen Representative, who uses a CentComm PDA, of which its accesses normally don't match Nanotrasen …
> Prevent setting ID card accesses twice when spawning players in jobs

- Resources/Locale/en-US/_Impstation/thavens/no-and.ftl
- Resources/Locale/en-US/_Impstation/thavens/shared.ftl
- Resources/Locale/en-US/_Impstation/thavens/wildcard.ftl
- Resources/Locale/en-US/_Impstation/thavens/yes-and.ftl
- Resources/Prototypes/_Impstation/Species/Thavens/Moods/no_and.yml
- Resources/Prototypes/_Impstation/Species/Thavens/Moods/shared.yml
- Resources/Prototypes/_Impstation/Species/Thavens/Moods/wildcard.yml
- Resources/Prototypes/_Impstation/Species/Thavens/Moods/yes_and.yml
Added new Thaven moods.
The existing pool is a bit stale, especially the shared moods, so I wanted to add more.
- (Shared) The Royal Realm: The station is a feudal realm. The captain is king, the department heads nobility, and the rest of the station knights, servants, or peasants.
- (Shared) Oathbound: A thaven must honor all oaths made. A thaven may never directly tell a lie, but can hide the truth through deceptive wording.
- (Shared) Prank War: A clownish spirit has infected the station, and you find friendly pranks, especially against fellow Thaven, to be great fun.
- (Shared) People of the Stars: Like their carp-kin, Thaven are beings of the stellar sea. You feel drawn to space, whether to explore, discover, or construct something new.
- (Shared) Gourmet Gassier: Oxygen and Nitrogen …
> New thaven moods

- Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
- Resources/Prototypes/_DV/Entities/Mobs/Species/harpy.yml
I added the AnomalyHost tag to felinids and harpies to fix a bug where they could not be infected with an anomaly. While I have not tested this, there's no reason this fix should not work.
Fixing bugs is good :godo:.
I added the AnomalyHost tag to felinid.yml and harpy.yml
**Changelog**
:cl: amethystowo
- fix: Fixed a bug where felinids and harpies could not become the host of infection anomalies.
> :boom: :cat: :boom: :bird: 

- Resources/Prototypes/Catalog/spellbook_catalog.yml
- Resources/Prototypes/Magic/event_spells.yml
Removed Rod from wizard's spellbook, and changed summon spells for Funky. Now both summon-guns and summon-magic will not make players free agents. Also added new unique funky guns to the gun pools, and removed station-destroying effects from both pools (no explosives like china-lake or fireball) and instakill effects. Hopefully makes wizard into a state where we can re-add it to the gamemode pool (as a separate PR).
Making Wizard more MRP friendly
Commented out some lines, added yml for the new guns, and flipped a true to a false for the make-antag flag.
Also added the Mind Swap spell that was added to Wizden after our last merge, we have the back-end code for it to work, so why not?
Casting Summon Guns, did not make 2nd connected user into an antag. Same for summon magic.
Rod spell …
> Funking up Wizard

- Resources/Prototypes/Catalog/Cargo/cargo_food.yml
I increased the prices for pre-prepared food and drinks from the request computer.
As the prices currently are, people (including cargo (and salv)) can just buy food, and completely ignore the chef. While they can still buy food, they have to earn that pizza party with fundraisers now :fire: 
Oh holiest YAML paladin Miiiiiiish(@DevilishMilk), I took it upon mineself to follow in your holy path, and edited the YAMLs to suit my needs!
**Changelog**
:cl: amethystowo
- tweak: Increased pre-prepared food and drink prices. Get to fundraising for that pizza party!
> I :heart: :man_cook: :fire: :+1: :pray:

- Resources/Locale/en-US/accent/cowboy.ftl
When Cowboy-accented characters said "worried", it would be replaced with "cowboy-accent-replace-89" due to an error I placed in the file here: https://github.com/funky-station/funky-station/pull/1069. This PR fixes that.
I am bad at typing.
1 character change btw
N/A
n/a
**Changelog**
:cl:
- fix: Fixes a bug where cowboy accent characters would replace "worried" with "cowboy-accent-replace-89"
> Fixes Cowboy Accent 

- Content.Server/Administration/Commands/SetOutfitCommand.cs
After doing an archaeological exploration of the fucking `SpawnAndDeleteAllEntities` test fail, I eventually tracked down the bug to an issue where `InternalEncryptionKeySpawner` was being Created Anew Every Time instead of being Accessed Properly. The actual `InternalEncryptionKeySpawner` system factually must be accessed via `entityManager.System<T>()`, avoiding a dumbass scenario where `EntityManager` turns up null in the middle of calling `TryInsertEncryptionKey`.
Fixes #1037.
💩🧹
💩💩💩💩🧹
Yes, I checked if this worked by spawning a fuckton of cluwnes and by manually setting assorted outfits on an IPC and prying the keys to see what went in.
**Changelog**
no cl no fun
> Fix cluwne IPC test fails

- Content.Server/Chat/Systems/ChatSystem.LoocBudget.cs
- Content.Server/Chat/Systems/ChatSystem.cs
- Content.Shared/_Funkystation/CCVars/CCVars.Funky.cs
- Resources/Locale/en-US/_Funkystation/looc-budget.ftl
- Resources/engineCommandPerms.yml
Applied formatting to `ChatSystem.cs` (it was completely messed up).
Added `ChatSystem.LoocBudget.cs` to handle looc budget stuff.
Added two cvars `funky.looc_budget_enabled`: if the LOOC budget system is enabled and `funky.looc_budget_default`: the default budget for each player.
Added admin console command `looc_budget` to set a player or everyone's LOOC budget.  Usage is as follows:
`looc_budget <user | all> <budget> <refill budget> <inform user>`
where user is the target, budget is the new budget to set (the max LOOC messages), refill budget is a bool which when set to true will reset the player's sent LOOC message counter back to zero, inform user is a bool which when set to true will give the user a message telling them they have had their LOOC budget adjusted and to what number. …
> Add LOOC budget

- Content.Server/Cloning/CloningSystem.Subscriptions.cs
- Content.Server/Cloning/CloningSystem.cs
More things have special cloning handling in CloningSystem! PDAs (and their contents) and ID cards (and their accesses and NanoChat ID number and chat history) get copied.
Fixes #1163.
less metagaming!!! wooo!!!
Also bringing the PDA cloning in line with the other "exact state of things" cloning is a good thing. Pushes it further and further toward social deduction.
Additional `CloningItemEvent` subscriptions were added to handle `IdCardComponent`, `AccessComponent`, `PdaComponent`, and `NanoChatCardComponent`. These items, if not properly set up, will result in differences that can out Paradox Clones.
The `NanoChatCardComponent` in particular copies the original's NanoChat card number, causing messages sent to the original to also be sent to the clone. The clone's NanoChat card is …
> Paradox Clone improvements: PDAs etc.

- Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
- Content.Server/Nuke/NukeComponent.cs
- Content.Server/Nuke/NukeSystem.cs
- Content.Shared/Nuke/NukeDiskComponent.cs
- Resources/Locale/en-US/nuke/nuke-component.ftl
Ported the microwave-nukedisk interaction (https://github.com/space-wizards/space-station-14/pull/36114) from Wizden.
Comedy. More microwave reactions are good.
From the original PR (https://github.com/space-wizards/space-station-14/pull/36114): 
> Adds a new NukeDiskComponent.TimeModifier datafield that is combined with the NukeComponent's Timer datafield to set the remaining time when the nuke is ready to be armed. Unless it already has a value, the disks time modifier will be randomly assigned whenever the disk is first microwaved, and there is no way to know what the modifier is until the disk is in the nuke & the code has been entered.
Video from original PR (https://github.com/space-wizards/space-station-14/pull/36114):
https://github.com/user-attachments/assets/78120c0c-3c62-4566-ad …
> Ports the microwave-nukedisk interaction from Wizden

- Content.Server/Chat/Systems/ChatSystem.LoocBudget.cs
- Content.Server/Chat/Systems/ChatSystem.cs
- Resources/Locale/en-US/_Funkystation/looc-budget.ftl
- Resources/engineCommandPerms.yml
Add looc_budget_get to quickly query a player's LOOC budget
**Changelog**
> Fix LOOC budget not being reset after round end

- Content.Server/EntityEffects/Effects/PlantMetabolism/PlantCryoxadone.cs
Cryoxadone will no longer prevent plants from producing fruit when expected if they were de-aged later in their life cycle.
(This fixes #1150.)
🌱
This just sets LastProduce to the resulting Age of the plant. This is 1:1 with Wizden code on the same matter.
**Changelog**
:cl:
- fix: Cryoxadone no longer causes plants to cease fruiting in certain circumstances.
> Fix cryoxadone on plants causing plants to stop fruiting

- Resources/Maps/_Harmony/centcomm.yml
- Resources/Prototypes/_Goobstation/Mail/mailDeliveries.yml
Removes the Plushie Throngler from CentComm; makes it 10x as rare as it currently is through mail.
I hate fun.
**Changelog**
:cl: Miiish
- remove: Removed the throngler plushie from CentComm
> Kills the Throngler Plushie

- Content.Server/_Goobstation/Flashbang/FlashbangSystem.cs
Your over-ear headset now works correctly and protects you from a flashbang's stun at range. Certain helmets that offer the same protection should also work.
eeeeeeeeeeeeeeee
Instead of coding on hopes and dreams, replaced a function with something that actually makes a check.
**Changelog**
:cl:
- fix: Over-ear headsets now actually and correctly protect against flashbang stuns.
> Make hearing protection actually protect against flashbangs

- Content.Server/_DV/Cargo/Components/StationLogisticStatsDatabaseComponent.cs
- Content.Server/_DV/Cargo/Systems/LogisticStatsSystem.cs
- Content.Shared/Cargo/SharedCargoSystem.cs
Fixed an issue causing roundstart station budget to skyrocket higher and higher the longer the server was running.
_[SALARY CUTTING NOISES]_
so THAT'S why that line was commented out
went and peeked at dV to see what they did to their own systems to account for departmental accounts, did what they did, reasonable enough fix
**Changelog**
:cl:
- fix: Roundstart budget no longer balloons out of control.
> Obscenely high roundstart budget fixed

- Content.Server/_Funkystation/HFR/Systems/HypertorusFusionReactorSystem.cs
- Resources/Prototypes/_Funkystation/Entities/Structures/Machines/Atmospherics/hfr.yml
Lowers the power draw for the HFR from 250kW to 100kW.
There are already many obstacles to atmos techs setting up the HFR. Making sure your power network can support it will still be one of them but it shouldn't be as much of an issue as it is. With it lowered to 100kW, any secondary power generator, like the AME or the solar arrays on most stations, should be enough to safely run it, allowing you to even separate it from the main power network entirely if you wish. 
None
None
**Changelog**
:cl:
- tweak: HFR power draw has been lowered from 250kW to 100kW
> Lower HFR power draw

- Resources/Prototypes/Catalog/Cargo/cargo_atmospherics.yml
- Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
- Resources/Prototypes/_NF/Recipes/Construction/Graphs/utilities/storage_canister.yml
- Resources/Prototypes/_NF/Recipes/Construction/utilities.yml
Port of craftable gas canisters from frontier. Canisters can be crafted or broken down for 5 plasteel. The storage canister, and all other gas canisters are also now 500 specos cheaper to order through cargo. 
Canisters shouldn't be as rare a commodity as they are. 
None
**Changelog**
:cl:
- add: Gas canisters can now be constructed and deconstructed.
> Craftable canisters

- Resources/Prototypes/secret_weights.yml
Modified Secret roundstart weightings.
Completely removed Blob and Blobtraitor from the roundstart pool.
Bumped Revolutionaries from 15% to 10%
Added the remainder of these over to Traitor, changeling, and Survival.
Staff discussion from a few days ago.
For blob rounds:
Blob always feels underwhelming as an inherent roundstart gamemode due to hinging the round on one person, and works best as a midround antagonist where it serves as a diversion of time and resources to the main antagonists of the round. That's not to say it's not incredibly powerful if ignored.
Revolutionaries are my favorite gamemode, but they can be pretty exhausting and slug-festy. Lowering the chances of it rolling makes it feel more special when it does roll, IMO.
**Changelog**
:cl: Miiish
- tweak: Tweaked roundstart …
> Roundstart weight tweaks

- Resources/Locale/en-US/game-ticking/game-ticker.ftl
When your character has they/them pronouns and you latejoin, it says "<character> have arrived at the station!" This is driving me insane so I fixed it to always say has.
I will scream and cry and break things if this doesn't get merged
changed one line of localization
**Changelog**
:cl:
- fix: latejoin announcements now properly use "has" instead of "have" for characters with they/them pronouns
> Grammar fix on latejoin text

- Content.Shared/Item/SharedItemSystem.cs
Put code block back in conditional statement that it needed to be in. Fixed desword bug.
Fixed technical bug.
Desword stopped working after this [pr](https://github.com/funky-station/funky-station/pull/1164) which cleaned up code in the file. The block was out of a conditional it was meant to be in though. I put the code block back in the enclosing conditional, and it works again.
**Changelog**
:cl:
- fix: Fixed code bug causing desword to fail
> fixed bug causing desword failures

- Resources/Prototypes/InventoryTemplates/arachnid_inventory_template.yml
Arachnid web slots can hold items without a jumpsuit, but are always visible in the strip menu
A recent update made it so Arachnid web slots were identical to regular pocket slots, but this was not intentional
edits arachnid_inventory_template.yml a total of 4 lines
N/A
none, very basic YML changes
**Changelog**
:cl: hereelabs
- fix: Arachnid web slots can now hold items without a jumpsuit again, but are always visible.
> Fix: Arachnid Web Slots

- Resources/Locale/en-US/thief/backpack.ftl
- Resources/Prototypes/Catalog/thief_toolbox_sets.yml
Swapped the Storage Implant for the Freedom Implant in the Thief's Anatomy Kit.
As thieves no longer need to steal and keep specific objects, the storage implant makes brazenly stealing objects unhealthily free, allowing them to steal things and whisk them away into the void preventing them from being punished despite how obvious the theft may have been. Then they may after be deposited somewhere else afterward, and the cycle may continue.
In compensation, it has been replaced with a Freedom Implant, as it fits with the overall theme of the anatomy kit and its other contents.
**Changelog**
:cl:
- tweak: Replaced the Thief's Anatomy Kit Storage Implanter with a Freedom Implanter.
> Thief: Swap Storage for Freedom Implant

- Content.Shared/_EE/Overlays/Switchable/ThermalVisionComponent.cs
Recent update made the thermal vision system start erroring, causing enhanced eyesight to do nothing. My question is not "why did this break?", my question is "why was this not ALREADY broken????". Shout out to enhanced eyesight for working for exactly 1 update cycle before breaking.
bug
1 line change. Thermal vision was not networked for some reason, causing attempting to dirty it to throw an error. Once again, I really don't understand why this has only NOW become an issue.
**Changelog**
> Fix thermal vision 

- Content.Server/GameTicking/GameTicker.Lobby.cs
- Content.Server/Preferences/Managers/IServerPreferencesManager.cs
- Content.Server/Preferences/Managers/ServerPreferencesManager.cs
- Content.Server/ReadyManifest/ReadyManifestSystem.cs
Fixed the ready manifest.
bug fix
Previously, if you ran `toggleready true/false`, it would increment or decrement job counters regardless of if your ready state is actually changing. This resulted in negative numbers on the manifest, as entering the character customization screen would force unready (even if you weren't ready).
Additionally, my multi-char changes adds the ability to change your job priorities (via drag and drop) while readied, so a new event and some logic is added to handle these cases.
https://github.com/user-attachments/assets/ded08390-190e-4977-bfd8-1578290cbcee
https://github.com/user-attachments/assets/497749b6-ce3a-42ce-bba3-6ad63e5c952d
https://github.com/user-attachments/assets/8768e1da-1691-4454-a112-1b5ca66bd524
none
**Changelog**
:cl: Quantumcross
- fix: …
> Fix ready manifest

- Content.Server/Implants/RadioImplantSystem.cs
- Content.Server/Radio/Components/ActiveRadioComponent.cs
- Content.Server/Radio/Components/IntrinsicRadioTransmitterComponent.cs
- Content.Server/Radio/EntitySystems/RadioSystem.cs
- Content.Server/_DV/CosmicCult/Abilities/CosmicFragmentationSystem.cs
- Content.Server/_DV/CosmicCult/CosmicCultRuleSystem.cs
I've fixed issues with encryption keys overriding implanted radio channels in IPCs.
IPCs no longer lose access to any implanted channels when switching out their encryption keys.
I've added new "implicit" channels to ActiveRadioComponent and IntrinsicRadioTransmitterComponent, that will be untouched by the EncryptionKeyHolderComponent. This solves the issue of EncryptionKeyHolder wiping all channels and building it from scratch using only the keys it has inserted.
I've gone through and switched implants and cosmic cult to use the new intrinsic channels.
This also adds a couple helpers in the RadioSystem.cs, for easier readability and logic implementation.
**Changelog**
:cl:
- fix: IPCs who gain channels in a manner other than an encryption key will no longer lose it when changing keys.
> implicit radio channels

- Resources/Prototypes/Catalog/Fills/Items/belt.yml
- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
- Resources/Prototypes/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/healthanalyzer.yml
- Resources/Prototypes/_Funkystation/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/_Funkystation/Entities/Objects/Misc/PDA_cartridge_case.yml
Removed the MedTek from Medical crew and the BSO.
Boosted health analyzer charge by 50%, so it should now hold about 7.5 minutes of constant use.
The MedTek seems a bit odd and out-of-place, and makes the health analyzer completely redundant. Why bother using this cool specialized tool if I have a constantly-charged better one constantly on me?
yml edits galore
**Changelog**
:cl: Miiish
- remove: Removed the MedTek cartridge from crew PDAs.
- add: Doctors and Paramedics now start with health analyzers.
- tweak: Boosted health analyzer charge capacity by 50%
> Removes MedTek cartridge from crew PDAs, boosts health analyzer usage a bit

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/Research/arsenal.yml
Changes the Experimental Battery Ammo T3 arsenal research into a T2 one
and also now makes it unlock the portable recharger
Svalinns can also now be made in the Security Techfab
And Portable Rechargers can now also be made in the Protolathe 
Svalinn contraband rating is changed from Security to Security+Cargo (mostly for the sake of salvagers being able to use them)
(And also changes the Contraband rating of the Retro Laser Blaster from Major to Security)
currently the Svalinn is a incredibly underused weapon due to it being restricted as a T3 arsenal tech
with the shift in focus to giving the station a more laser focused arsenal, seems like a good time to change it
and the same for the portable recharger
its very expensive crafting cost alongside it being restricted to T3 arsenal makes …
> Svalinn tweaks

- Content.Server/_EinsteinEngines/Radio/IntrinsicRadioKeySystem.cs
- Content.Shared/PAI/SharedPAISystem.cs
- Resources/Locale/en-US/store/pai-catalog.ftl
- Resources/Prototypes/Catalog/pai_catalog.yml
- Resources/Prototypes/Entities/Objects/Fun/pai.yml
I've added a new store listing to the pAI shop, that enabled pAIs to accept encryption keys to hear (but not speak to) more channels.
I feel this will help pAI's become more helpful to their owners, so they can be more in tune with what their owner's department is doing and offer advice if needed. pAI's can still speak over binary.
Other than adding the store listing and event, I also modified how the EncryptionKeyHolderComponent works to check if the entity is a pAI, and if it does, it does not modify what the pAI can speak to.
**Changelog**
:cl:
- add: The pAI store now contains an upgrade to allow a pAI to hear (but not speak on) more radio channels.
> pAI shop add encryption

- Content.Server/_DV/CosmicCult/CosmicCultRuleSystem.cs
added a check to disable steward revote after phase 3 has begun
cosmic cult crashing the game after their rounds is too op
see the commit
This fixes the major crash that was happening, which is the only one I could reproduce. so if there are other ways it was crashing then those might still happen.
honestly, if someone who's less tired than I am rn just wants to go in and add checks to all the places people are just indexing lists without any regard for memory safety that would probably be good. There's a lot of places that cause similar crashes, including a fuck ton in atmos code.
also. I kind of just assumed here that the different rulesystems get restart round to round. if not then only the first cosmic cult round after a server restart will allow revotes. :godo:
I am like, 95% sure …
> Fix cosmic cult crash

- Content.Shared/Access/Components/IdCardConsoleComponent.cs
- Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml
- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
- Resources/Prototypes/Roles/Jobs/Security/detective.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
- Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
- Resources/Prototypes/Roles/Jobs/Wildcards/security_clown.yml
LICENSE: MIT
Fixes some genpop related issues, namely:
- ID card computers can now assign genpop accesses
- Access configurators can change those accesses
- All security personnel and HoP now have genpop access
Having weird intangible accesses in your brig is pain. Source: my security experience since genpop was added in.
YAMLmaxxing except for that ID card computer part where i added strings to an array because for some reason that is hardcoded WHY.
N/A
None I think
**Changelog**
:cl:
- fix: All security personnel can now access genpop.
- fix: ID card computers can assign genpop accesses.
- fix: Access configurators can apply genpop accesses to things.
> Genpop fixes

- Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
LICENSE: MIT
Gave BSO genpop accesses.
I forgot to do that in my previous fix PR.
Now all crew jobs with Security access should also have Genpop access, as I checked.
That being said, in case someone else should have this access (like rest of Command), now is a good time to bring that up so I can fix it before they have to deal with it until next release again. Pretty sure only crew with Security access, not just Brig, had access to prison cells before Genpop though.
YAMLmaxxing
N/A
**Changelog**
:cl:
- fix: Blueshield Officers now have Genpop accesses.
> Genpop fix for BSO access

- Content.Shared/Armor/SharedArmorSystem.cs
- Resources/Locale/en-US/armor/armor-examine.ftl
- Resources/Prototypes/_Funkystation/Catalog/Cargo/cargo_engineering.yml
- Resources/Prototypes/_Funkystation/Catalog/Fills/Crates/engineering.yml
- Resources/Prototypes/_Goobstation/Entities/Clothing/Head/helmets.yml
- Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/specific.yml
I added an purchaseable HEV equipment crate for 5000 spesos that includes a HEV suit, crowbar, and nitrogen/oxygen tanks. Adjusted HEV suit & helmet descriptions and changed naming from H.E.V to HEV. 
All suits that don’t ash in contact with the SM now display this in their armor examine text.
The HEV suit is currently only rarely available, either by being mapped in or through low-chance radiation locker spawns. Aside from the CE hardsuit, it's the only hardsuit that resists contact with the SM. The HEV suit is also useful for other departments like Science, who often need proper hardsuits instead of relying on EVA suits. The new crate increases availability while the 5000 spesos price tag keeps it a significant investment and can be adjusted for balance if needed.
- Added …
> Purchaseable HEV Suit Crate and Ashing Immunity Tooltip

- Content.Server/_DV/CosmicCult/CosmicCultRuleSystem.cs
Fixed cosmic cultist retaining astral murmur after deconvert.
Bug. #1405 
I missed the initial addition of the channel, so it went to the standard channels instead of implicit ones.
Additionally, it will no longer wipe any previously-implanted channels.
**Changelog**
:cl:
- fix: Fixed Cosmic Cultists retaining the Astral Murmur after being deconverted.
> Fixing Astral Murmur on deconversion

- Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/vests.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
- Resources/Prototypes/_Funkystation/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Armor value pass, secfab change, disabler SMG projectile switchover
> Lasers pass #3 - armor value changes

- Content.Server/Radio/EntitySystems/RadioSystem.cs
- Content.Shared/Radio/RadioChannelPrototype.cs
- Resources/Prototypes/radio_channels.yml
This PR removes the ability to speak on the common channel through your headset. You need to use the intercom to scream for help.
The removal of greencomms changes a lot.
No more screaming for help at security because you broke into science and made yourself a PKA. Now, you have to actually incite a riot naturally.
Antagonists get more leeway. No longer will your sneaky stealth roleplay be shut down instantly because of a tider. You have room for error and you can more easily hide your acts. Gives more room to do stealth. Be one with the shadows.
The reporter is the main source of information. This should encourage more actual reporter roleplay and not just being a glorified tider with an announcement board. (This may require a sop rewrite..)
Service should see more usage because the bar …
> Nerfing Greencomms

- Content.Server/Morgue/MorgueSystem.cs
Title
very annoying
Added a check to giving the morgue tray the HasSoul appearance to check if the entity has the Unrevivable component or not
https://github.com/user-attachments/assets/320897e6-01f0-49bd-b4bf-6f76972ae927
**Changelog**
:cl: Miiish
- tweak: Unrevivable people no longer trigger the morgue soul alarm.
> Unrevivable entities don't trigger the revive alarm in the morgue

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
Changes the Deckards caliber from .45 magnum into .50 shotgun shells 
The Deckard has always been a somewhat forgotten weapon, supposedly intended as a emergency weapon to use for command, it being only 5 shots of .45 meant it rarely makes a differance 
With the laser arsenal slowly on its way and most balistics exept for shotguns being phased out, seems like a oportunity to give it some much needed attention.
With 5 shotgun shots that can be fired in pretty rapidly it would now be a supprisingly effective weapon for emergencies 
And it would make it stand out as a properly unique weapon rather than just a borderline sidegrade to the inspector.
Due to not being able to use a speed loader on it, instead needing to load 1 shell at a time, helps reinforce it as more of a emergency weapon for …
> Shotgun Deckard 

- Content.IntegrationTests/Pair/TestPair.Recycle.cs
- Content.IntegrationTests/Tests/Round/CharacterSelectionTest.cs
- Content.Server/Antag/AntagSelectionSystem.cs
Thanks to @Terkala for helping me find this one.
Char 1: Alice
- Enabled
- No antag
Char 2: Bob
- Disabled
- Thief antag
If you late joined as Bob, and were selected to be a late join thief, it would fail as you have no enabled characters with thief selected.
Now late join antag selection will specifically look at the character profile that is joining.
bug fix
The fix is well commented, the tests are kino.
nope
**Changelog**
:cl:
- fix: Fix Late join antag selection if you have no "active" characters with a specific antagonist role.
> FIX late join antag selection, add character selection integration tests, add some more admin logging

- Resources/Prototypes/Catalog/Fills/Items/firstaidkits.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Increased first aid kit slot capacity from 4x2 to 5x2.
It still remains a 4x2 item in bags, so now you have 2 extra slots.
All first aid kits now come with a health analyzer.
Combat medkit has been removed from the medlathe
Incentivizes nicer and more sensible usage of storage containers, feels better than dumping everything in your bag being the optimal solution.
It's not TARDIS technology, it's just a visual representation of a better-organized box rather than having everything be loose.
Combat medkit has been killed from the medlathe as it's a 2x2 container with (now 5x2) units of space that cost the same amount of plastic as the base medkit.
**Changelog**
:cl: Miiish
- remove: Combat medkits are no longer available in the medlathe.
- tweak: First aid kits now have 10 slots of …
> first aid kit slot increase, combat medkit removed from medlathe

- Resources/Prototypes/Catalog/Fills/Items/belt.yml
- Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
- Resources/Prototypes/Entities/Objects/Devices/pda.yml
- Resources/Prototypes/_Funkystation/Entities/Objects/Misc/PDA_cartridge_case.yml
Re-adds MedTek (but not to BSO as it is dead) and reverts most of the accompanying changes, except the changes to battery length
Overall, the MedTek Removal experiment has ended up with mostly negative, for little actual gain in-game. Roleplay quality has not seen any real benefits from removing it, and its only effect on such is requiring several breaks throughout the shift (or often, throughout the same surgery operation) that slows down Medical care in a way that is not fun for either the performing Medical staff or often-helpless Victim. 
In macro-effects, it has contributed to an uptick in Surgery rottings as well, and has had a negative impact on who is actually healing people in the Medbay in crisis scenarios (Med Interns tend to get left in dust, aimless overall, as more …
> They re-Moved Medtek?

- Resources/Maps/_Funkystation/elkridge.yml
The test fails will not be my fault this time
Elkridge:
- Added material silos to every department
- Fixed missing atmos in Salvage
:cl:
- add: Material silos are now available on Elkridge
- fix: Unspaced the new Salvage bay on Elkridge
> Elkridge updates and fixes for the Week of Sep. 4

- Content.Server/_Impstation/CartridgeLoader/Cartridges/SOSCartridgeComponent.cs
always was intended to, just forgot to make this change
- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
**Changelog**
:cl: PurpleTranStar
- fix: SOS now correctly pings the paramedic and warden.
> SOS now properly pings the warden and paramedic

- Content.Server/Radio/EntitySystems/RadioSystem.cs
- Content.Shared/Radio/Components/IntercomOnlyBypassComponent.cs
- Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
- Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
- Resources/Prototypes/Entities/Mobs/Player/silicon.yml
- Resources/Prototypes/_DV/Entities/Structures/Power/Generation/Supermatter/supermatter.yml
Adds the IntercomOnlyBypass Component. A blank component that allows headsets and some specific characters to talk in common as if they were an intercom.
This allows specific objects that speak on common (SM) to actually be able to type in common. Also allows the ability to create headsets that can type in common. 
Just a blank component called IntercomOnlybypass. It checks for that in the code. Previously, only the Intercom component and Silicon Law Bounds were checked.
- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
**Changelog**
:cl: PurpleTranStar
- fix: The Supermatter will …
> IntercomOnlyBypass

- Resources/Prototypes/_Funkystation/Recipes/Reactions/alcohol.yml
Pineapple Margherita recipe now requires 2u of pineapple juice instead of 1u.
Feedback from Talus: Currently the minimum batch is 16, which doesn't have a common multiple with 30 until 240, and using multiples of 5 gets you 80. doubling the pineapple juice will bump the minimum batch up to 20, which goes into 60, and using multiples of 5 gets you 100u, which is exactly enough to fill a shaker.
Single line update, changed 1 to 2.
**Changelog**
:cl:
- tweak: The Pineapple Margherita drink recipe now requires 2u of pineapple juice for better batch sizes.
> Increased PineappleMargherita pineapple juice to 2u

- Resources/Prototypes/Entities/Structures/Machines/lathe.yml
see title
I keep finding exploits with IPC torsos, and they are quite literally useless to people who aren't trying do some exploit or other.
So no harm done in removing them from the exosuit fabricator.
yaml
:cl:
- remove: Pulled IPC torsos from the exosuit fabricator because Shitmed continues to live up to its name
> Removed IPC torso from exosuit fabricator

- Resources/Prototypes/_Funkystation/Roles/Jobs/CentComm/magistrate.yml
Changed the magistrate playtime requirements to be 100 hours in the security department.
In initial discord discussions regarding porting the Magistrate to Funky, the goal was to demand 100 security hours to play the role. In doing so, we both match the playtime requirement from [Paradise Station](https://www.paradisestation.org/wiki/index.php?title=Magistrate) and require a deep understanding of Space Law from any potential Magistrate players.
Initially added to Funky on [July 7, 2025](https://github.com/funky-station/funky-station/pull/793), under playtime requirements of 20 overall hours and 5 Nanotrasen Representative hours, the playtime requirements were changed on [July 25, 2025](https://github.com/funky-station/funky-station/pull/1217) to be 10 hours in Head of Security, 10 hours …
> Magistrate playtime requirement is now 100 sec hours

- Resources/Locale/en-US/xenoarchaeology/artifact-hints.ftl
- Resources/Prototypes/XenoArch/artifact_triggers.yml
Added the rolling and slicing artifact triggers.
So science has some interaction with the kitchen, if they require an kitchen knife or rolling pin. And also a way for antags to get a weapon secretly.
Added lines in "Resources/Prototypes/XenoArch/artifact_triggers.yml" and "Resources/Locale/en-US/xenoarchaeology/artifact-hints.ftl" (see changelist of this pull request)
None
**Changelog**
:cl:
- add: Added rolling artifact trigger
- add: Added slicing artifact trigger
> Rolling and slicing artifact triggers

- Content.Client/_DV/TapeRecorder/UI/TapeRecorderWindow.xaml
- Content.Client/_DV/TapeRecorder/UI/TapeRecorderWindow.xaml.cs
I added a time display in the corner of Tape Recorder's UI window.
Having used a tape recorder in-game for a bit, I noticed that it's not too convenient for replaying particular parts of the tape, as replay and rewind speeds are different, and on a 2-minute-long recording a slider is not a very precise way to gauge where you are in it. As recording transcripts already display the timestamp of every recorded message on the tape, I decided it would be convenient to include a way to tell exactly what second it is on at any given point.
I edied one .xaml and one .xaml.cs files connected to Tape Recorder UI. One change added a Duration Label to the UI window, the other one made it change depending on the playback slider position.
https://github.com/user-attachments/assets/7b49ba7c-7dd5-4a44-9e2 …
> Time display for Tape Recorder UI

- Resources/Prototypes/Reagents/narcotics.yml
ForeverWeed is now 2x stronger than THC
people weren't getting high enough from forever weed, this should fix it.
- [ X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
**Changelog**
:cl: PurpleTranStar
- tweak: Rainbow Cannabis brownies are no longer ain't shit
> ForeverWeed is now 2x stronger than regular THC

- Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
- Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
- Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
- Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
increased the threshold for trainee roles to be locked out of from 20 hours to 35 hours, and for security its 40 hours. note, after reaching 20 hours you can still play, for example, a regular sec off. so before you type away, no, we didnt increase playtime requirements.
players feel intimidated by being thrown into the deep end of a role too early. giving them more breathing room respects their time and gives them more room to learn.
**Changelog**
:cl:
- tweak: Increased intern lockout time for Engineering, Science, and Medical from 20 hours to 35 hours.
- tweak: Increased intern lockout time for Security from 20 hours to 40 hours.
> We want More Interns

- Content.Server/Communications/CommunicationsConsoleComponent.cs
- Content.Server/Communications/CommunicationsConsoleSystem.cs
- Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
LICENSE: MIT
fucked up the last pr lol
Added a bool to allow us to set whether or not a comms console can change the alert level.
True by default, the only two I disabled it on are the syndi and wizard consoles.
It might be beneficial to do this for some of the head's comms consoles as well if someone thinks so, but idrc about that atm
Useful for antag comms consoles and any consoles for which you don't want the ability to set the alert level
new datafield in CommunicationsConsoleComponent, just an additional or check in CommunicationsConsoleSystem, both changes commented
N/A
**Changelog**
:cl: Miiish
- tweak: Syndicate comms computers can no longer change the alert level.
> canAlert - adjust whether or not comms consoles can set alert levels
